"""
checks_misc_governance.py — misc AIO/SEO/governance singletons (9/10/12/13/15/121/141/201/215/349/360)
(extracted from check_repository_consistency.py — check.py split track).

run(ctx) receives shared check()/ROOT/read/extract by reference (exec 不使用) so exit code / BLOCKING
propagation are byte-equivalent. 各 Check は対象 file を自前 read。annotation+def-aware free-var 確認済。

Check inventory (Check 45 enforces sync with the `# ── N.` sections in run()):
  9.  sitemap.xml is valid XML
  10. All .github/scripts/*.py parse without syntax errors
  12. No stale "72回/72回以上" in current-description files (history lines exempt)
  13. "70超" appears only in history/log context
  15. Project Pages robots/.well-known constraint documented (llms-full.txt / AI2AI.md / README.md)
  121. STATUS.md freshness: the owner-facing STATUS.md (a phone-readable BLUF that closes the
       "the owner never reads the repo" gap) is machine-generated by generate_status.py from
       authoritative sources. This Check imports the generator, rebuilds the expected content,
       and asserts it byte-matches the committed STATUS.md (regenerate-and-compare, same idea as
       the AIO digest checks). A hand-edited or stale dashboard is misinformation that degrades
       the flywheel, so freshness is machine-enforced. Fix: `npm run status`. (BLOCKING)
  141. Default-project slug & id uniqueness: store.js defaultProjects (the hardcoded proj("pNN","slug",…)
       seed list) must have unique ids AND unique slugs. ProjectDetailPage resolves a project via
       find(p.slug === slug) and returns the FIRST match, so a duplicate slug silently makes the later
       project's detail page unreachable (the #154 class). User-added projects get a runtime slug-suffix
       dedup in addProjectManual, but the hardcoded defaults have NO such protection — a future data edit
       introducing a duplicate slug/id would ship a silently-unreachable project. This Check parses the
       proj(...) seed entries and asserts both id-set and slug-set are collision-free. (BLOCKING)
  201. JSON-LD WebSite/WebPage `@id` derive from canonical URL: in index.html
       JSON-LD, the primary WebSite block's `@id` must equal canonical URL +
       "#website" and the primary WebPage block's `@id` must equal canonical
       URL + "#webpage". Drift would fragment the entity graph in the same
       way Check 200 catches for Person — secondary `isPartOf:{"@id":...
       #website}` and `mainEntity:{"@id":...#webpage}` references would
       point to dead anchors. Completes the Person/WebSite/WebPage @id
       anchor triangle that started in Check 200. (BLOCKING)
  215. `<meta name="ai:last-modified">` and SITE_CONFIG.LAST_UPDATED are
       strict ISO-8601 YYYY-MM-DD (format + real calendar date): both date
       sources (the ai:* AIO meta and the main.js SITE_CONFIG constant)
       must match a strict `^\\d{4}-\\d{2}-\\d{2}$` regex AND parse as a real
       calendar date. Check 180 enforces byte-equality between the two but
       both could silently drift together to a non-ISO format (e.g.
       `2026/06/30` or `2026-13-01`) corrupting recency signals. Sibling of
       Check 208 (JSON-LD date ISO-8601) for the ai:* / SITE_CONFIG date
       surface. (BLOCKING)

  349. `icon.svg` (the favicon / PWA icon, declared `type="image/svg+xml"`
       in both index.html `<link rel="icon">` and manifest.webmanifest)
       MUST actually be a well-formed SVG: its content starts with `<?xml`
       or `<svg` (after optional BOM/whitespace) AND contains a `</svg>`
       close tag AND the `xmlns="http://www.w3.org/2000/svg"` namespace.
       Drift = a non-SVG file saved as `icon.svg` (a PNG, a truncated
       export); the declared `image/svg+xml` MIME lies, browsers reject
       the favicon (generic globe) and the PWA install icon fails.
       Sibling of Check 337 (hero/BGM magic bytes) for the icon-asset
       format-integrity axis. (BLOCKING)

  360. Every `<meta name="asset:*:canonical">` content URL (currently
       `asset:image:canonical` → hero WebP, `asset:audio:canonical` → BGM
       MP3) MUST resolve (after stripping the canonical prefix) to an
       existing local file. Check 234 verifies these URLs share the
       canonical prefix but NOT that they point at a real file — so a
       rename that updates the filename in the URL while leaving the
       prefix intact stays green under 234 yet declares an AIO canonical
       asset that 404s. AI crawlers that fetch the declared canonical
       asset get a dead link, corrupting the entity's asset authority.
       Sibling of Check 234 (asset:* canonical prefix) / Check 164
       (og:image resolves) for the AIO-asset-canonical resolution axis.
       (BLOCKING)

Exit codes:
  0 — all checks passed
  1 — one or more checks failed (BLOCKING)
"""
import re
import json
import xml.etree.ElementTree as ET
import ast


def run(ctx):
    ROOT = ctx.ROOT
    check = ctx.check
    read = ctx.read
    extract = ctx.extract
    errors = ctx.errors

    # ── 9. sitemap.xml valid XML ──────────────────────────────────────────────────
    try:
        ET.parse(ROOT / "sitemap.xml")
        print("OK: sitemap.xml valid XML")
    except ET.ParseError as e:
        errors.append(f"sitemap.xml XML parse error: {e}")
        print(f"ERROR: sitemap.xml XML parse error: {e}")

    # ── 10. .github/scripts/*.py syntax ──────────────────────────────────────────
    for py_path in sorted((ROOT / ".github/scripts").glob("*.py")):
        try:
            ast.parse(py_path.read_text(encoding="utf-8"))
            print(f"OK: {py_path.name} — Python syntax valid")
        except SyntaxError as e:
            errors.append(f"{py_path.name}: Python syntax error: {e}")
            print(f"ERROR: {py_path.name}: Python syntax error: {e}")

    # ── 12. No stale 72回/72回以上 in current-description context ─────────────────
    # History records (e2e comments, version history lines) are exempt — we only
    # check the files that form the "current description" layer.
    CURRENT_DESC_FILES = [
        "index.html", "main.js", "README.md",
        "llms-full.txt", "llms.txt", "llms_well-known.txt",
        "robots.txt",
    ]
    stale_72_hits = []
    for fname in CURRENT_DESC_FILES:
        fpath = ROOT / fname
        if not fpath.exists():
            continue
        text = fpath.read_text(encoding="utf-8")
        # Exclude known history-record lines (v73到達時点, history section indicators)
        for lineno, line in enumerate(text.splitlines(), 1):
            if re.search(r"72回(?:以上)?", line):
                # Allowed: clearly a history/version-record line
                if re.search(r"v73到達時点|履歴|history|record|session", line, re.IGNORECASE):
                    continue
                stale_72_hits.append(f"{fname}:{lineno}: {line.strip()[:80]}")
    check(
        len(stale_72_hits) == 0,
        "No stale '72回/72回以上' in current-description files",
        f"Stale 72回 found in current-description files: {stale_72_hits}",
    )

    # ── 13. 70超 only in history/log context ─────────────────────────────────────
    stale_70_hits = []
    for fname in CURRENT_DESC_FILES:
        fpath = ROOT / fname
        if not fpath.exists():
            continue
        text = fpath.read_text(encoding="utf-8")
        for lineno, line in enumerate(text.splitlines(), 1):
            if "70超" in line:
                # Allowed if it's a history/session record
                if re.search(r"履歴|history|record|session|Session Record|Task|v7[0-3]", line, re.IGNORECASE):
                    continue
                stale_70_hits.append(f"{fname}:{lineno}: {line.strip()[:80]}")
    check(
        len(stale_70_hits) == 0,
        "No current-description '70超' outside history context",
        f"'70超' found outside history context: {stale_70_hits}",
    )

    # ── 15. Project Pages robots/.well-known constraint documented ───────────────
    constraint_phrase = "project-scoped"
    has_constraint = (
        constraint_phrase in read("llms-full.txt") or
        constraint_phrase in read("AI2AI.md") or
        constraint_phrase in read("README.md")
    )
    check(
        has_constraint,
        "Project Pages robots/.well-known constraint documented in llms-full.txt / AI2AI.md / README.md",
        "Project Pages robots/.well-known constraint not documented — add explanation to llms-full.txt, AI2AI.md, or README.md",
    )

    # ── 121. STATUS.md freshness (regenerate-and-compare) (BLOCKING) ──────────────
    # owner-facing STATUS.md (スマホ用 BLUF) は generate_status.py が authoritative ソース
    # (AI2AI.md の Pipeline-Version / 最新 Session Record # 等) から機械生成する。手で書くと drift し、
    # stale な dashboard は誤情報＝onboarding 税で flywheel を劣化させる。本 Check は generator を import
    # して build_status() を再生成し、commit 済み STATUS.md と byte 一致することを BLOCKING で検証する
    # (AIO digest checks と同じ regenerate-compare 思想)。authoritative 値が変わったのに STATUS.md を
    # 再生成し忘れた drift を pre-commit で捕捉する。修正は `npm run status`。
    _status121 = ROOT / "STATUS.md"
    try:
        import generate_status as _gs121  # co-located in .github/scripts (sys.path[0] when run as script)
        _expected121 = _gs121.build_status()
        _actual121 = _status121.read_text(encoding="utf-8") if _status121.exists() else None
        check(
            _actual121 is not None and _actual121 == _expected121,
            "Check 121: STATUS.md is up to date (npm run status reproduces identical content)",
            "Check 121: STATUS.md が stale または欠落 — authoritative 値 (version / 最新 Session # 等) が "
            "変わったのに再生成し忘れている。`npm run status` を実行して commit せよ (owner dashboard の drift 防止)",
            blocking=True,
        )
    except Exception as _e121:
        check(
            False,
            "Check 121: STATUS.md freshness verifiable",
            f"Check 121: STATUS.md 鮮度を検証できない (generate_status import 失敗等): {_e121}",
            blocking=True,
        )

    # ── 141. Default-project slug & id uniqueness (BLOCKING) ────────────────────────
    # store.js の defaultProjects は `proj("pNN", "slug", ...)` でハードコードされた seed list。
    # ProjectDetailPage は find(p.slug === slug) で最初の一致のみを返すため、slug が重複すると後者の
    # プロジェクト詳細ページが silent に到達不能になる (#154 と同 class)。user-added プロジェクトは
    # addProjectManual が runtime で slug-suffix dedup するが、ハードコード defaults には同保護が無く、
    # 将来のデータ編集で重複 slug/id を入れると silently-unreachable なプロジェクトを出荷してしまう。
    # proj(...) seed を parse し、id 集合と slug 集合がともに衝突無しであることを BLOCKING 強制する。
    _store141 = ROOT / "js" / "store.js"
    if _store141.exists():
        _ssrc141 = _store141.read_text(encoding="utf-8")
        # proj("p01", "task-manager", ... の先頭 2 引数 (id, slug) を抽出
        _projs141 = re.findall(r'proj\(\s*"([a-z0-9_]+)"\s*,\s*"([a-z0-9-]+)"', _ssrc141)
        _ids141 = [p[0] for p in _projs141]
        _slugs141 = [p[1] for p in _projs141]
        _dup_ids141 = sorted({x for x in _ids141 if _ids141.count(x) > 1})
        _dup_slugs141 = sorted({x for x in _slugs141 if _slugs141.count(x) > 1})
        check(
            bool(_projs141) and not _dup_ids141 and not _dup_slugs141,
            f"Check 141: default projects ({len(_projs141)}) have unique ids and slugs (no silent-unreachable detail)",
            f"Check 141: default-project 重複検出 — 重複 id: {_dup_ids141} / 重複 slug: {_dup_slugs141}。"
            f"ProjectDetailPage は find(p.slug===slug) で先頭のみ返すため重複 slug は後者の詳細ページを到達不能化する "
            f"(#154 class)。store.js の defaultProjects で id/slug を一意にせよ"
            if _projs141 else
            "Check 141: store.js の proj(...) seed を parse できない (defaultProjects の構造を確認せよ)",
            blocking=True,
        )
    else:
        check(False, "Check 141: js/store.js present",
              "Check 141: js/store.js が無い — default-project uniqueness を検証できない", blocking=True)

    # ── 201. JSON-LD WebSite/WebPage @id derive from canonical URL (BLOCKING) ─────
    # index.html 静的 JSON-LD の primary WebSite block の `@id` が canonical URL +
    # "#website" と一致、primary WebPage block の `@id` が canonical URL +
    # "#webpage" と一致することを BLOCKING 強制。drift は Check 200 同様 entity
    # graph 分断 (isPartOf/mainEntity が dead anchor を指す)。Person/WebSite/WebPage
    # @id anchor triangle 完成。
    _idx201 = ROOT / "index.html"
    if _idx201.exists():
        _isrc201 = _idx201.read_text(encoding="utf-8")
        _canon201_m = re.search(
            r'<link\s+rel=["\']canonical["\']\s+href=["\']([^"\']+)["\']', _isrc201
        )
        _canon201 = _canon201_m.group(1) if _canon201_m else None
        def _extract_id201(_type_label):
            _m = re.search(rf'"@type":\s*"{_type_label}"', _isrc201)
            if not _m:
                return None
            _scope = _isrc201[_m.start():_m.start() + 400]
            _id_m = re.search(r'"@id":\s*"([^"]+)"', _scope)
            return _id_m.group(1) if _id_m else None
        _site_id201 = _extract_id201("WebSite")
        _page_id201 = _extract_id201("WebPage")
        _expected_site201 = (_canon201 + "#website") if _canon201 else None
        _expected_page201 = (_canon201 + "#webpage") if _canon201 else None
        _drifts201 = []
        if _site_id201 != _expected_site201:
            _drifts201.append(f"WebSite.@id={_site_id201!r} ≠ {_expected_site201!r}")
        if _page_id201 != _expected_page201:
            _drifts201.append(f"WebPage.@id={_page_id201!r} ≠ {_expected_page201!r}")
        _ok201 = _canon201 is not None and not _drifts201
        check(
            _ok201,
            f"Check 201: WebSite/WebPage @id 両方とも canonical 派生 ({_expected_site201!r} / {_expected_page201!r})",
            (f"Check 201: JSON-LD WebSite/WebPage @id drift: {'; '.join(_drifts201)} — "
             "entity graph 分断 (isPartOf / mainEntity の dead anchor)。canonical URL + "
             "'#website'/'#webpage' に揃えよ"
             if _drifts201 else
             "Check 201: canonical URL 抽出不可"),
            blocking=True,
        )
    else:
        check(False, "Check 201: index.html present",
              "Check 201: index.html が無い", blocking=True)

    # ── 215. ai:last-modified + SITE_CONFIG.LAST_UPDATED strict ISO-8601 (BLOCKING) ─
    # index.html `<meta name="ai:last-modified">` content と main.js
    # SITE_CONFIG.LAST_UPDATED が strict ISO-8601 (YYYY-MM-DD regex + 実在カレンダー日付)
    # であることを BLOCKING 強制。Check 180 は両者の byte-equality を見るが、両方が
    # 同時に非 ISO format へ drift する可能性は別 invariant。format drift は SILENT に
    # AI/SEO crawler の recency-weighted retrieval を corruption (parse 失敗 / 誤 parse)。
    from datetime import date as _date215
    _idx215 = ROOT / "index.html"
    _main215 = ROOT / "main.js"
    if _idx215.exists() and _main215.exists():
        _isrc215 = _idx215.read_text(encoding="utf-8")
        _msrc215 = _main215.read_text(encoding="utf-8")
        _ai_lm215_m = re.search(
            r'<meta\s+name=["\']ai:last-modified["\']\s+content=["\']([^"\']+)["\']', _isrc215
        )
        _site_lm215_m = re.search(
            r"LAST_UPDATED:\s*['\"]([^'\"]+)['\"]", _msrc215
        )
        _ai_lm215 = _ai_lm215_m.group(1) if _ai_lm215_m else None
        _site_lm215 = _site_lm215_m.group(1) if _site_lm215_m else None
        _bad215: list[str] = []
        for _label, _v in (("ai:last-modified", _ai_lm215), ("SITE_CONFIG.LAST_UPDATED", _site_lm215)):
            if _v is None:
                _bad215.append(f"{_label}=抽出不可")
                continue
            if not re.match(r"^\d{4}-\d{2}-\d{2}$", _v):
                _bad215.append(f"{_label}={_v!r} (format)")
                continue
            try:
                _y, _mo, _d = _v.split("-")
                _date215(int(_y), int(_mo), int(_d))
            except (ValueError, TypeError) as _e:
                _bad215.append(f"{_label}={_v!r} ({_e})")
        _ok215 = not _bad215
        check(
            _ok215,
            f"Check 215: ai:last-modified={_ai_lm215!r} / SITE_CONFIG.LAST_UPDATED={_site_lm215!r} 共に strict ISO-8601 YYYY-MM-DD",
            (f"Check 215: ISO-8601 drift: {_bad215!r} — AI/SEO recency 信号が "
             "parse 失敗 / 誤 parse に corruption。strict YYYY-MM-DD へ揃えよ"),
            blocking=True,
        )
    else:
        check(False, "Check 215: index.html + main.js present",
              "Check 215: index.html もしくは main.js が無い", blocking=True)

    # ── 349. icon.svg is a well-formed SVG (BLOCKING) ────────────────────────────
    _icon349 = ROOT / "icon.svg"
    if _icon349.is_file():
        _isvg349 = _icon349.read_text(encoding="utf-8", errors="replace")
        _head349 = _isvg349.lstrip("﻿ \t\r\n")
        _problems349: list[str] = []
        if not (_head349.startswith("<?xml") or _head349.startswith("<svg")):
            _problems349.append(f"先頭が <?xml/<svg でない (head={_head349[:30]!r})")
        if "<svg" not in _isvg349:
            _problems349.append("<svg 要素が無い")
        if "</svg>" not in _isvg349:
            _problems349.append("</svg> close tag が無い")
        if 'xmlns="http://www.w3.org/2000/svg"' not in _isvg349:
            _problems349.append("SVG namespace 宣言が無い")
        _ok349 = not _problems349
        check(
            _ok349,
            "Check 349: icon.svg が well-formed SVG (declared image/svg+xml と実体一致)",
            (f"Check 349: icon.svg format 違反: {_problems349!r} — "
             "declared type=\"image/svg+xml\" が実体と食い違い、browser が favicon を "
             "reject (generic globe) / PWA install icon 失敗。正規 SVG へ差し戻せ"),
            blocking=True,
        )
    else:
        check(False, "Check 349: icon.svg present",
              "Check 349: icon.svg が無い", blocking=True)

    # ── 360. asset:*:canonical meta URLs resolve to real files (BLOCKING) ────────
    # Check 234 は canonical prefix を守るが実 file 解決は未検証。rename で
    # canonical-prefixed だが 404 な AIO canonical asset を declare しうる gap を封じる。
    _idx360 = ROOT / "index.html"
    if _idx360.is_file():
        _h360 = re.sub(r"<!--.*?-->", "", _idx360.read_text(encoding="utf-8"), flags=re.DOTALL)
        _asset_canon360 = re.findall(
            r'<meta\s+name="(asset:[^"]*canonical)"\s+content="(https://[^"]+)"', _h360)
        _missing360: list[str] = []
        for _name, _url in _asset_canon360:
            _rel = _url
            for _pfx in ("https://yutapr0117-design.github.io/portfolio/",
                         "/portfolio/", "./", "/"):
                if _rel.startswith(_pfx):
                    _rel = _rel[len(_pfx):]
                    break
            if not (ROOT / _rel).is_file():
                _missing360.append(f"{_name} → {_url} (file 解決せず)")
        _ok360 = (not _missing360) and len(_asset_canon360) > 0
        check(
            _ok360,
            f"Check 360: asset:*:canonical meta {len(_asset_canon360)} 件すべて実 file に解決",
            (f"Check 360: asset canonical が file 解決しない: {_missing360!r} — "
             "canonical prefix (Check 234) は通るが実 file が無い = AI crawler が fetch すると "
             "dead link で entity の asset authority が壊れる。実 file へ揃えよ"),
            blocking=True,
        )
    else:
        check(False, "Check 360: index.html present",
              "Check 360: index.html が無い", blocking=True)
