"""mutation_samples_e2e_archive3.py — behavior mutation の 3 番目の archive。

archive2 が Check 365 の 1,000 行上限に達したため、最古の連続ブロックをここへ rotate した。
**archive も無限には伸ばせない** —— hot log を rotate する先が伸び続ければ同じ壁に当たる、
という consistency 側 (mutation_samples_archive / archive2) と同じ 2 段構成をここでも採る。
新規 mutation は mutation_samples.py の tail へ追記し、~975 行で archive2 へ rotate する。
"""
from mutation_samples_common import ROOT  # noqa: F401 (entry 内で参照)

E2E_MUTATIONS_ARCHIVE3 = [
    {
        "name": "behavior: task move の done 境界 disabled affordance の喪失 — apps.js の「次のステータスへ進める」ボタン `disabled: task.status === 'done'` を false へ → done 列でも next が有効に見え「これ以上進めない」UX affordance が壊れる (moveStatus の clamp はデータを守るが disabled 属性は別レイヤーの affordance。backlog 境界と対称の done 境界被覆の非 vacuity 検証)",
        "file": ROOT / "js" / "apps.js",
        "find": "disabled: task.status === 'done',",
        "replace": "disabled: false,",
        "test": "disabled at the done boundary",
    },
    {
        "name": "behavior: pomodoro 集中時間 input の範囲外 clamp の喪失 — pomodoro-page.js work onchange の clamp(...,1,180) を外し生 parseInt へ → 999 分等の範囲外値がそのまま settings.work に入り不正 duration の timer になる (number input max=180 は programmatic/paste を防がず JS clamp が実防御。上限/下限境界の非 vacuity 検証)",
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "s.appsData.pomodoro.settings.work = clamp(parseInt(e.target.value, 10) || 25, 1, 180);",
        "replace": "s.appsData.pomodoro.settings.work = parseInt(e.target.value, 10) || 25;",
        "test": "clamps out-of-range values",
    },
    {
        "name": "behavior: pomodoro 短休憩 input の範囲外 clamp[1,60] の喪失 — pomodoro-page.js short onchange の clamp(...,1,60) を外し生 parseInt へ → 999 分等が settings.short に入り work とは別 range の境界が壊れる (#838 work とは独立の range・独立 regress の非 vacuity 検証)",
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "s.appsData.pomodoro.settings.short = clamp(parseInt(e.target.value, 10) || 5, 1, 60);",
        "replace": "s.appsData.pomodoro.settings.short = parseInt(e.target.value, 10) || 5;",
        "test": "short/long break inputs clamp",
    },
    {
        "name": "behavior: pomodoro 長休憩 input の範囲外 clamp[1,120] の喪失 — pomodoro-page.js long onchange の clamp(...,1,120) を外し生 parseInt へ → 999 分等が settings.long に入り short(60) とも別 range の上限 120 境界が壊れる (独立 regress の非 vacuity 検証)",
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "s.appsData.pomodoro.settings.long = clamp(parseInt(e.target.value, 10) || 15, 1, 120);",
        "replace": "s.appsData.pomodoro.settings.long = parseInt(e.target.value, 10) || 15;",
        "test": "short/long break inputs clamp",
    },
    {
        "name": "behavior: AI submit の空/空白プロンプトガードの喪失 — ai-page.js submit の `!input.trim() ||` を外し aiLoading のみ残す → 空文字/空白のみの送信が握り潰されず空の会話を ai.history に積み UI/localStorage を汚す (settings の空入力バリデーションは test 済だが AI 空プロンプトガードは未被覆だった穴の非 vacuity 検証)",
        "file": ROOT / "js" / "ai-page.js",
        "find": "if (!input.trim() || aiLoading) {return;}",
        "replace": "if (aiLoading) {return;}",
        "test": "ignores empty and whitespace",
    },
    {
        "name": "behavior: task addTask の空/空白タイトルガードの喪失 — apps.js addTask の `if (!title.trim())` を常時 false 化 → 空文字/空白のみの Enter が空タイトル task を backlog に積む (AI #841 と同 class の入力バリデーションガード・task 面の非 vacuity 検証)",
        "file": ROOT / "js" / "apps.js",
        "find": "if (!title.trim()) {return;}",
        "replace": "if (false) {return;}",
        "test": "ignore empty/whitespace-only input",
    },
    {
        "name": "behavior: todo addTodo の空/空白テキストガードの喪失 — apps.js addTodo の `if (!text.trim())` を常時 false 化 → 空文字/空白のみの Enter が空テキスト todo を積む (task addTask とは別 function・独立 regress の非 vacuity 検証)",
        "file": ROOT / "js" / "apps.js",
        "find": "if (!text.trim()) {return;}",
        "replace": "if (false) {return;}",
        "test": "ignore empty/whitespace-only input",
    },
    {
        "name": "behavior: snapshot 復元ボタンの未保存時 disabled affordance の喪失 — settings-page.js の 復元ボタン `disabled: !snap` を除去 → snapshot 未保存でも復元ボタンが有効に見え「復元するものが無い」affordance が壊れる (restoreSnapshot は no-op guard 済だが disabled 属性は別レイヤーの UX affordance。#836 task done 境界と同 class・snapshot 面の非 vacuity 検証)",
        "file": ROOT / "js" / "settings-page.js",
        "find": "onclick: restoreSnapshot, disabled: !snap",
        "replace": "onclick: restoreSnapshot",
        "test": "disabled until a snapshot exists",
    },
    {
        "name": "behavior: router の unknown-app whitelist else 分岐の喪失 — router.js の `apps/<app>` で whitelist 外を 'not-found' にする else を 'app-task' へ → 存在しない app サブルート (apps/nonexistent) が task ページを描画し NotFound に落ちない (top-level unknown route とは別 code path の非 vacuity 検証)",
        "file": ROOT / "js" / "router.js",
        "find": ": 'not-found';",
        "replace": ": 'app-task';",
        "test": "Unknown app subroute",
    },
    {
        "name": "behavior: profile github/linkedin の URL スキームサニタイズ (#139 XSS) の喪失 — store.js safeUrl の http(s) スキームチェックを外し raw 値をそのまま返す → import した javascript:/data: 等の危険スキーム URL が ContactPage の href に載り XSS ベクタになる (既存 URL-sanitized test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証)",
        "file": ROOT / "js" / "store.js",
        "find": "return /^https?:\\/\\//i.test(s) ? s.slice(0, 500) : String(fallback || '');",
        "replace": "return s;",
        "test": "URL-sanitized",
    },
    {
        "name": "behavior: pomodoro getDuration の live-state 参照 (#134) の喪失 — pomodoro-page.js getDuration の `State.get()...settings` を render 毎キャプチャの stale closure `pomo.settings` へ戻す → 稼働中に集中時間を変えても complete() の remainingSec リセットが旧設定値を使う (getRemaining #121 と同根の stale-closure バグ。既存 mid-run test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証)",
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "const settings = State.get().appsData.pomodoro.settings;",
        "replace": "const settings = pomo.settings;",
        "test": "completion uses the latest focus-duration",
    },
    {
        "name": "behavior: AI 入力の IME composition ガード (#152) の喪失 — ai-page.js の Enter ハンドラから `&& !e.isComposing` を外す → 日本語入力で IME 変換確定の Enter が未確定テキストを誤 submit する (task IME #299 とは別 function・ai-input 独立の実バグ。日本語が主対象の本サイトで既存 test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証)",
        "file": ROOT / "js" / "ai-page.js",
        "find": "if (e.key === 'Enter' && !e.isComposing) {",
        "replace": "if (e.key === 'Enter') {",
        "test": "AI input ignores Enter during IME composition",
    },
    {
        "name": "behavior: nav-lab collapse 状態の reload 復元喪失 — components.js isLabOpen() の localStorage 読み戻し `=== 'true'` を常時 false 化 → reload 後に Lab 展開状態が失われ collapsed へ戻る (#826 で追加した field-persist reload round-trip の非 vacuity 検証。read-back 喪失で展開→reload→展開維持が RED)",
        "file": ROOT / "js" / "components.js",
        "find": "return localStorage.getItem(labKey) === 'true';",
        "replace": "return false;",
        "test": "Lab nav-group collapse state restores from localStorage across reload",
    },
    {
        "name": "behavior: home 統計カウンタが実データを反映しなくなる — js/home-page.js の TODO カウンタを state.appsData.todos.length から固定値へ置換 → 追加/削除しても数字が動かない silent な描画退行 (Stats は 3 カウンタとも state 由来のデータ駆動面だが e2e 未被覆で、値が固定化しても route 訪問テストは通る)",
        "file": ROOT / "js" / "home-page.js",
        "find": "h('div', { class: 'h2 color-warning' }, String(state.appsData.todos.length)),",
        "replace": "h('div', { class: 'h2 color-warning' }, '1'),",
        "test": "Home stat counters reflect real data",
    },
    {
        "name": "behavior: ResumePage の profile.title 描画喪失 — js/components.js の ResumePage の lead 見出しを State 由来から固定文字列へ置換 → import/設定した title が Resume に反映されなくなる。#/resume は内容レベルの e2e が皆無で route 訪問テストは「fatal なし・content 非空」で通るため、この描画退行は従来どの gate も捕捉できなかった (profile.title は sidebar と Resume の 2 箇所で描画されるデータ駆動値)",
        "file": ROOT / "js" / "components.js",
        "find": "h('h2', { class: 'h3 mb-4', 'data-ai-content': 'lead', lang: langOfText(State.get().profile.title) }, State.get().profile.title),",
        "replace": "h('h2', { class: 'h3 mb-4', 'data-ai-content': 'lead' }, 'Resume'),",
        "test": "Imported profile.title renders on both the sidebar and the Resume page",
    },
    {
        "name": "a11y: task/todo フィルタ変更の SR 通知喪失 — js/apps.js の todo 件数 status から role/aria-live を除去 (#1031 で assertive→polite へ移行済) → フィルタで一覧が変わっても SR には完全に無音 (通知領域には直前のアクション文言が残ったまま・#content 内 live region は 0 個) という実測 gap へ退行する (WCAG 4.1.3 Status Messages)",
        "file": ROOT / "js" / "apps.js",
        "find": "h('div', { class: 'sr-only', role: 'status', 'aria-live': 'polite', id: 'todo-filter-status' },",
        "replace": "h('div', { class: 'sr-only', id: 'todo-filter-status' },",
        "test": "Task and Todo filter changes are announced",
    },
    {
        "name": "a11y: quiz 検索のヒット件数アナウンス喪失 — quiz-renderer.js の resultStatus からヒット時の件数文言を空文字へ戻す → 0 件時だけ喋りヒット時は無言という旧非対称に退行し、SR 利用者は絞り込みが効いたのか結果が何件なのか分からない (WCAG 4.1.3 Status Messages・ProjectsPage は件数を通知しているのに quiz だけ無言だった実 gap の回帰防止)",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": "                    : '「' + query + '」に一致する問題 ' + matchCount + ' 件')",
        "replace": "                    : '')",
        "test": "Quiz search announces the match count",
    },
    {
        "name": "a11y: BGM ボタンの状態同期喪失 — js/ui-components.js の _syncAll から `btn.setAttribute('aria-pressed', String(_on))` を除去 → 再生中でも SR には常に「押されていない」と報告される (aria-pressed が false 固定)。BGM は behavior e2e 完全未カバーで Check 376 も action の解決しか見ないため、この退行はどの gate も通り抜けていた。新設 BGM a11y test の非 vacuity 検証",
        "file": ROOT / "js" / "ui-components.js",
        "find": "            btn.setAttribute('aria-pressed', String(_on));",
        "replace": "",
        "test": "BGM toggle syncs aria-pressed and aria-label",
    },
    {
        "name": "a11y: Toast の二重アナウンス再混入 — js/ui-components.js の toast コンテナへ aria-live を再付与 → 専用 sr-only 領域 #action-announcement (assertive) と視覚コンテナ (polite) の両方が同じ message を読み上げ、SR 利用者に同一通知が 2 回 (かつコンテナ側は内包する閉じるボタンの語まで含めて) 届く WCAG 4.1.3 の退行。単一通知チャネル化の回帰防止",
        "file": ROOT / "js" / "ui-components.js",
        "find": "            container.id = 'toast-container';",
        "replace": "            container.id = 'toast-container';\n            container.setAttribute('aria-live', 'polite');",
        "test": "Toast is announced through exactly one live region",
    },
    {
        "name": "behavior: cross-tab が別 schema/欠損 store を raw 採用して crash (#93 class)",
        "file": ROOT / "js" / "state.js",
        "find": "                    if (incoming.schemaVersion !== CONSTANTS.SCHEMA_VERSION) {return;}\n",
        "replace": "",
        "test": "Cross-tab sync ignores a foreign-schema",
    },
    {
        "name": "behavior: quiz 検索が section 見出しを対象外 (#285 class)",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": "                    if (sectionMatch) {return true;}\n",
        "replace": "",
        "test": "section-header",
    },
    {
        "name": "behavior: drawer 再 open の scroll-clobber (#262 class)",
        "file": ROOT / "js" / "mobile-drawer.js",
        "find": "        if (drawer.getAttribute('aria-hidden') === 'false') {return;}\n\n",
        "replace": "",
        "test": "scroll-clobber regression",
    },
    {
        "name": "behavior: 安全網が正常な FatalPage を覆う (silent-failure 限定の喪失)",
        "file": ROOT / "js" / "fatal-overlay.js",
        "find": "\n                    && !document.getElementById('fallback-details')",
        "replace": "",
        "test": "safety net does not cover",
    },
    {
        "name": "behavior: 外部リンク noopener 強制 (tabnabbing 防御) の喪失",
        "file": ROOT / "js" / "mobile-drawer.js",
        "find": "                if (!rel.includes('noopener')) {rel.push('noopener');}\n",
        "replace": "",
        "test": "External target=_blank links are hardened",
    },
    {
        "name": "behavior: AIO/SEO の route 毎 document.title 注入の喪失 (リポジトリ中核 bet)",
        "file": ROOT / "js" / "meta-management.js",
        "find": "        document.title = fullTitle;\n",
        "replace": "",
        "test": "Each route updates document.title",
    },
    {
        "name": "behavior: resilience — corrupt localStorage 耐性 (storage.parse の JSON 例外ガード) の喪失",
        "file": ROOT / "js" / "storage.js",
        "find": "        try {\n            return JSON.parse(data);\n        } catch {\n            return null;\n        }",
        "replace": "        return JSON.parse(data);",
        "test": "App recovers gracefully from corrupt localStorage",
    },
    {
        "name": "behavior: resilience — schema 不一致時の旧データ退避+default リセットの喪失",
        "file": ROOT / "js" / "store.js",
        "find": "if (data.schemaVersion !== CONSTANTS.SCHEMA_VERSION) {",
        "replace": "if (data.schemaVersion === CONSTANTS.SCHEMA_VERSION) {",
        "test": "Store migrates safely on schema version mismatch",
    },
    {
        "name": "behavior: IME composition guard の喪失 (日本語変換確定 Enter の誤 submit・主対象言語)",
        "file": ROOT / "js" / "apps.js",
        "find": "if (e.key === 'Enter' && !e.isComposing) {",
        "replace": "if (e.key === 'Enter') {",
        "test": "Task input ignores Enter during IME composition",
    },
    {
        "name": "behavior: live-input focus-loss guard の喪失 (oninput が全再描画で focus を破棄)",
        "file": ROOT / "js" / "apps.js",
        "find": "State.updateSilently(s => { s.appsData.notes = val.slice(0, CONSTANTS.LIMITS.NOTES_TEXT); });",
        "replace": "State.update(s => { s.appsData.notes = val.slice(0, CONSTANTS.LIMITS.NOTES_TEXT); });",
        "test": "Notes textarea retains focus while typing",
    },
    {
        "name": "behavior: a11y route-focus (WCAG 2.4.3) の喪失 (route 遷移で新ページ h1 へ focus 移らず)",
        "file": ROOT / "main.js",
        "find": "if (isRouteChange && content && _focusWasLost) {",
        "replace": "if (!isRouteChange && content && _focusWasLost) {",
        "test": "Route change moves focus to the new page heading",
    },
    {
        "name": "behavior: resilience — localStorage quota 超過の握り潰し (storage.set try/catch) の喪失",
        "file": ROOT / "js" / "storage.js",
        "find": "        try {\n            // codeql[js/clear-text-storage-of-sensitive-data] - False positive:\n            // Stores portfolio UI state (task list, theme, pomodoro history).\n            // No credentials, tokens, or PII are stored in localStorage.\n            localStorage.setItem(key, value);\n            return true;\n        } catch {\n            return false;\n        }",
        "replace": "        localStorage.setItem(key, value);\n        return true;",
        "test": "Task app degrades gracefully when localStorage write quota",
    },
    {
        "name": "behavior: a11y — mobile drawer focus-trap (WCAG modal) の喪失 (Tab が背景へ漏れる)",
        "file": ROOT / "js" / "mobile-drawer.js",
        "find": "if (e.key !== 'Tab') {return;}",
        "replace": "if (e.key !== 'Tab-DISABLED') {return;}",
        "test": "Mobile drawer traps focus within the dialog",
    },
    {
        "name": "behavior: a11y — command palette focus-trap の喪失 (Tab が背景へ漏れる)",
        "file": ROOT / "js" / "command-palette.js",
        # NOTE (2026-08-10 差し替え): 旧 mutation は JS の forward-wrap
        #   (`activeElement === last` → `first.focus()`) を潰していたが、**それは観測不能**だった。
        #   #947 で palette 開放中は #app が inert になり背景に focusable が 0 個になるため、
        #   **ブラウザ自身が focus を閉じ込める**（実測: palette 内 focusable は input 1 つのみで
        #   Tab を 6 回押しても動かない）。週次 probe が SURVIVED として検出したので、
        #   **実際に閉じ込めている guard = setAppInert** を対象に付け替えた。
        "find": "        if (typeof setAppInert === 'function') { setAppInert(true); }",
        "replace": "        if (false) { setAppInert(true); }",
        "test": "Command palette traps Tab focus inside the modal",
    },
    {
        "name": "behavior: pomodoro complete (#121) — getRemaining の stale-closure 化で timer が永遠に未完了",
        # 2026-07-04 bloat-reduction: PomodoroPage は js/apps.js → js/pomodoro-page.js へ分離した
        # (#558)。find-anchor もそこへ移動したため file を追従させる (抽出で anchor が orphan 化した
        # 実例・mutation-probe --e2e が検出)。
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "            return Math.max(0, Math.ceil((rt.endAtMs - Date.now()) / 1000));",
        "replace": "            return rt.remainingSec;",
        "test": "Pomodoro completes at zero",
    },
    {
        "name": "behavior: snapshot 復元が正規化を通さず生採用して schema 不一致/欠損で crash (#93/#295 class)",
        # 2026-07-05: SettingsPage を js/apps.js → js/settings-page.js へ分離したため anchor file を追従 (#558 class)
        "file": ROOT / "js" / "settings-page.js",
        "find": "            State.set(Store.validateAndNormalize(snap.data));",
        "replace": "            State.set(snap.data);",
        "test": "Snapshot restore normalizes",
    },
    {
        "name": "behavior: TodoPage が ErrorBoundary a11y 属性を leak (role=alert / dangling aria-errormessage)",
        "file": ROOT / "js" / "apps.js",
        "find": "        return h('div', { class: 'flex flex-col gap-4 max-w-2xl' },\n            h('header', { class: 'flex items-center gap-3' },\n                createIcon('list', 28),",
        "replace": "        return h('div', { class: 'flex flex-col gap-4 max-w-2xl error-boundary-fallback', role: 'alert', 'aria-errormessage': 'fallback-details' },\n            h('header', { class: 'flex items-center gap-3' },\n                createIcon('list', 28),",
        "test": "carries no leaked ErrorBoundary",
    },
    {
        "name": "behavior: normalizeAppsData の ai.history Array.isArray ガード喪失 (非配列 .filter で TypeError → 全 ingestion 経路 crash・#93/#295/#561 class)",
        "file": ROOT / "js" / "store.js",
        "find": "        if (Array.isArray(data.ai?.history)) {",
        "replace": "        if (data.ai?.history) {",
        "test": "normalizeAppsData tolerates a non-array",
    },
    {
        "name": "behavior: normalizeProject の tech Array.isArray ガード喪失 (非配列 project field .filter で TypeError → import/ingestion crash・#93/#295/#561/#568 class)",
        "file": ROOT / "js" / "store.js",
        "find": "        return (Array.isArray(v) ? v : [])",
        "replace": "        return (v || [])",
        "test": "normalizeProject tolerates a non-array",
    },
    {
        "name": "behavior: normalizeAppsData の task.tags Array.isArray ガード喪失 (非配列 tags .filter で TypeError → import/ingestion crash・#93/#295/#561/#568/#572 class)",
        "file": ROOT / "js" / "store.js",
        "find": "                    tags: safeStrList(t.tags, 10, CONSTANTS.LIMITS.CATEGORY),",
        "replace": "                    tags: (t.tags || []).filter(Boolean).slice(0, 10),",
        "test": "normalizeAppsData tolerates a non-array",
    },
    {
        "name": "behavior: ProjectDetailPage の !project null-guard 喪失 (非存在 slug で guard が発火せず undefined への property access で crash → 「プロジェクトが見つかりません」未描画)",
        "file": ROOT / "js" / "project-detail-page.js",
        "find": "        if (!project) {",
        "replace": "        if (false) {",
        "test": "ProjectDetailPage shows not-found message and returns to list for nonexistent slug",
    },
    {
        "name": "behavior: ProjectsPage URL deep-link ?q= 復元の喪失 (route.query.q を無視して常に空文字を初期 q にする → 直接到達時に検索状態が復元されず input が空)",
        "file": ROOT / "js" / "projects-page.js",
        "find": "        let q = route.query.q || '';",
        "replace": "        let q = '';",
        "test": "Projects page restores search query from URL deep-link (?q=)",
    },
    {
        "name": "behavior: ProjectsPage URL deep-link ?cat= 復元の喪失 (route.query.cat を無視して常に 'All' を初期 cat にする → 直接到達時にカテゴリフィルタが復元されず select が 'All')",
        "file": ROOT / "js" / "projects-page.js",
        "find": "        let cat = route.query.cat || 'All';",
        "replace": "        let cat = 'All';",
        "test": "Projects page restores category filter from URL deep-link (?cat=)",
    },
    {
        "name": "fix regression: h() textarea value — el.value 設定を el.setAttribute に戻す → reload 後に notes textarea が空 (el.value は IDL property、content attribute 経由では設定不能)",
        "file": ROOT / "js" / "ui-components.js",
        "find": "        } else if (key === 'value' && tag === 'textarea') {",
        "replace": "        } else if (key === 'value' && tag === 'NEVER_MATCH_INTENTIONAL_BREAK') {",
        "test": "Markdown notes app live-previews (innerHTML-free) and persists",
    },
    {
        "name": "fix regression: settings import mode select visual selection — selected 条件を除去すると再描画後に 'append' に戻る (#7cbc4d9 class)",
        "file": ROOT / "js" / "settings-page.js",
        "find": "                                        h('option', { value: 'upsert', selected: settingsImportMode === 'upsert' ? true : undefined }, 'upsert（更新+追加）'),",
        "replace": "                                        h('option', { value: 'upsert' }, 'upsert（更新+追加）'),",
        "test": "Settings import mode select retains visual selection after re-render",
    },
    {
        "name": "fix regression: task priority filter select visual selection — selected 条件を除去すると再描画後に 'all' に戻る (#7cbc4d9 class)",
        "file": ROOT / "js" / "apps.js",
        "find": "                        h('option', { value: 'high', text: 'High', selected: taskFilter.priority === 'high' ? true : undefined }),",
        "replace": "                        h('option', { value: 'high', text: 'High' }),",
        "test": "Task priority filter select retains visual selection after re-render",
    },
    {
        "name": "fix regression: task per-card priority select visual selection — selected 条件を除去すると再描画後に 'high' に戻る (#7cbc4d9 class)",
        "file": ROOT / "js" / "apps.js",
        "find": "                                            h('option', { value: 'low', text: 'Low', selected: task.priority === 'low' ? true : undefined })",
        "replace": "                                            h('option', { value: 'low', text: 'Low' })",
        "test": "Task per-card priority select retains visual selection after re-render",
    },
    {
        "name": "fix regression: todo filter select visual selection — selected 条件を除去すると再描画後に 'all' に戻る (#7cbc4d9 class)",
        "file": ROOT / "js" / "apps.js",
        "find": "                            h('option', { value: 'active', text: '未完了', selected: todoFilter === 'active' ? true : undefined }),",
        "replace": "                            h('option', { value: 'active', text: '未完了' }),",
        "test": "Todo filter select retains visual selection after re-render",
    },
    {
        "name": "behavior: quiz 検索語の reload 跨ぎ復元の喪失 (normalizeAppsData が quizSearch を preserve せず reload で空になる producer/consumer drift・#294/#568 class)",
        "file": ROOT / "js" / "store.js",
        "find": "        if (typeof data.quizSearch === 'string') {\n            result.quizSearch = data.quizSearch.slice(0, CONSTANTS.LIMITS.QUIZ_SEARCH);\n        }",
        "replace": "        // quizSearch preserve removed (mutation)",
        "test": "Quiz search term persists across reload",
    },
    {
        "name": "behavior: pomodoro 休憩時間 live-update の喪失 (short 設定 onchange の remainingSec 即更新を除去 → 休憩モード idle で設定変更しても表示が古いまま・work との非対称)",
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "                                        if (!s.appsData.pomodoro.runtime.isActive && s.appsData.pomodoro.runtime.mode === 'short-break') {\n                                            s.appsData.pomodoro.runtime.remainingSec = s.appsData.pomodoro.settings.short * 60;\n                                        }\n",
        "replace": "",
        "test": "Pomodoro break-duration change updates the idle timer display",
    },
    {
        "name": "behavior: AI keyword routing の breakdown 分岐喪失 (analyzeInput から breakdown keyword を除去 → 「分解して」が general に倒れ専用応答が出ない・#718 で追加した routing の非 vacuity 検証)",
        "file": ROOT / "js" / "ai-page.js",
        "find": "            if (p.includes('分解') || p.includes('タスク') || p.includes('手順') || p.includes('ステップ') || p.includes('段取り')) {return 'breakdown';}",
        "replace": "",
        "test": "AI assist routes prompts to troubleshoot/design/breakdown/writing/general",
    },
    {
        "name": "a11y: contact form の autocomplete=name 喪失 (nameInput から autocomplete 除去 → WCAG 1.3.5 の Identify Input Purpose 退行・#722 で追加した属性の非 vacuity 検証)",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": 'placeholder: "お名前", autocomplete: "name",',
        "replace": 'placeholder: "お名前",',
        "test": "Quiz contact form shows validation error on empty submit",
    },
    {
        "name": "a11y: route アナウンスの over-announce gate 喪失 (isRouteChange ガードを外し無条件 announce に戻す → 同一ページ State.update 再描画で route 名を繰り返しアナウンス・WCAG 4.1.3 退行・#727 で追加した gate の非 vacuity 検証)",
        "file": ROOT / "js" / "meta-management.js",
        "find": "        if (isRouteChange) { announceRouteForAccessibility(title); }",
        "replace": "        announceRouteForAccessibility(title);",
        "test": "Same-page State.update does not re-announce the route",
    },
    {
        "name": "a11y: settings 手動追加フォーム 名前入力の label 関連付け喪失 (input の id を除去 → visible <label for> と結び付かず getByLabel が解決不能・WCAG 3.3.2/4.1.2 退行・#728 で追加した関連付けの非 vacuity 検証)",
        "file": ROOT / "js" / "settings-page.js",
        "find": "h('input', { id: 'settingsNewName', class: 'input'",
        "replace": "h('input', { class: 'input'",
        "test": "accessible names via associated labels",
    },
    {
        "name": "a11y: project-detail 先頭セクション見出しの h2 喪失 (先頭 <h2 課題> を <h3> に戻す → h1(project.name)→h3 の見出しレベルスキップ・WCAG 1.3.1 / axe heading-order 退行・#731 で是正した見出しの非 vacuity 検証。first-only replace は先頭 = 課題 見出しに当たる)",
        "file": ROOT / "js" / "project-detail-page.js",
        # NOTE: この h2 の並びは **3 箇所** (課題 / アプローチ / アーキテクチャ) あり、素の式を
        #   find にすると replace(find, replace, 1) が先頭だけを壊す。壊れる場所を明示するため
        #   直後の createIcon('alert') まで含めて「課題」節に一意 anchor する (Check 420)。
        "find": "h('h2', { class: 'h3 mb-3' }, h('div', { class: 'flex items-center gap-2' },\n                                createIcon('alert', 20),",
        "replace": "h('h3', { class: 'h3 mb-3' }, h('div', { class: 'flex items-center gap-2' },\n                                createIcon('alert', 20),",
        "test": "project detail (#/projects/:slug)",
    },
    {
        "name": "behavior: pomodoro 稼働中モード切替が停止しない (switchMode の isActive=false→true) → 切替後もタイマー稼働表示のまま countdown が続く running-timer-with-wrong-mode 退行 (#747 の非 vacuity 検証。mode=mode 行を含む find で switchMode 限定)",
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "                s.appsData.pomodoro.runtime.mode = mode;\n                s.appsData.pomodoro.runtime.isActive = false;",
        "replace": "                s.appsData.pomodoro.runtime.mode = mode;\n                s.appsData.pomodoro.runtime.isActive = true;",
        "test": "switching mode while running",
    },
    {
        "name": "behavior: notes Markdown ## → h4 の 2 段 demote 喪失 (## を h2 要素へ戻す) → preview 内に note 由来 h2 が現れ heading-order/WCAG 1.3.1 崩れ (#748 の 3 レベル demote 非 vacuity 検証)",
        "file": ROOT / "js" / "apps.js",
        "find": "else if (h2) { flushList(); out.push(h('h4', { class: 'h2' }, ..._renderMarkdownInline(h2[1]))); }",
        "replace": "else if (h2) { flushList(); out.push(h('h2', { class: 'h2' }, ..._renderMarkdownInline(h2[1]))); }",
        "test": "demotes all three heading",
    },
    {
        "name": "behavior: brand sanitize の ALLOWED ガード喪失 (return ALLOWED.has(v)?v:DEFAULT を return v へ) → 不正 brand 値 'garbage-not-json' が data-brand にそのまま残り DEFAULT へ fallback しない (#754 の非 vacuity 検証)",
        "file": ROOT / "js" / "brand.js",
        "find": "        return ALLOWED.has(v) ? v : DEFAULT;",
        "replace": "        return v;",
        "test": "recovers gracefully from corrupt",
    },
    {
        "name": "behavior: theme cycle 三項遷移順の破壊 (system?dark:dark?light:system を system?light:... へ) → cycle が system→dark→light→system の順に一周しない (#755 の完全 cycle 順 非 vacuity 検証)",
        "file": ROOT / "js" / "theme.js",
        "find": "const next = current === 'system' ? 'dark' : current === 'dark' ? 'light' : 'system';",
        "replace": "const next = current === 'system' ? 'light' : current === 'dark' ? 'system' : 'dark';",
        "test": "3-state cycle order",
    },
    {
        "name": "behavior: settings upsert import が更新も新規追加も反映しない data-loss (upsert 分岐の Array.from(map.values()) を base.projects.slice() へ) → import した既存更新 + 新規 project が両方消える (#192 data-loss 実バグ regression の非 vacuity 検証)",
        "file": ROOT / "js" / "settings-page.js",
        "find": "                            merged.projects = Array.from(map.values());",
        "replace": "                            merged.projects = base.projects.slice();",
        "test": "upsert import updates existing",
    },
    {
        "name": "behavior: FatalPage『ホームへ』復旧の window.render() 明示呼び喪失 (home-route の同一 hash では Router.navigate('') が hashchange 不発火のため再描画されず FatalPage から復旧不能に戻る) → home で fatal 発生時『ホームへ』を押しても FatalPage が残る (#269 実バグ regression の非 vacuity 検証)",
        "file": ROOT / "js" / "components.js",
        "find": "if (typeof window.render === 'function') { window.render(); }",
        "replace": "if (typeof window.render === 'function') { /* #269 mutation: render 抑止 */ }",
        "test": "recovers (home-route)",
    },
    {
        "name": "behavior: pomodoro remainingSec=0 の ingestion round-trip fidelity — store.js normalize の 0 保持を `Number(x) || DEFAULT` footgun へ戻す → valid な remainingSec=0 (pause-at-zero / export・snapshot・cross-tab 由来) が DEFAULT(1500=25:00) に化け、リロード後に 00:00 が 25:00 へ silent に破壊される (0 は falsy ゆえ `||` が正当値を捨てる data-fidelity 実バグ regression の非 vacuity 検証)",
        "file": ROOT / "js" / "store.js",
        "find": "remainingSec: clamp(Number.isFinite(rt.remainingSec) ? rt.remainingSec : CONSTANTS.POMODORO_DEFAULT_REMAINING_SEC, 0, 86400),",
        "replace": "remainingSec: clamp(Number(rt.remainingSec) || CONSTANTS.POMODORO_DEFAULT_REMAINING_SEC, 0, 86400),",
        "test": "restores a persisted remainingSec of 0",
    },
    {
        "name": "behavior: task priority の normalize round-trip — store.js normalizeAppsData の priority 保持を `priority: 'med'` ハードコードへ戻す → 非デフォルト priority (high/low) が reload 後に silent に med へ default される (#294/#568/#684 = normalize が reload で field を drop/default する同 class。add-persist は既定 med・visual retention は同一セッションゆえ素通りする穴の非 vacuity 検証)",
        "file": ROOT / "js" / "store.js",
        "find": "priority: ['low', 'med', 'high'].includes(t.priority) ? t.priority : 'med',",
        "replace": "priority: 'med',",
        "test": "priority change persists across reload",
    },
    {
        "name": "behavior: todo completed の normalize round-trip — store.js normalizeAppsData の `completed: Boolean(t.completed)` を `completed: false` へ戻す → 完了 todo が reload 後に全て active へ silent に戻る (#294/#568/#684/#796 = normalize が reload で field を drop/default する同 class。add-persist/filter/disabled/clear は完了状態を reload 跨ぎで検証しないゆえ素通りする穴の非 vacuity 検証)",
        "file": ROOT / "js" / "store.js",
        "find": "completed: Boolean(t.completed),",
        "replace": "completed: false,",
        "test": "completed state persists across reload",
    },
    {
        "name": "behavior: ai.history の normalize round-trip — store.js normalizeAppsData の ai.history 読み戻し guard を skip させる (`if (Array.isArray(data.ai?.history))` を false && で無効化) → 会話履歴が reload 後に silent 消失する (#294/#568/#684/#796/#797 = normalize が reload で field を drop する同 class。生成テストは同一セッション描画のみゆえ素通りする穴の非 vacuity 検証)",
        "file": ROOT / "js" / "store.js",
        "find": "if (Array.isArray(data.ai?.history)) {",
        "replace": "if (false && Array.isArray(data.ai?.history)) {",
        "test": "conversation history persists across reload",
    },
    {
        "name": "behavior: pomodoro settings.work の normalize round-trip — store.js の `work: clamp(Number(...) || DEFAULT.work, 1, 180)` を `work: DEFAULT.work` ハードコードへ戻す → ユーザ設定の非デフォルト集中時間が reload 後に既定 25 へ silent に戻る (#294/#568/#684/#796/#797/#798 = normalize が reload で field を drop/default する同 class。mode/countdown/reset/interval-resume は非デフォルト settings 値の reload を検証しないゆえ素通りする穴の非 vacuity 検証)",
        "file": ROOT / "js" / "store.js",
        "find": "work: clamp(Number(data.pomodoro.settings.work) || CONSTANTS.POMODORO_DEFAULT_SETTINGS.work, 1, 180),",
        "replace": "work: CONSTANTS.POMODORO_DEFAULT_SETTINGS.work,",
        "test": "non-default settings persist across reload",
    },
    {
        "name": "behavior: h() boolean 子 skip の喪失 — ui-components.js の h() children ループから `typeof child === 'boolean'` skip を除去 → `cond && h(...)` が false のとき createTextNode('false') でリテラル 'false' が描画される実バグ (TodoPage の `filtered.length === 0 && h('p',…)` が todo 存在時に false → リスト末尾に可視 'false'。screenshot は advisory ゆえ素通りしていた) の非 vacuity 検証",
        "file": ROOT / "js" / "ui-components.js",
        "find": "if (child === undefined || child === null || typeof child === 'boolean') {return;}",
        "replace": "if (child === undefined || child === null) {return;}",
        "test": "does not render a literal",
    },
    {
        "name": "behavior: MAX_TASKS 件数上限切り詰めの喪失 — store.js normalizeAppsData の tasks `.slice(0, CONSTANTS.LIMITS.MAX_TASKS)` を除去 → import/cross-tab/snapshot 経由の巨大タスク配列が上限 500 で切り詰められず localStorage を bloat させ描画を重くする DoS ガードの喪失。文字列長 bound(#230) は test 済だが件数上限(MAX_TASKS/MAX_TODOS/MAX_PROJECTS)は未被覆だった穴の非 vacuity 検証",
        "file": ROOT / "js" / "store.js",
        "find": "                .slice(0, CONSTANTS.LIMITS.MAX_TASKS);",
        "replace": "                ;",
        "test": "truncates tasks to MAX_TASKS",
    },
    {
        "name": "behavior: MAX_TODOS 件数上限切り詰めの喪失 — store.js normalizeAppsData の todos `.slice(0, CONSTANTS.LIMITS.MAX_TODOS)` を除去 → 巨大 todo 配列が上限 1000 で切り詰められず bloat/描画劣化 DoS を招く。tasks(#801) と別の distinct slice 行ゆえ独立に regress しうる穴の非 vacuity 検証",
        "file": ROOT / "js" / "store.js",
        "find": "                .slice(0, CONSTANTS.LIMITS.MAX_TODOS);",
        "replace": "                ;",
        "test": "truncates todos to MAX_TODOS",
    },
    {
        "name": "behavior: settings import の対象 checkbox 選択的 gate の喪失 — settings-page.js の import が `settingsIncludeProjects && Array.isArray(parsed.projects)` から checkbox ガードを外し常時取り込みへ → Projects を OFF にしても import されユーザが意図的に除外したデータを上書きする (#825 で追加した選択的 gate の非 vacuity 検証。gate 除去で skippedProj が公開一覧に出現し count 0 が RED。テストは keptProject visible を先に待ち grid 描画を確定してから absence 検査する非 vacuous 順序)",
        "file": ROOT / "js" / "settings-page.js",
        "find": "if (settingsIncludeProjects && Array.isArray(parsed.projects)) {",
        "replace": "if (Array.isArray(parsed.projects)) {",
        "test": "selective gate",
    },
]
