#!/usr/bin/env python3
"""mutation_samples_e2e_archive2.py — 旧 (rotated) behavior mutation データ (e2e 版 log-rotation part 2).

`mutation_samples_e2e_archive.py` (part 1) 自体が Check 365 の 1,000 行 cap に達したため新設。
consistency 側が `mutation_samples_archive.py` / `archive2.py` の 2 段構成になっているのと同じ形で、
**archive も無限には伸ばせない**ことへの対処 (2026-08-17)。

rotation の向き: 新規は mutation_samples.py の tail → part 1 → part 2 と古い順に押し出される。
どの段にあっても `E2E_MUTATIONS` へ連結されるので、mutation の総数と有効性は変わらない。

- 公開: E2E_MUTATIONS_ARCHIVE2 (dict の list)。mutation_samples.py が連結する。
- Check 362 (find-anchor 実在) / 379 (test title 解決) / 397 (title 一意) / 420 (find 一意) は
  連結後の全件に対して働くため、archive へ移しても検証は緩まない。
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

E2E_MUTATIONS_ARCHIVE2 = [
    {
        "name": "behavior: task move の done 境界 disabled affordance の喪失 — apps.js の「次のステータスへ進める」ボタン `disabled: task.status === 'done'` を false へ → done 列でも next が有効に見え「これ以上進めない」UX affordance が壊れる (moveStatus の clamp はデータを守るが disabled 属性は別レイヤーの affordance。backlog 境界と対称の done 境界被覆の非 vacuity 検証)",
        "file": ROOT / "js" / "apps.js",
        "find": "disabled: task.status === 'done',",
        "replace": "disabled: false,",
        "test": "disabled at the done boundary",
    },
    {
        "name": "behavior: pomodoro 集中時間 input の範囲外 clamp の喪失 — pomodoro-page.js work onchange の clamp(...,1,180) を外し生 parseInt へ → 999 分等の範囲外値がそのまま settings.work に入り不正 duration の timer になる (number input max=180 は programmatic/paste を防がず JS clamp が実防御。上限/下限境界の非 vacuity 検証)",
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "s.appsData.pomodoro.settings.work = clamp(parseInt(e.target.value, 10) || 25, 1, 180);",
        "replace": "s.appsData.pomodoro.settings.work = parseInt(e.target.value, 10) || 25;",
        "test": "clamps out-of-range values",
    },
    {
        "name": "behavior: pomodoro 短休憩 input の範囲外 clamp[1,60] の喪失 — pomodoro-page.js short onchange の clamp(...,1,60) を外し生 parseInt へ → 999 分等が settings.short に入り work とは別 range の境界が壊れる (#838 work とは独立の range・独立 regress の非 vacuity 検証)",
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "s.appsData.pomodoro.settings.short = clamp(parseInt(e.target.value, 10) || 5, 1, 60);",
        "replace": "s.appsData.pomodoro.settings.short = parseInt(e.target.value, 10) || 5;",
        "test": "short/long break inputs clamp",
    },
    {
        "name": "behavior: pomodoro 長休憩 input の範囲外 clamp[1,120] の喪失 — pomodoro-page.js long onchange の clamp(...,1,120) を外し生 parseInt へ → 999 分等が settings.long に入り short(60) とも別 range の上限 120 境界が壊れる (独立 regress の非 vacuity 検証)",
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "s.appsData.pomodoro.settings.long = clamp(parseInt(e.target.value, 10) || 15, 1, 120);",
        "replace": "s.appsData.pomodoro.settings.long = parseInt(e.target.value, 10) || 15;",
        "test": "short/long break inputs clamp",
    },
    {
        "name": "behavior: AI submit の空/空白プロンプトガードの喪失 — ai-page.js submit の `!input.trim() ||` を外し aiLoading のみ残す → 空文字/空白のみの送信が握り潰されず空の会話を ai.history に積み UI/localStorage を汚す (settings の空入力バリデーションは test 済だが AI 空プロンプトガードは未被覆だった穴の非 vacuity 検証)",
        "file": ROOT / "js" / "ai-page.js",
        "find": "if (!input.trim() || aiLoading) {return;}",
        "replace": "if (aiLoading) {return;}",
        "test": "ignores empty and whitespace",
    },
    {
        "name": "behavior: task addTask の空/空白タイトルガードの喪失 — apps.js addTask の `if (!title.trim())` を常時 false 化 → 空文字/空白のみの Enter が空タイトル task を backlog に積む (AI #841 と同 class の入力バリデーションガード・task 面の非 vacuity 検証)",
        "file": ROOT / "js" / "apps.js",
        "find": "if (!title.trim()) {return;}",
        "replace": "if (false) {return;}",
        "test": "ignore empty/whitespace-only input",
    },
    {
        "name": "behavior: todo addTodo の空/空白テキストガードの喪失 — apps.js addTodo の `if (!text.trim())` を常時 false 化 → 空文字/空白のみの Enter が空テキスト todo を積む (task addTask とは別 function・独立 regress の非 vacuity 検証)",
        "file": ROOT / "js" / "apps.js",
        "find": "if (!text.trim()) {return;}",
        "replace": "if (false) {return;}",
        "test": "ignore empty/whitespace-only input",
    },
    {
        "name": "behavior: snapshot 復元ボタンの未保存時 disabled affordance の喪失 — settings-page.js の 復元ボタン `disabled: !snap` を除去 → snapshot 未保存でも復元ボタンが有効に見え「復元するものが無い」affordance が壊れる (restoreSnapshot は no-op guard 済だが disabled 属性は別レイヤーの UX affordance。#836 task done 境界と同 class・snapshot 面の非 vacuity 検証)",
        "file": ROOT / "js" / "settings-page.js",
        "find": "onclick: restoreSnapshot, disabled: !snap",
        "replace": "onclick: restoreSnapshot",
        "test": "disabled until a snapshot exists",
    },
    {
        "name": "behavior: router の unknown-app whitelist else 分岐の喪失 — router.js の `apps/<app>` で whitelist 外を 'not-found' にする else を 'app-task' へ → 存在しない app サブルート (apps/nonexistent) が task ページを描画し NotFound に落ちない (top-level unknown route とは別 code path の非 vacuity 検証)",
        "file": ROOT / "js" / "router.js",
        "find": ": 'not-found';",
        "replace": ": 'app-task';",
        "test": "Unknown app subroute",
    },
    {
        "name": "behavior: profile github/linkedin の URL スキームサニタイズ (#139 XSS) の喪失 — store.js safeUrl の http(s) スキームチェックを外し raw 値をそのまま返す → import した javascript:/data: 等の危険スキーム URL が ContactPage の href に載り XSS ベクタになる (既存 URL-sanitized test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証)",
        "file": ROOT / "js" / "store.js",
        "find": "return /^https?:\\/\\//i.test(s) ? s.slice(0, 500) : String(fallback || '');",
        "replace": "return s;",
        "test": "URL-sanitized",
    },
    {
        "name": "behavior: pomodoro getDuration の live-state 参照 (#134) の喪失 — pomodoro-page.js getDuration の `State.get()...settings` を render 毎キャプチャの stale closure `pomo.settings` へ戻す → 稼働中に集中時間を変えても complete() の remainingSec リセットが旧設定値を使う (getRemaining #121 と同根の stale-closure バグ。既存 mid-run test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証)",
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "const settings = State.get().appsData.pomodoro.settings;",
        "replace": "const settings = pomo.settings;",
        "test": "completion uses the latest focus-duration",
    },
    {
        "name": "behavior: AI 入力の IME composition ガード (#152) の喪失 — ai-page.js の Enter ハンドラから `&& !e.isComposing` を外す → 日本語入力で IME 変換確定の Enter が未確定テキストを誤 submit する (task IME #299 とは別 function・ai-input 独立の実バグ。日本語が主対象の本サイトで既存 test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証)",
        "file": ROOT / "js" / "ai-page.js",
        "find": "if (e.key === 'Enter' && !e.isComposing) {",
        "replace": "if (e.key === 'Enter') {",
        "test": "AI input ignores Enter during IME composition",
    },
    {
        "name": "behavior: nav-lab collapse 状態の reload 復元喪失 — components.js isLabOpen() の localStorage 読み戻し `=== 'true'` を常時 false 化 → reload 後に Lab 展開状態が失われ collapsed へ戻る (#826 で追加した field-persist reload round-trip の非 vacuity 検証。read-back 喪失で展開→reload→展開維持が RED)",
        "file": ROOT / "js" / "components.js",
        "find": "return localStorage.getItem(labKey) === 'true';",
        "replace": "return false;",
        "test": "Lab nav-group collapse state restores from localStorage across reload",
    },
    {
        "name": "behavior: home 統計カウンタが実データを反映しなくなる — js/home-page.js の TODO カウンタを state.appsData.todos.length から固定値へ置換 → 追加/削除しても数字が動かない silent な描画退行 (Stats は 3 カウンタとも state 由来のデータ駆動面だが e2e 未被覆で、値が固定化しても route 訪問テストは通る)",
        "file": ROOT / "js" / "home-page.js",
        "find": "h('div', { class: 'h2 color-warning' }, String(state.appsData.todos.length)),",
        "replace": "h('div', { class: 'h2 color-warning' }, '1'),",
        "test": "Home stat counters reflect real data",
    },
    {
        "name": "behavior: ResumePage の profile.title 描画喪失 — js/components.js の ResumePage の lead 見出しを State 由来から固定文字列へ置換 → import/設定した title が Resume に反映されなくなる。#/resume は内容レベルの e2e が皆無で route 訪問テストは「fatal なし・content 非空」で通るため、この描画退行は従来どの gate も捕捉できなかった (profile.title は sidebar と Resume の 2 箇所で描画されるデータ駆動値)",
        "file": ROOT / "js" / "components.js",
        "find": "h('h2', { class: 'h3 mb-4', 'data-ai-content': 'lead', lang: langOfText(State.get().profile.title) }, State.get().profile.title),",
        "replace": "h('h2', { class: 'h3 mb-4', 'data-ai-content': 'lead' }, 'Resume'),",
        "test": "Imported profile.title renders on both the sidebar and the Resume page",
    },
    {
        "name": "a11y: task/todo フィルタ変更の SR 通知喪失 — js/apps.js の todo 件数 status から role/aria-live を除去 (#1031 で assertive→polite へ移行済) → フィルタで一覧が変わっても SR には完全に無音 (通知領域には直前のアクション文言が残ったまま・#content 内 live region は 0 個) という実測 gap へ退行する (WCAG 4.1.3 Status Messages)",
        "file": ROOT / "js" / "apps.js",
        "find": "h('div', { class: 'sr-only', role: 'status', 'aria-live': 'polite', id: 'todo-filter-status' },",
        "replace": "h('div', { class: 'sr-only', id: 'todo-filter-status' },",
        "test": "Task and Todo filter changes are announced",
    },
    {
        "name": "a11y: quiz 検索のヒット件数アナウンス喪失 — quiz-renderer.js の resultStatus からヒット時の件数文言を空文字へ戻す → 0 件時だけ喋りヒット時は無言という旧非対称に退行し、SR 利用者は絞り込みが効いたのか結果が何件なのか分からない (WCAG 4.1.3 Status Messages・ProjectsPage は件数を通知しているのに quiz だけ無言だった実 gap の回帰防止)",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": "                    : '「' + query + '」に一致する問題 ' + matchCount + ' 件')",
        "replace": "                    : '')",
        "test": "Quiz search announces the match count",
    },
    {
        "name": "a11y: BGM ボタンの状態同期喪失 — js/ui-components.js の _syncAll から `btn.setAttribute('aria-pressed', String(_on))` を除去 → 再生中でも SR には常に「押されていない」と報告される (aria-pressed が false 固定)。BGM は behavior e2e 完全未カバーで Check 376 も action の解決しか見ないため、この退行はどの gate も通り抜けていた。新設 BGM a11y test の非 vacuity 検証",
        "file": ROOT / "js" / "ui-components.js",
        "find": "            btn.setAttribute('aria-pressed', String(_on));",
        "replace": "",
        "test": "BGM toggle syncs aria-pressed and aria-label",
    },
    {
        "name": "a11y: Toast の二重アナウンス再混入 — js/ui-components.js の toast コンテナへ aria-live を再付与 → 専用 sr-only 領域 #action-announcement (assertive) と視覚コンテナ (polite) の両方が同じ message を読み上げ、SR 利用者に同一通知が 2 回 (かつコンテナ側は内包する閉じるボタンの語まで含めて) 届く WCAG 4.1.3 の退行。単一通知チャネル化の回帰防止",
        "file": ROOT / "js" / "ui-components.js",
        "find": "            container.id = 'toast-container';",
        "replace": "            container.id = 'toast-container';\n            container.setAttribute('aria-live', 'polite');",
        "test": "Toast is announced through exactly one live region",
    },
    {
        "name": "behavior: cross-tab が別 schema/欠損 store を raw 採用して crash (#93 class)",
        "file": ROOT / "js" / "state.js",
        "find": "                    if (incoming.schemaVersion !== CONSTANTS.SCHEMA_VERSION) {return;}\n",
        "replace": "",
        "test": "Cross-tab sync ignores a foreign-schema",
    },
    {
        "name": "behavior: quiz 検索が section 見出しを対象外 (#285 class)",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": "                    if (sectionMatch) {return true;}\n",
        "replace": "",
        "test": "section-header",
    },
    {
        "name": "behavior: drawer 再 open の scroll-clobber (#262 class)",
        "file": ROOT / "js" / "mobile-drawer.js",
        "find": "        if (drawer.getAttribute('aria-hidden') === 'false') {return;}\n\n",
        "replace": "",
        "test": "scroll-clobber regression",
    },
    {
        "name": "behavior: 安全網が正常な FatalPage を覆う (silent-failure 限定の喪失)",
        "file": ROOT / "js" / "fatal-overlay.js",
        "find": "\n                    && !document.getElementById('fallback-details')",
        "replace": "",
        "test": "safety net does not cover",
    },
    {
        "name": "behavior: 外部リンク noopener 強制 (tabnabbing 防御) の喪失",
        "file": ROOT / "js" / "mobile-drawer.js",
        "find": "                if (!rel.includes('noopener')) {rel.push('noopener');}\n",
        "replace": "",
        "test": "External target=_blank links are hardened",
    },
    {
        "name": "behavior: AIO/SEO の route 毎 document.title 注入の喪失 (リポジトリ中核 bet)",
        "file": ROOT / "js" / "meta-management.js",
        "find": "        document.title = fullTitle;\n",
        "replace": "",
        "test": "Each route updates document.title",
    },
    {
        "name": "behavior: resilience — corrupt localStorage 耐性 (storage.parse の JSON 例外ガード) の喪失",
        "file": ROOT / "js" / "storage.js",
        "find": "        try {\n            return JSON.parse(data);\n        } catch {\n            return null;\n        }",
        "replace": "        return JSON.parse(data);",
        "test": "App recovers gracefully from corrupt localStorage",
    },
    {
        "name": "behavior: resilience — schema 不一致時の旧データ退避+default リセットの喪失",
        "file": ROOT / "js" / "store.js",
        "find": "if (data.schemaVersion !== CONSTANTS.SCHEMA_VERSION) {",
        "replace": "if (data.schemaVersion === CONSTANTS.SCHEMA_VERSION) {",
        "test": "Store migrates safely on schema version mismatch",
    },
    {
        "name": "behavior: IME composition guard の喪失 (日本語変換確定 Enter の誤 submit・主対象言語)",
        "file": ROOT / "js" / "apps.js",
        "find": "if (e.key === 'Enter' && !e.isComposing) {",
        "replace": "if (e.key === 'Enter') {",
        "test": "Task input ignores Enter during IME composition",
    },
    {
        "name": "behavior: live-input focus-loss guard の喪失 (oninput が全再描画で focus を破棄)",
        "file": ROOT / "js" / "apps.js",
        "find": "State.updateSilently(s => { s.appsData.notes = val.slice(0, CONSTANTS.LIMITS.NOTES_TEXT); });",
        "replace": "State.update(s => { s.appsData.notes = val.slice(0, CONSTANTS.LIMITS.NOTES_TEXT); });",
        "test": "Notes textarea retains focus while typing",
    },
    {
        "name": "behavior: a11y route-focus (WCAG 2.4.3) の喪失 (route 遷移で新ページ h1 へ focus 移らず)",
        "file": ROOT / "main.js",
        "find": "if (isRouteChange && content && _focusWasLost) {",
        "replace": "if (!isRouteChange && content && _focusWasLost) {",
        "test": "Route change moves focus to the new page heading",
    },
    {
        "name": "behavior: resilience — localStorage quota 超過の握り潰し (storage.set try/catch) の喪失",
        "file": ROOT / "js" / "storage.js",
        "find": "        try {\n            // codeql[js/clear-text-storage-of-sensitive-data] - False positive:\n            // Stores portfolio UI state (task list, theme, pomodoro history).\n            // No credentials, tokens, or PII are stored in localStorage.\n            localStorage.setItem(key, value);\n            return true;\n        } catch {\n            return false;\n        }",
        "replace": "        localStorage.setItem(key, value);\n        return true;",
        "test": "Task app degrades gracefully when localStorage write quota",
    },
    {
        "name": "behavior: a11y — mobile drawer focus-trap (WCAG modal) の喪失 (Tab が背景へ漏れる)",
        "file": ROOT / "js" / "mobile-drawer.js",
        "find": "if (e.key !== 'Tab') {return;}",
        "replace": "if (e.key !== 'Tab-DISABLED') {return;}",
        "test": "Mobile drawer traps focus within the dialog",
    },
    {
        "name": "behavior: a11y — command palette focus-trap の喪失 (Tab が背景へ漏れる)",
        "file": ROOT / "js" / "command-palette.js",
        # NOTE (2026-08-10 差し替え): 旧 mutation は JS の forward-wrap
        #   (`activeElement === last` → `first.focus()`) を潰していたが、**それは観測不能**だった。
        #   #947 で palette 開放中は #app が inert になり背景に focusable が 0 個になるため、
        #   **ブラウザ自身が focus を閉じ込める**（実測: palette 内 focusable は input 1 つのみで
        #   Tab を 6 回押しても動かない）。週次 probe が SURVIVED として検出したので、
        #   **実際に閉じ込めている guard = setAppInert** を対象に付け替えた。
        "find": "        if (typeof setAppInert === 'function') { setAppInert(true); }",
        "replace": "        if (false) { setAppInert(true); }",
        "test": "Command palette traps Tab focus inside the modal",
    },
    {
        "name": "behavior: pomodoro complete (#121) — getRemaining の stale-closure 化で timer が永遠に未完了",
        # 2026-07-04 bloat-reduction: PomodoroPage は js/apps.js → js/pomodoro-page.js へ分離した
        # (#558)。find-anchor もそこへ移動したため file を追従させる (抽出で anchor が orphan 化した
        # 実例・mutation-probe --e2e が検出)。
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "            return Math.max(0, Math.ceil((rt.endAtMs - Date.now()) / 1000));",
        "replace": "            return rt.remainingSec;",
        "test": "Pomodoro completes at zero",
    },
    {
        "name": "behavior: snapshot 復元が正規化を通さず生採用して schema 不一致/欠損で crash (#93/#295 class)",
        # 2026-07-05: SettingsPage を js/apps.js → js/settings-page.js へ分離したため anchor file を追従 (#558 class)
        "file": ROOT / "js" / "settings-page.js",
        "find": "            State.set(Store.validateAndNormalize(snap.data));",
        "replace": "            State.set(snap.data);",
        "test": "Snapshot restore normalizes",
    },
    {
        "name": "behavior: TodoPage が ErrorBoundary a11y 属性を leak (role=alert / dangling aria-errormessage)",
        "file": ROOT / "js" / "apps.js",
        "find": "        return h('div', { class: 'flex flex-col gap-4 max-w-2xl' },\n            h('header', { class: 'flex items-center gap-3' },\n                createIcon('list', 28),",
        "replace": "        return h('div', { class: 'flex flex-col gap-4 max-w-2xl error-boundary-fallback', role: 'alert', 'aria-errormessage': 'fallback-details' },\n            h('header', { class: 'flex items-center gap-3' },\n                createIcon('list', 28),",
        "test": "carries no leaked ErrorBoundary",
    },
    {
        "name": "behavior: normalizeAppsData の ai.history Array.isArray ガード喪失 (非配列 .filter で TypeError → 全 ingestion 経路 crash・#93/#295/#561 class)",
        "file": ROOT / "js" / "store.js",
        "find": "        if (Array.isArray(data.ai?.history)) {",
        "replace": "        if (data.ai?.history) {",
        "test": "normalizeAppsData tolerates a non-array",
    },
    {
        "name": "behavior: normalizeProject の tech Array.isArray ガード喪失 (非配列 project field .filter で TypeError → import/ingestion crash・#93/#295/#561/#568 class)",
        "file": ROOT / "js" / "store.js",
        "find": "        return (Array.isArray(v) ? v : [])",
        "replace": "        return (v || [])",
        "test": "normalizeProject tolerates a non-array",
    },
    {
        "name": "behavior: normalizeAppsData の task.tags Array.isArray ガード喪失 (非配列 tags .filter で TypeError → import/ingestion crash・#93/#295/#561/#568/#572 class)",
        "file": ROOT / "js" / "store.js",
        "find": "                    tags: safeStrList(t.tags, 10, CONSTANTS.LIMITS.CATEGORY),",
        "replace": "                    tags: (t.tags || []).filter(Boolean).slice(0, 10),",
        "test": "normalizeAppsData tolerates a non-array",
    },
    {
        "name": "behavior: ProjectDetailPage の !project null-guard 喪失 (非存在 slug で guard が発火せず undefined への property access で crash → 「プロジェクトが見つかりません」未描画)",
        "file": ROOT / "js" / "project-detail-page.js",
        "find": "        if (!project) {",
        "replace": "        if (false) {",
        "test": "ProjectDetailPage shows not-found message and returns to list for nonexistent slug",
    },
    {
        "name": "behavior: ProjectsPage URL deep-link ?q= 復元の喪失 (route.query.q を無視して常に空文字を初期 q にする → 直接到達時に検索状態が復元されず input が空)",
        "file": ROOT / "js" / "projects-page.js",
        "find": "        let q = route.query.q || '';",
        "replace": "        let q = '';",
        "test": "Projects page restores search query from URL deep-link (?q=)",
    },
    {
        "name": "behavior: ProjectsPage URL deep-link ?cat= 復元の喪失 (route.query.cat を無視して常に 'All' を初期 cat にする → 直接到達時にカテゴリフィルタが復元されず select が 'All')",
        "file": ROOT / "js" / "projects-page.js",
        "find": "        let cat = route.query.cat || 'All';",
        "replace": "        let cat = 'All';",
        "test": "Projects page restores category filter from URL deep-link (?cat=)",
    },
    {
        "name": "fix regression: h() textarea value — el.value 設定を el.setAttribute に戻す → reload 後に notes textarea が空 (el.value は IDL property、content attribute 経由では設定不能)",
        "file": ROOT / "js" / "ui-components.js",
        "find": "        } else if (key === 'value' && tag === 'textarea') {",
        "replace": "        } else if (key === 'value' && tag === 'NEVER_MATCH_INTENTIONAL_BREAK') {",
        "test": "Markdown notes app live-previews (innerHTML-free) and persists",
    },
    {
        "name": "fix regression: settings import mode select visual selection — selected 条件を除去すると再描画後に 'append' に戻る (#7cbc4d9 class)",
        "file": ROOT / "js" / "settings-page.js",
        "find": "                                        h('option', { value: 'upsert', selected: settingsImportMode === 'upsert' ? true : undefined }, 'upsert（更新+追加）'),",
        "replace": "                                        h('option', { value: 'upsert' }, 'upsert（更新+追加）'),",
        "test": "Settings import mode select retains visual selection after re-render",
    },
    {
        "name": "fix regression: task priority filter select visual selection — selected 条件を除去すると再描画後に 'all' に戻る (#7cbc4d9 class)",
        "file": ROOT / "js" / "apps.js",
        "find": "                        h('option', { value: 'high', text: 'High', selected: taskFilter.priority === 'high' ? true : undefined }),",
        "replace": "                        h('option', { value: 'high', text: 'High' }),",
        "test": "Task priority filter select retains visual selection after re-render",
    },
    {
        "name": "fix regression: task per-card priority select visual selection — selected 条件を除去すると再描画後に 'high' に戻る (#7cbc4d9 class)",
        "file": ROOT / "js" / "apps.js",
        "find": "                                            h('option', { value: 'low', text: 'Low', selected: task.priority === 'low' ? true : undefined })",
        "replace": "                                            h('option', { value: 'low', text: 'Low' })",
        "test": "Task per-card priority select retains visual selection after re-render",
    },
    {
        "name": "fix regression: todo filter select visual selection — selected 条件を除去すると再描画後に 'all' に戻る (#7cbc4d9 class)",
        "file": ROOT / "js" / "apps.js",
        "find": "                            h('option', { value: 'active', text: '未完了', selected: todoFilter === 'active' ? true : undefined }),",
        "replace": "                            h('option', { value: 'active', text: '未完了' }),",
        "test": "Todo filter select retains visual selection after re-render",
    },
    {
        "name": "behavior: quiz 検索語の reload 跨ぎ復元の喪失 (normalizeAppsData が quizSearch を preserve せず reload で空になる producer/consumer drift・#294/#568 class)",
        "file": ROOT / "js" / "store.js",
        "find": "        if (typeof data.quizSearch === 'string') {\n            result.quizSearch = data.quizSearch.slice(0, CONSTANTS.LIMITS.QUIZ_SEARCH);\n        }",
        "replace": "        // quizSearch preserve removed (mutation)",
        "test": "Quiz search term persists across reload",
    },
    {
        "name": "behavior: pomodoro 休憩時間 live-update の喪失 (short 設定 onchange の remainingSec 即更新を除去 → 休憩モード idle で設定変更しても表示が古いまま・work との非対称)",
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "                                        if (!s.appsData.pomodoro.runtime.isActive && s.appsData.pomodoro.runtime.mode === 'short-break') {\n                                            s.appsData.pomodoro.runtime.remainingSec = s.appsData.pomodoro.settings.short * 60;\n                                        }\n",
        "replace": "",
        "test": "Pomodoro break-duration change updates the idle timer display",
    },
    {
        "name": "behavior: AI keyword routing の breakdown 分岐喪失 (analyzeInput から breakdown keyword を除去 → 「分解して」が general に倒れ専用応答が出ない・#718 で追加した routing の非 vacuity 検証)",
        "file": ROOT / "js" / "ai-page.js",
        "find": "            if (p.includes('分解') || p.includes('タスク') || p.includes('手順') || p.includes('ステップ') || p.includes('段取り')) {return 'breakdown';}",
        "replace": "",
        "test": "AI assist routes prompts to troubleshoot/design/breakdown/writing/general",
    },
    {
        "name": "a11y: contact form の autocomplete=name 喪失 (nameInput から autocomplete 除去 → WCAG 1.3.5 の Identify Input Purpose 退行・#722 で追加した属性の非 vacuity 検証)",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": 'placeholder: "お名前", autocomplete: "name",',
        "replace": 'placeholder: "お名前",',
        "test": "Quiz contact form shows validation error on empty submit",
    },
    {
        "name": "a11y: route アナウンスの over-announce gate 喪失 (isRouteChange ガードを外し無条件 announce に戻す → 同一ページ State.update 再描画で route 名を繰り返しアナウンス・WCAG 4.1.3 退行・#727 で追加した gate の非 vacuity 検証)",
        "file": ROOT / "js" / "meta-management.js",
        "find": "        if (isRouteChange) { announceRouteForAccessibility(title); }",
        "replace": "        announceRouteForAccessibility(title);",
        "test": "Same-page State.update does not re-announce the route",
    },
    {
        "name": "a11y: settings 手動追加フォーム 名前入力の label 関連付け喪失 (input の id を除去 → visible <label for> と結び付かず getByLabel が解決不能・WCAG 3.3.2/4.1.2 退行・#728 で追加した関連付けの非 vacuity 検証)",
        "file": ROOT / "js" / "settings-page.js",
        "find": "h('input', { id: 'settingsNewName', class: 'input'",
        "replace": "h('input', { class: 'input'",
        "test": "accessible names via associated labels",
    },
    {
        "name": "a11y: project-detail 先頭セクション見出しの h2 喪失 (先頭 <h2 課題> を <h3> に戻す → h1(project.name)→h3 の見出しレベルスキップ・WCAG 1.3.1 / axe heading-order 退行・#731 で是正した見出しの非 vacuity 検証。first-only replace は先頭 = 課題 見出しに当たる)",
        "file": ROOT / "js" / "project-detail-page.js",
        # NOTE: この h2 の並びは **3 箇所** (課題 / アプローチ / アーキテクチャ) あり、素の式を
        #   find にすると replace(find, replace, 1) が先頭だけを壊す。壊れる場所を明示するため
        #   直後の createIcon('alert') まで含めて「課題」節に一意 anchor する (Check 420)。
        "find": "h('h2', { class: 'h3 mb-3' }, h('div', { class: 'flex items-center gap-2' },\n                                createIcon('alert', 20),",
        "replace": "h('h3', { class: 'h3 mb-3' }, h('div', { class: 'flex items-center gap-2' },\n                                createIcon('alert', 20),",
        "test": "project detail (#/projects/:slug)",
    },
    {
        "name": "behavior: pomodoro 稼働中モード切替が停止しない (switchMode の isActive=false→true) → 切替後もタイマー稼働表示のまま countdown が続く running-timer-with-wrong-mode 退行 (#747 の非 vacuity 検証。mode=mode 行を含む find で switchMode 限定)",
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "                s.appsData.pomodoro.runtime.mode = mode;\n                s.appsData.pomodoro.runtime.isActive = false;",
        "replace": "                s.appsData.pomodoro.runtime.mode = mode;\n                s.appsData.pomodoro.runtime.isActive = true;",
        "test": "switching mode while running",
    },
    {
        "name": "behavior: notes Markdown ## → h4 の 2 段 demote 喪失 (## を h2 要素へ戻す) → preview 内に note 由来 h2 が現れ heading-order/WCAG 1.3.1 崩れ (#748 の 3 レベル demote 非 vacuity 検証)",
        "file": ROOT / "js" / "apps.js",
        "find": "else if (h2) { flushList(); out.push(h('h4', { class: 'h2' }, ..._renderMarkdownInline(h2[1]))); }",
        "replace": "else if (h2) { flushList(); out.push(h('h2', { class: 'h2' }, ..._renderMarkdownInline(h2[1]))); }",
        "test": "demotes all three heading",
    },
    {
        "name": "behavior: brand sanitize の ALLOWED ガード喪失 (return ALLOWED.has(v)?v:DEFAULT を return v へ) → 不正 brand 値 'garbage-not-json' が data-brand にそのまま残り DEFAULT へ fallback しない (#754 の非 vacuity 検証)",
        "file": ROOT / "js" / "brand.js",
        "find": "        return ALLOWED.has(v) ? v : DEFAULT;",
        "replace": "        return v;",
        "test": "recovers gracefully from corrupt",
    },
    {
        "name": "behavior: theme cycle 三項遷移順の破壊 (system?dark:dark?light:system を system?light:... へ) → cycle が system→dark→light→system の順に一周しない (#755 の完全 cycle 順 非 vacuity 検証)",
        "file": ROOT / "js" / "theme.js",
        "find": "const next = current === 'system' ? 'dark' : current === 'dark' ? 'light' : 'system';",
        "replace": "const next = current === 'system' ? 'light' : current === 'dark' ? 'system' : 'dark';",
        "test": "3-state cycle order",
    },
    {
        "name": "behavior: settings upsert import が更新も新規追加も反映しない data-loss (upsert 分岐の Array.from(map.values()) を base.projects.slice() へ) → import した既存更新 + 新規 project が両方消える (#192 data-loss 実バグ regression の非 vacuity 検証)",
        "file": ROOT / "js" / "settings-page.js",
        "find": "                            merged.projects = Array.from(map.values());",
        "replace": "                            merged.projects = base.projects.slice();",
        "test": "upsert import updates existing",
    },
    {
        "name": "behavior: FatalPage『ホームへ』復旧の window.render() 明示呼び喪失 (home-route の同一 hash では Router.navigate('') が hashchange 不発火のため再描画されず FatalPage から復旧不能に戻る) → home で fatal 発生時『ホームへ』を押しても FatalPage が残る (#269 実バグ regression の非 vacuity 検証)",
        "file": ROOT / "js" / "components.js",
        "find": "if (typeof window.render === 'function') { window.render(); }",
        "replace": "if (typeof window.render === 'function') { /* #269 mutation: render 抑止 */ }",
        "test": "recovers (home-route)",
    },
    {
        "name": "behavior: pomodoro remainingSec=0 の ingestion round-trip fidelity — store.js normalize の 0 保持を `Number(x) || DEFAULT` footgun へ戻す → valid な remainingSec=0 (pause-at-zero / export・snapshot・cross-tab 由来) が DEFAULT(1500=25:00) に化け、リロード後に 00:00 が 25:00 へ silent に破壊される (0 は falsy ゆえ `||` が正当値を捨てる data-fidelity 実バグ regression の非 vacuity 検証)",
        "file": ROOT / "js" / "store.js",
        "find": "remainingSec: clamp(Number.isFinite(rt.remainingSec) ? rt.remainingSec : CONSTANTS.POMODORO_DEFAULT_REMAINING_SEC, 0, 86400),",
        "replace": "remainingSec: clamp(Number(rt.remainingSec) || CONSTANTS.POMODORO_DEFAULT_REMAINING_SEC, 0, 86400),",
        "test": "restores a persisted remainingSec of 0",
    },
    {
        "name": "behavior: task priority の normalize round-trip — store.js normalizeAppsData の priority 保持を `priority: 'med'` ハードコードへ戻す → 非デフォルト priority (high/low) が reload 後に silent に med へ default される (#294/#568/#684 = normalize が reload で field を drop/default する同 class。add-persist は既定 med・visual retention は同一セッションゆえ素通りする穴の非 vacuity 検証)",
        "file": ROOT / "js" / "store.js",
        "find": "priority: ['low', 'med', 'high'].includes(t.priority) ? t.priority : 'med',",
        "replace": "priority: 'med',",
        "test": "priority change persists across reload",
    },
    {
        "name": "behavior: todo completed の normalize round-trip — store.js normalizeAppsData の `completed: Boolean(t.completed)` を `completed: false` へ戻す → 完了 todo が reload 後に全て active へ silent に戻る (#294/#568/#684/#796 = normalize が reload で field を drop/default する同 class。add-persist/filter/disabled/clear は完了状態を reload 跨ぎで検証しないゆえ素通りする穴の非 vacuity 検証)",
        "file": ROOT / "js" / "store.js",
        "find": "completed: Boolean(t.completed),",
        "replace": "completed: false,",
        "test": "completed state persists across reload",
    },
    {
        "name": "behavior: ai.history の normalize round-trip — store.js normalizeAppsData の ai.history 読み戻し guard を skip させる (`if (Array.isArray(data.ai?.history))` を false && で無効化) → 会話履歴が reload 後に silent 消失する (#294/#568/#684/#796/#797 = normalize が reload で field を drop する同 class。生成テストは同一セッション描画のみゆえ素通りする穴の非 vacuity 検証)",
        "file": ROOT / "js" / "store.js",
        "find": "if (Array.isArray(data.ai?.history)) {",
        "replace": "if (false && Array.isArray(data.ai?.history)) {",
        "test": "conversation history persists across reload",
    },
    {
        "name": "behavior: pomodoro settings.work の normalize round-trip — store.js の `work: clamp(Number(...) || DEFAULT.work, 1, 180)` を `work: DEFAULT.work` ハードコードへ戻す → ユーザ設定の非デフォルト集中時間が reload 後に既定 25 へ silent に戻る (#294/#568/#684/#796/#797/#798 = normalize が reload で field を drop/default する同 class。mode/countdown/reset/interval-resume は非デフォルト settings 値の reload を検証しないゆえ素通りする穴の非 vacuity 検証)",
        "file": ROOT / "js" / "store.js",
        "find": "work: clamp(Number(data.pomodoro.settings.work) || CONSTANTS.POMODORO_DEFAULT_SETTINGS.work, 1, 180),",
        "replace": "work: CONSTANTS.POMODORO_DEFAULT_SETTINGS.work,",
        "test": "non-default settings persist across reload",
    },
    {
        "name": "behavior: h() boolean 子 skip の喪失 — ui-components.js の h() children ループから `typeof child === 'boolean'` skip を除去 → `cond && h(...)` が false のとき createTextNode('false') でリテラル 'false' が描画される実バグ (TodoPage の `filtered.length === 0 && h('p',…)` が todo 存在時に false → リスト末尾に可視 'false'。screenshot は advisory ゆえ素通りしていた) の非 vacuity 検証",
        "file": ROOT / "js" / "ui-components.js",
        "find": "if (child === undefined || child === null || typeof child === 'boolean') {return;}",
        "replace": "if (child === undefined || child === null) {return;}",
        "test": "does not render a literal",
    },
    {
        "name": "behavior: MAX_TASKS 件数上限切り詰めの喪失 — store.js normalizeAppsData の tasks `.slice(0, CONSTANTS.LIMITS.MAX_TASKS)` を除去 → import/cross-tab/snapshot 経由の巨大タスク配列が上限 500 で切り詰められず localStorage を bloat させ描画を重くする DoS ガードの喪失。文字列長 bound(#230) は test 済だが件数上限(MAX_TASKS/MAX_TODOS/MAX_PROJECTS)は未被覆だった穴の非 vacuity 検証",
        "file": ROOT / "js" / "store.js",
        "find": "                .slice(0, CONSTANTS.LIMITS.MAX_TASKS);",
        "replace": "                ;",
        "test": "truncates tasks to MAX_TASKS",
    },
    {
        "name": "behavior: MAX_TODOS 件数上限切り詰めの喪失 — store.js normalizeAppsData の todos `.slice(0, CONSTANTS.LIMITS.MAX_TODOS)` を除去 → 巨大 todo 配列が上限 1000 で切り詰められず bloat/描画劣化 DoS を招く。tasks(#801) と別の distinct slice 行ゆえ独立に regress しうる穴の非 vacuity 検証",
        "file": ROOT / "js" / "store.js",
        "find": "                .slice(0, CONSTANTS.LIMITS.MAX_TODOS);",
        "replace": "                ;",
        "test": "truncates todos to MAX_TODOS",
    },
    {
        "name": "behavior: settings import の対象 checkbox 選択的 gate の喪失 — settings-page.js の import が `settingsIncludeProjects && Array.isArray(parsed.projects)` から checkbox ガードを外し常時取り込みへ → Projects を OFF にしても import されユーザが意図的に除外したデータを上書きする (#825 で追加した選択的 gate の非 vacuity 検証。gate 除去で skippedProj が公開一覧に出現し count 0 が RED。テストは keptProject visible を先に待ち grid 描画を確定してから absence 検査する非 vacuous 順序)",
        "file": ROOT / "js" / "settings-page.js",
        "find": "if (settingsIncludeProjects && Array.isArray(parsed.projects)) {",
        "replace": "if (Array.isArray(parsed.projects)) {",
        "test": "selective gate",
    },
    {
        "name": "behavior: brand セレクタ UI の localStorage 書き込み喪失 — settings-page.js brand <select> の onchange から Brand.set を除去し window.render() のみへ → UI で選んだ brand が localStorage に書かれず reload 後に復元されない (#828 で追加した producer 側 round-trip の非 vacuity 検証。write 喪失で classic 選択→reload→data-brand 復元が RED)",
        "file": ROOT / "js" / "settings-page.js",
        "find": "onchange: (e) => { Brand.set(e.target.value); window.render(); }",
        "replace": "onchange: (e) => { window.render(); }",
        "test": "UI write round-trip",
    },
    {
        "name": "behavior: notes Markdown inline renderer の複数マーカー逐次処理の喪失 — apps.js _renderMarkdownInline の while ループを if 化し 1 個目のマーカーのみ処理 → 同一行の 2 個目以降の **bold**/`code` とマーカー間/末尾の平文が preview から欠落する (#832 後継の markdown edge coverage。既存テストは 1 bold + 1 code のみで複数マーカー行を未検証だった穴の非 vacuity 検証)",
        "file": ROOT / "js" / "apps.js",
        "find": "while ((m = token.exec(rest)) !== null) {",
        "replace": "if ((m = token.exec(rest)) !== null) {",
        "test": "multiple bold/code markers with interleaved text",
    },
    {
        "name": "behavior: テーマ切替が入力途中のテキストを巻き添えにする回帰 — js/theme.js の cycle を updateSilently から State.update へ戻す → notify で全再描画 (#content を clear) が走り、未送信の入力が消える (実測: task 8 文字 → 0 / ai 6 文字 → 0)。テーマはページ内容と無関係な chrome 操作なので巻き添えにしてはならない (#258 / #684 と同じ全再描画回避の規律)",
        "file": ROOT / "js" / "theme.js",
        "find": "        State.updateSilently(s => s.theme = next);",
        "replace": "        State.update(s => s.theme = next);",
        # NOTE: 題名はテンプレートリテラル (`... on ${route}`) で 3 ルート分ループ生成される。
        #   Check 379/397 は静的セグメントを parse するので、**動的部分を含まない前半**を指定する
        #   (3 インスタンス全てが同じコード経路を検証するため、どれが落ちても捕捉として妥当)。
        "test": "Theme toggle does not discard in-flight input on",
    },
    {
        "name": "behavior: 既定プロジェクトの並べ替えが reload で失われる回帰 — mergeProjectsWithDefaults が incoming(保存済み)順の default を採らず、末尾補完だけにする旧実装へ戻す → settings の ↑↓ で既定プロジェクトを並べ替えても reload の normalize round-trip で定義順へ silent に戻る。画面表示順 = state.projects 順なので利用者の操作そのものが失われる。user 追加分は incoming 順で append され保持されるため **default だけが戻る非対称**で気付きにくい",
        "file": ROOT / "js" / "store.js",
        "find": "            merged.push(d ? ({ ...d, ...p, id: d.id }) : p);\n            mergedIds.add(p.id);",
        "replace": "            if (!d) { merged.push(p); mergedIds.add(p.id); }",
        "test": "Default-project reorder survives a reload (normalize round-trip)",
    },
    {
        "name": "behavior: 無効な ?cat= の正規化喪失 — projects-page.js の `cat` 妥当性チェックを外す → stale bookmark / 削除済みカテゴリの deep-link で <select> は option 不在ゆえ 'All' 表示なのにフィルタは無効値のまま = 「全カテゴリーと表示されているのに 0 件」の control↔content desync (#781 と同族)。既存テストは有効カテゴリの選択と URL 同期しか見ておらず未被覆だった",
        "file": ROOT / "js" / "projects-page.js",
        "find": "        if (cat !== 'All' && !categories.includes(cat)) { cat = 'All'; }",
        "replace": "        if (false) { cat = 'All'; }",
        "test": "An unknown ?cat= deep-link normalizes to All (no control-content desync)",
    },
    {
        "name": "behavior: Speakable が宣言するセレクタの実体喪失 — js/pages.js の role-split 表から id を rename → Speakable JSON-LD は `#role-split-table` を宣言し続けるのに要素が存在しなくなり、AI 音声アシスタント向けの機械向け宣言が実態と乖離する (#929 の WebMCP 幻セレクタと同 class)。視覚に一切出ないため screenshot も通常の behavior test も素通りする",
        "file": ROOT / "js" / "pages.js",
        "find": "id: 'role-split-table'",
        "replace": "id: 'role-split-table-RENAMED'",
        # NOTE: 題名はテンプレートリテラルでルート毎に生成される。Check 379/397 は静的セグメントを
        #   parse するので動的部分を含まない前半を指定する (3 インスタンスが走るが、role-split の
        #   1 件が落ちれば suite 全体が FAIL = 捕捉として妥当)。
        "test": "Speakable route selector resolves on",
    },
    {
        "name": "behavior: quiz title の own-key ガード喪失 (#926 の回帰) — page-meta.js の hasOwnProperty 検証を `map[type] ||` へ戻す → `?type=constructor` などプロトタイプ継承キーで **関数オブジェクトが返り** document.title が「function Object() { [native code] }」に化ける。title はタブ名・履歴・AI クローラが受け取る機械可読面で、視覚の主要部には出ないため screenshot でも気付けない",
        "file": ROOT / "js" / "page-meta.js",
        "find": "            return Object.prototype.hasOwnProperty.call(map, type) ? map[type] : 'Quiz';",
        "replace": "            return map[type] || 'Quiz';",
        "test": "Quiz document.title stays in the known-safe set for ?type=",
    },
    {
        "name": "behavior: agentic な描画完了信号の喪失 — main.js の data-ai-state を最終状態も loading:true のままにする → AI エージェントが「永遠に読み込み中」と誤解して待ち続ける。data-ai-state は {route, filter, loading} を公開する機械可読面で、route/filter は既存テストが見ていたが loading のライフサイクルは未被覆だった。視覚に一切出ないため screenshot も通常の behavior test も素通りする",
        "file": ROOT / "main.js",
        "find": "                    loading: false",
        "replace": "                    loading: true",
        "test": "data-ai-state exposes a true->false loading lifecycle per route",
    },
    {
        "name": "behavior: WebMCP の走査セレクタが実描画に解決しなくなる (#929 の再発) — main.js の [data-ai-role] を、リポジトリのどこにも描画されていない .role-split-item へ戻す → ツールは「現在の DOM 状態から抽出します」と謳いながら常に静的フォールバックを返す。WebMCP は実ブラウザに未実装で登録すらされないため、API を shim して execute() を実行する e2e が唯一の捕捉層",
        "file": ROOT / "main.js",
        "find": "document.querySelectorAll('[data-ai-role]')",
        "replace": "document.querySelectorAll('.role-split-item')",
        "test": "WebMCP tool extracts from the live DOM on its route and falls back off-route",
    },
    {
        "name": "behavior: home の in-page ジャンプが reduced-motion を無視する (#993 の回帰) — home-page.js の三項を `behavior: 'smooth'` へ戻す → reduce 環境でも no-preference と同一のアニメーション曲線で 1,000px 超スクロールする。CSS の reduce override は behavior 明示呼び出しには効かない (同じ実測で scrollTo(0,0) は reduce のとき即時＝CSS 側は正常に働いていた) ため、誤って「守られている」と読みやすい",
        "file": ROOT / "js" / "home-page.js",
        "find": "el.scrollIntoView({ behavior: reduce ? 'auto' : 'smooth' });",
        "replace": "el.scrollIntoView({ behavior: 'smooth' });",
        "test": "WCAG 2.3.3: reduced-motion では in-page ジャンプが即時になる",
    },
    {
        "name": "behavior: in-page ジャンプ後に focus が移らなくなる (#993 の回帰) — home-page.js の focus() を潰す → viewport だけが 1,000px 動き、移動先が見えないユーザーには何も起きず、キーボードユーザーの次の Tab は画面外へ去ったボタンから続く (WCAG 2.4.3)",
        "file": ROOT / "js" / "home-page.js",
        "find": "el.focus({ preventScroll: true });",
        "replace": "void 0;",
        "test": "WCAG 2.4.3: in-page ジャンプが移動先へ focus を移す",
    },
    {
        "name": "behavior: 再描画後の focus 復元機構が失われる (#994 の回帰) — main.js _renderCore の復元条件を潰す → change のたびコントロールが自分自身を DOM ごと消して focus が body へ落ちる。number input は ArrowUp の 1 回目で focus を失い 2 回目以降が効かない (値を 1 段しか動かせない = 実質キーボード操作不能)",
        "file": ROOT / "main.js",
        "find": "            if (_restoreFocusId && _focusWasLost) {",
        "replace": "            if (false && _restoreFocusId && _focusWasLost) {",
        "test": "WCAG 2.1.1: ポモドーロの設定を ArrowUp で連続操作できる",
    },
    {
        "name": "behavior: 再描画前の focus 控えが失われる (#994 の回帰・復元の対) — main.js _renderCore が clear の前に控える id を常に null にする → 復元条件は残るが鍵が無くなり、同じく focus が body へ落ちる。Todo の完了チェックは 1 件チェックするたび focus を失い、次の項目を Space で続けてチェックできない",
        "file": ROOT / "main.js",
        "find": "                ? _prevActive.id : null;",
        "replace": "                ? null : null;",
        "test": "WCAG 2.1.1: TODO の完了チェックを Space で連続操作できる",
    },
    {
        "name": "behavior: ポモドーロ開始ボタンの focus 復元 id が外れる (#995 の回帰) — 開始した瞬間に focus が body へ落ち、稼働中は毎秒再描画されるため復帰の機会も無く『開始したらキーボードでは止められない』状態になる",
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "                                id: 'pomo-toggle',\n",
        "replace": "",
        "test": "WCAG 2.1.1: ポモドーロを開始した後もキーボードで一時停止できる",
    },
    {
        "name": "behavior: タスク移動ボタンの focus 復元 id が外れる (#995 の回帰) — ステータスを 1 段動かすたび focus が body へ落ち、backlog→進行中→done と続けて動かせない (毎回ドキュメント先頭から Tab し直しになる)",
        "file": ROOT / "js" / "apps.js",
        "find": "                                                id: 'task-move-next-' + task.id,\n",
        "replace": "",
        "test": "WCAG 2.1.1: タスクをキーボードだけで連続してステータス移動できる",
    },
    {
        "name": "behavior: 復元先が消えた時の #content 退避が失われる (#995 の回帰) — 削除ボタンは自分自身を消すので元の要素へ戻せない。退避が無いと focus は body に残り、続きの Tab がドキュメント先頭からやり直しになる",
        "file": ROOT / "main.js",
        "find": "                if (content && (!_now || _now === document.body || _now === document.documentElement)) {",
        "replace": "                if (false && content && (!_now || _now === document.body || _now === document.documentElement)) {",
        "test": "WCAG 2.1.1: 項目を削除しても focus が本文内に残る",
    },
    {
        "name": "behavior: プロジェクトのタグ絞り込みが focus を捨てる (#995 の回帰) — このボタンは grid 内に居るので renderGrid() が自分自身を消す。_renderCore の復元経路を通らない手動再描画ゆえ、個別の focus 移動が無いと body へ落ちる",
        "file": ROOT / "js" / "projects-page.js",
        "find": "                                            if (inputEl) { inputEl.focus({ preventScroll: true }); }",
        "replace": "                                            void 0;",
        "test": "WCAG 2.1.1: プロジェクトのタグ絞り込みは検索欄へ focus を移す",
    },
    {
        "name": "behavior: サイドバー nav の focus 復元 id が外れる (#997 の回帰) — _renderCore は #content だけでなく sidebar も毎回作り直すため、id が無いと同一ルート再描画のたびに nav の focus が body へ落ちる。ポモドーロ稼働中は毎秒再描画されるので、キーボード利用者はタイマーが動いている間サイドバーに focus を留めておけない",
        "file": ROOT / "js" / "components.js",
        "find": "                id: navId(item),\n",
        "replace": "",
        "test": "WCAG 2.1.1: ポモドーロ稼働中でもサイドバーに focus を留められる",
    },
    {
        "name": "behavior: sidebar と drawer の Lab 本体 id が再び衝突する (#997 の回帰) — drawer を開くと同一 id の要素が 2 つ DOM 上に存在し、sidebar 側トグルの aria-controls が drawer 側を指す (支援技術が視覚的に隠れた別グループへ着地する)。focus 復元も getElementById を鍵にするので復元先が別物になりうる",
        "file": ROOT / "js" / "components.js",
        "find": "        const labBodyId = isDrawer ? 'drawer-nav-lab-body' : 'nav-lab-body';",
        "replace": "        const labBodyId = 'nav-lab-body';",
        "test": "sidebar と drawer の nav が id を衝突させない",
    },
    {
        "name": "behavior: Lab トグルがハードコード id を掴む (#997 の回帰) — 自分の aria-controls を辿らずに getElementById('nav-lab-body') すると、sidebar と drawer が同時に存在する mobile で相手側の本体を開閉する。どちらが動くかが構築順という偶然に委ねられる",
        "file": ROOT / "js" / "components.js",
        "find": "                    const body = document.getElementById(e.currentTarget.getAttribute('aria-controls'));",
        "replace": "                    const body = document.getElementById('nav-lab-body');",
        "test": "drawer の Lab トグルは drawer 側の本体だけを開閉する",
    },
    {
        "name": "behavior: 履歴移動で drawer が開いたまま残る (#998 の回帰) — drawer 内 nav リンク以外の経路でルートが変わると drawer が閉じず、背後のページだけが切り替わって #app は inert / body は scroll lock のまま残る。Android の戻るボタンは『開いているモーダルを閉じる』操作として使われるのに、実際には見えない場所でページが遷移する",
        "file": ROOT / "js" / "mobile-drawer.js",
        "find": "    window.addEventListener('hashchange', () => { closeDrawer(); });",
        "replace": "    void 0;",
        "test": "drawer 開放中にブラウザの戻るでルートが変わったら drawer が閉じる",
    },
    {
        "name": "behavior: 履歴移動で command palette が開いたまま残る (#999 の回帰・#998 の drawer 版と対) — _choose 以外の経路でルートが変わると palette が閉じず、背後のページだけが切り替わって #app は inert のまま残る。両者は同じ『モーダル』なので片方だけ直すと #947 と同じ非対称が残る",
        "file": ROOT / "js" / "command-palette.js",
        "find": "        window.addEventListener('hashchange', () => { close(); });",
        "replace": "        void 0;",
        "test": "palette 開放中にブラウザの戻るでルートが変わったら palette が閉じる",
    },
    {
        "name": "behavior: close() の再入ガードが外れる (#999 の回帰) — hashchange に繋いだ結果、閉じている palette へも close() が走り、末尾の lastFocused.focus() がルート遷移のたびに過去の要素へ focus を引き戻す。生き残る要素 (#menuBtn 等) が lastFocused だと新ページ h1 への route-focus (#267) が毎回打ち消される",
        "file": ROOT / "js" / "command-palette.js",
        "find": "        if (!isOpen()) { return; }\n        // 背景の inert を必ず解除する",
        "replace": "        // 背景の inert を必ず解除する",
        "test": "palette を一度使った後もルート遷移で新ページの見出しへ focus が移る",
    },
    {
        "name": "behavior: Settings 並べ替えボタンの focus 復元 id が外れる (#1000 の回帰) — 1 回押すたびに focus が外れ 2 回目以降が効かない。プロジェクトを何段も動かすのが本来の用途なので、実質キーボードでは使えなくなる",
        "file": ROOT / "js" / "settings-page.js",
        "find": "id: 'settings-move-down-' + p.id, ",
        "replace": "",
        "test": "WCAG 2.1.1: プロジェクトの並べ替えをキーボードで連続実行できる",
    },
    {
        "name": "behavior: 並べ替えの focus 復元鍵を p.id から idx へ戻す (#1000 の回帰) — 移動後にその位置へ来た **別のプロジェクト**のボタンへ focus が移り、続けて押すと違う行が動く (実測では往復して元の順序に戻った)。リスト項目の復元鍵は位置ではなく同一性で作れ",
        "file": ROOT / "js" / "settings-page.js",
        "find": "id: 'settings-move-down-' + p.id,",
        "replace": "id: 'settings-move-down-' + idx,",
        "test": "WCAG 2.1.1: プロジェクトの並べ替えをキーボードで連続実行できる",
    },
    {
        "name": "behavior: Settings 表示切替ボタンの focus 復元 id が外れる (#1000 の回帰) — 切り替えるたびに focus が body へ落ち、元に戻すのに毎回ドキュメント先頭から Tab し直しになる",
        "file": ROOT / "js" / "settings-page.js",
        "find": "id: 'settings-toggle-hidden-' + p.id, ",
        "replace": "",
        "test": "WCAG 2.1.1: 表示切替ボタンは押した後も focus が残る",
    },
    {
        "name": "behavior: 再描画後のキャレット復元が失われる (#1001 の回帰) — focus は id で戻るがキャレットは末尾へ飛ぶため、文章の途中を編集中に外部要因の再描画 (ポモドーロ完了) が起きると次に打った 1 文字が末尾へ着弾する。値もフォーカスも正しいので気付きにくい",
        "file": ROOT / "main.js",
        "find": "                    if (_restoreFocusSel && typeof _again.setSelectionRange === 'function') {",
        "replace": "                    if (false && _restoreFocusSel && typeof _again.setSelectionRange === 'function') {",
        "test": "Markdown ノート編集中の再描画でもキャレットが保たれる",
    },
    {
        "name": "behavior: @media print が丸ごと無効化される — 印刷時にナビ chrome が残り、暗色テーマのまま紙に出る。screenshot は screen media で撮るので到達せず、consistency は CSS の存在しか見ないため、この spec を書くまで捕捉層がゼロだった (#133/#134/#135 と同じ silent-critical class)",
        "file": ROOT / "style.css",
        "find": "        @media print {",
        "replace": "        @media print-disabled {",
        "test": "印刷時はナビ chrome が消え、本文が全幅で横あふれしない",
    },
    {
        "name": "behavior: 印刷時の外部リンク URL 併記が失われる — 紙にはクリックできる要素が無いので、リンク先が本文に出ていないと参照できない。視覚 (screen) には一切出ないため print emulation 以外では観測できない",
        "file": ROOT / "style.css",
        "find": '                content: " (" attr(href) ")";',
        "replace": '                content: "";',
        "test": "印刷時は外部リンクの URL が紙面に併記される",
    },
    {
        "name": "behavior: forced-colors (HCM) のフォーカスリング fallback が失われる — Chromium はブランド色を強制変換して rgba(5, 0, 73, 0.8) = **半透明**の暗い青を描く (実測)。HCM で最も困る『薄くて見えない』状態そのもの。Check 101 はブロックの存在を静的に強制するだけで効果は見ず、screenshot は通常モードで撮るので到達しない",
        "file": ROOT / "style.css",
        "find": "        @media (forced-colors: active) {",
        "replace": "        @media (forced-colors: nope) {",
        "test": "ハイコントラストモードでフォーカスリングが system color になる",
    },
    {
        "name": "behavior: prefers-contrast: more の token 上書きが失われる — 境界線と補助テキストが薄いグレーのまま残り、高コントラストを要求したユーザーに何も返さない。静的にも動的にも無被覆だった面",
        "file": ROOT / "style.css",
        "find": "        @media (prefers-contrast: more) {",
        "replace": "        @media (prefers-contrast: nope) {",
        "test": "高コントラスト設定で境界線と補助テキストが濃くなる",
    },
    {
        "name": "behavior: 詳細ページの not-found ガードが外れる — 開いている詳細ページの project が別画面 (Settings の削除 / 別タブ / import) から消える経路があり、無条件に dereference すると FatalPage になる。#93/#295/#561/#568 で繰り返した ingestion-crash の『参照側』版",
        "file": ROOT / "js" / "project-detail-page.js",
        "find": "        if (!project) {",
        "replace": "        if (false) {",
        "test": "開いている詳細ページのプロジェクトを削除しても FatalPage にならない",
    },
    {
        "name": "behavior: 読み物ページの節タイトルが見出し要素でなくなる (#1011 の回帰) — 4,000 文字・9 セクションの本文に見出しが H1 の 1 個だけになり、スクリーンリーダーの見出しジャンプで一切辿れない。axe は『長い本文に小見出しが無い』をルール化していないので a11y スキャンは緑のまま",
        "file": ROOT / "js" / "ai-knowhow-page.js",
        "find": "                h('h2', { class: 'text-head-lg' }, title)",
        "replace": "                h('span', { class: 'text-head-lg' }, title)",
        "test": "ai-knowhow の節タイトルが実際の見出し要素である",
    },
    {
        "name": "behavior: quiz の章題が見出し要素でなくなる (#1012 の回帰) — 本文 24,500 文字のページに見出しが H1 の 1 個だけになり、スクリーンリーダーの見出しジャンプで 7 章のどこにも飛べない。NOTE: `quiz-section-title` の行は file 内に 2 箇所あり (architecture quiz 用と既存問題集用)、**既定の aws quiz が通るのは後者**。1 行だけの find だと前者に当たって偽 PASS するので、直前の icon 行を含めて一意にしている (Check 420 の要求そのもの)",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": "                    sHeader.appendChild(h(\"div\", { class: \"quiz-section-icon\", 'aria-hidden': 'true' }, \"\U0001F4DD\"));\n                    sHeader.appendChild(h(\"h2\", { class: \"quiz-section-title\" }, section));",
        "replace": "                    sHeader.appendChild(h(\"div\", { class: \"quiz-section-icon\", 'aria-hidden': 'true' }, \"\U0001F4DD\"));\n                    sHeader.appendChild(h(\"div\", { class: \"quiz-section-title\" }, section));",
        "test": "quiz の章題が実際の見出し要素である",
    },
    {
        "name": "behavior: プロジェクト一覧のリスト意味論が失われる (#1013 の回帰) — 18 件の同列カードが SR に「リスト・18 項目」とアナウンスされなくなり、リスト単位のジャンプ操作も効かなくなる。視覚には一切出ないので screenshot でも通常の behavior test でも捕捉できない",
        "file": ROOT / "js" / "projects-page.js",
        "find": "            gridContainer.setAttribute('role', 'list');",
        "replace": "            void 0;",
        "test": "プロジェクト一覧がリストとしてアナウンスされる",
    },
    {
        "name": "behavior: アプリ一覧の listitem が失われる (#1013 の回帰) — role=list の中身が listitem でなくなり、項目数のアナウンスもリスト内移動も壊れる (axe の aria-required-children でも捕捉されうるが、こちらは項目数の一致まで見る)",
        "file": ROOT / "js" / "components.js",
        "find": "h('article', { class: 'card', role: 'listitem' },",
        "replace": "h('article', { class: 'card' },",
        "test": "アプリ一覧がリストとしてアナウンスされる",
    },
    {
        "name": "behavior: ポモドーロ設定ラベルの for 結線が失われる (#1014 の回帰) — ラベル文字をクリック/タップしても入力欄が活性化せず、タップ標的も入力欄だけに縮む。入力欄側に aria-label があるため **axe は緑のまま** (axe は『label 要素が孤立していること』をルール化していない)",
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": ", for: 'pomo-setting-long' }, '長休憩'),",
        "replace": " }, '長休憩'),",
        "test": "ポモドーロはラベル文字のクリックで入力欄が活性化する",
    },
    {
        "name": "behavior: Settings の checkbox グループ名が宙に浮いた label へ戻る (#1014 の回帰) — 「対象」は 3 つの checkbox をまとめるグループ名で、単一 control を指す for は使えない。label のままだとどの control にも結び付かず、グループとしての関連付けも失われる",
        "file": ROOT / "js" / "settings-page.js",
        "find": "h('span', { class: 'text-sm text-muted', id: 'settingsIncludeGroupLabel' }, '対象'),",
        "replace": "h('label', { class: 'text-sm text-muted' }, '対象'),",
        "test": "Settings に宙に浮いた label が無い",
    },
    {
        "name": "behavior: CSP 違反検出ゲートが機能するかの自己検証 (#1016) — index.html に `data:` スクリプトを注入して **本物の CSP 違反**を起こす。旧実装は『メッセージ全体に karte が含まれるか』で除外していたが、CSP 違反メッセージには違反した directive の全文が載り、この CSP は KARTE ホストを許可しているため **あらゆる違反が除外され gate が絶対に落ちない**状態だった。ブロック対象 URL のホスト名で判定する形へ是正済み",
        "file": ROOT / "index.html",
        "find": "</head>",
        "replace": "<script src=\"data:text/javascript,void 0\"></script>\n</head>",
        "test": "No Trusted Types or CSP violations in console",
    },
    {
        "name": "behavior: soft-404 の noindex が外れる — 存在しないルートが index 可能になり、AI/検索クローラが『中身の無いページ』を実在ページとして取り込む。視覚には一切出ないため screenshot でも通常の behavior test でも捕捉できない AIO 面",
        "file": ROOT / "js" / "meta-management.js",
        "find": "            robotsEl.setAttribute('content', 'noindex, nofollow');",
        "replace": "            robotsEl.setAttribute('content', 'index, follow');",
        "test": "Robots meta protects against soft-404",
    },
    {
        "name": "behavior: og:type のルート追従が失われる — article ルートでも og:type が website のまま残り、SNS/クローラが記事として解釈しなくなる。head の meta なので視覚ゲートは一切反応しない",
        "file": ROOT / "js" / "meta-management.js",
        "find": "        document.querySelector('meta[property=\"og:type\"]')?.setAttribute('content', ogType);",
        "replace": "        void ogType;",
        "test": "Article routes inject JSON-LD Article",
    },
    {
        "name": "behavior: ルート entity anchor から曖昧性排除の宣言が消える — 同名の学術研究者等との混同を防ぐ文が失われ、AIO の中核である『エンティティを正しく解釈させる』賭けが弱まる。sr-only なので視覚には出ない",
        "file": ROOT / "js" / "meta-management.js",
        "find": "            ' Not affiliated with any academic researcher.';",
        "replace": "            '';",
        "test": "Route entity anchor declares entity authority",
    },
    {
        "name": "behavior: 英語だけの行への lang=en 付与が失われる (#1020 の回帰) — html lang=ja の文書内で英語が日本語の音韻で読み上げられる (WCAG 3.1.2)。quiz だけで 49 箇所あり、うち 34 回は同じラベル。axe には該当ルールが無く (html-lang-valid は文書全体の lang しか見ない) 視覚にも出ないため、捕捉層は behavior test だけ",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": "                                lang: langOfText(line)",
        "replace": "                                lang: undefined",
        "test": "quiz の英語だけの塊に lang=",
    },
    {
        "name": "behavior: 固定英語文字列の lang=en が外れる (#1021 の回帰) — html lang=ja の文書内で英語キャプションが日本語の音韻で読み上げられる。axe に該当ルールが無く視覚にも出ないため behavior test だけが捕捉層",
        "file": ROOT / "js" / "home-page.js",
        "find": "                                class: 'text-caption', lang: 'en'",
        "replace": "                                class: 'text-caption'",
        "test": "固定の英語文字列に lang=",
    },
    {
        "name": "behavior: data 由来テキストの lang 判定が外れる (#1022 の回帰) — profile.title のような利用者編集データは静的に言語を決められないため描画時に判定している。外れると html lang=ja の文書内で英語が日本語の音韻で読み上げられる (WCAG 3.1.2)",
        "file": ROOT / "js" / "components.js",
        "find": ", lang: langOfText(State.get().profile.title) }",
        "replace": " }",
        "test": "data 由来のテキストにも lang=",
    },
    {
        "name": "behavior: hiring-risk の問題集 CTA の query type が typo る (#1027) — route は存在するので Check 395 は緑のまま、実際には既定の AWS 問題集が silent に表示される (#926 の own-key ガードで crash はせず falls back するだけ)。採用担当が辿る導線で「PM 問題集を見る」が別の問題集を出す",
        "file": ROOT / "js" / "hiring-risk-page.js",
        "find": "path: 'quiz?type=pm',",
        "replace": "path: 'quiz?type=pmm',",
        "test": "hiring-risk の問題集 CTA が宣言どおりの問題集へ着地する",
    },
    {
        "name": "behavior: 絞り込み件数の polite status が失われる (#1031 の回帰) — status role/aria-live を外すと件数変化が SR へ伝わらなくなる。従来は assertive 領域へ書いて読み上げを割り込んでいた非対称を、ProjectsPage/QuizPage と同じ polite なローカル status へ揃えたもの",
        "file": ROOT / "js" / "apps.js",
        "find": "h('div', { class: 'sr-only', role: 'status', 'aria-live': 'polite', id: 'task-filter-status' },",
        "replace": "h('div', { class: 'sr-only', id: 'task-filter-status' },",
        "test": "絞り込みの件数が polite な status でアナウンスされる",
    },
    {
        "name": "behavior: #content が再び live region になる (#1032 の回帰) — ページ本文そのもの (quiz では 24,500 文字) が live region になり、ルート遷移や State 更新のたびにスクリーンリーダーが本文全体を読み直す chatty なアンチパターンへ戻る。ポモドーロ稼働中は毎秒再描画されるため特に害が大きい",
        "file": ROOT / "index.html",
        "find": '<div class="container" id="content" aria-busy="false"></div>',
        "replace": '<div class="container" id="content" aria-busy="false" aria-live="polite"></div>',
        "test": "#content は live region ではなく、通知は専用領域が担う",
    },
    {
        "name": "behavior: full export が 1 フィールド落とす (#1035) — フル export は利用者にとって **バックアップ**なので、export 側で notes が落ちる (あるいは import が無視する) だけで黙ってデータが失われる。部分 export のテストも手書き JSON の import テストもこの経路を通らないため、往復させる test だけが捕捉層",
        "file": ROOT / "js" / "settings-page.js",
        "find": "function exportFull() { downloadJSON(State.get(), ",
        "replace": "function exportFull() { downloadJSON({ ...State.get(), appsData: { ...State.get().appsData, notes: '' } }, ",
        "test": "full export → 全リセット → import で状態が再現する",
    },
    {
        "name": "behavior: import が theme を復元しなくなる (#1036 の回帰) — theme は full export に含まれるのに import が無視すると、フルバックアップを復元しても表示テーマの設定だけが黙って失われる (#139 の profile strip と同じ data-fidelity class)",
        "file": ROOT / "js" / "settings-page.js",
        "find": "                    if (typeof parsed.theme === 'string') { merged.theme = parsed.theme; applied = true; }\n",
        "replace": "",
        "test": "表示テーマが export → import で復元され",
    },
    {
        "name": "behavior: DOM がテーマ state に追随しなくなる (#1036 の回帰) — import / 全リセット / snapshot 復元は Theme.cycle を通らないため、data-theme と .dark が古いまま残り reload するまで切り替わらない",
        "file": ROOT / "main.js",
        "find": "                if (_wantTheme && document.documentElement.getAttribute('data-theme') !== _wantTheme) {",
        "replace": "                if (false && _wantTheme && document.documentElement.getAttribute('data-theme') !== _wantTheme) {",
        "test": "表示テーマが export → import で復元され",
    },
    {
        "name": "behavior: import が projectPrefs を復元しなくなる (#1037 の回帰) — backup を戻すと **意図的に隠したプロジェクトが再び公開状態になる**。既定プロジェクトは削除できず『非表示』が唯一の非公開手段 (#886) なので、単なる表示設定ではなく公開/非公開の意思が失われる",
        "file": ROOT / "js" / "settings-page.js",
        "find": "                        if (parsed.projectPrefs && Array.isArray(parsed.projectPrefs.hiddenIds)) {",
        "replace": "                        if (false && parsed.projectPrefs && Array.isArray(parsed.projectPrefs.hiddenIds)) {",
        "test": "非表示にしたプロジェクトが export → import 後も非表示のまま",
    },
    {
        "name": "behavior: 部分 export した素の配列を import が受け付けなくなる (#1038 の回帰) — `Projectsのみ` は projects の素の配列を書き出すので、full-state 形しか見ないと **何も起きないのに『インポートが完了しました』**と報告する。戻せないファイルを作って成功したと言うのは失敗するより悪い",
        "file": ROOT / "js" / "settings-page.js",
        "find": "            if (Array.isArray(raw)) { return { projects: raw }; }",
        "replace": "            if (false && Array.isArray(raw)) { return { projects: raw }; }",
        "test": "部分 export (Projectsのみ) を import で戻せる",
    },
    {
        "name": "behavior: 認識できない形式を silent no-op として成功報告する (#1038 の回帰) — 形式判定が null を返さなくなると、何も適用されないまま『インポートが完了しました』が出る。利用者は復元できたと信じてしまう",
        "file": ROOT / "js" / "settings-page.js",
        "find": "            if (has('name', 'title', 'bio', 'email', 'github', 'linkedin', 'location')) { return { profile: raw }; }\n            return null;",
        "replace": "            if (has('name', 'title', 'bio', 'email', 'github', 'linkedin', 'location')) { return { profile: raw }; }\n            return raw;",
        "test": "認識できない形式の JSON は成功と report しない",
    },
    {
        "name": "behavior: 対象から全部落ちても成功と報告する (#1040 の回帰) — 形は認識できるのに『対象』チェックボックスの選択で中身が全部落ちる場合、1 セクションも適用していないのに『インポートが完了しました』が出る。#1038 で塞いだ silent-lie の残り半分で、利用者からは同じく『バックアップを戻したのに戻っていない』としか見えない",
        "file": ROOT / "js" / "settings-page.js",
        "find": "                    let applied = false;",
        "replace": "                    let applied = true;",
        "test": "対象から外した形の import を成功と report しない",
    },
    {
        "name": "behavior: AppsDataのみ の形を import が受け付けなくなる (#1040) — `AppsDataのみ` は素の appsData オブジェクトを書き出す。この枝が落ちると素の配列 (Projectsのみ) だけが戻せる非対称になり、apps のバックアップだけが黙って戻らない",
        "file": ROOT / "js" / "settings-page.js",
        "find": "            if (has('tasks', 'todos', 'pomodoro', 'ai', 'notes', 'quizSearch')) { return { appsData: raw }; }",
        "replace": "            if (false && has('tasks', 'todos', 'pomodoro', 'ai', 'notes', 'quizSearch')) { return { appsData: raw }; }",
        "test": "対象から外した形の import を成功と report しない",
    },
    {
        "name": "behavior: 全リセットの confirm ガードが消える — キャンセルしても全データが初期化される。破壊操作の確認は『押し間違い』ではなく『考え直した』を守るためのもので、これが効かないとキャンセルを押した利用者がデータを失う。最悪の silent failure なのに安全網の非 vacuity が未実証だった",
        "file": ROOT / "js" / "settings-page.js",
        "find": "            if (!confirm('すべてのデータを初期化しますか？')) {return;}\n",
        "replace": "",
        "test": "Canceling the reset confirm keeps data (data-safety)",
    },
    {
        "name": "behavior: プロジェクト削除の confirm ガードが消える — キャンセルしても削除される。既定プロジェクトは削除できないため対象はユーザーが自分で追加したものだけで、復元手段は backup しか無い",
        "file": ROOT / "js" / "settings-page.js",
        "find": "            if (!confirm('本当に削除しますか？')) {return;}\n",
        "replace": "",
        "test": "Canceling the delete confirm keeps the project (data-safety)",
    },
    {
        "name": "behavior: MAX_PROJECTS の件数上限が緩む — import/cross-tab/snapshot 経由で巨大な projects 配列が localStorage を bloat させ描画を重くする DoS ガードの喪失。NOTE: 切り詰めは mergeProjectsWithDefaults 内で **二重に適用**されている (normalizedIncoming の slice と最終 merged の slice) ため、**片方の slice を消すだけでは RED にならない** (もう片方が受ける)。意味のある mutation は上限値そのものを緩めること",
        "file": ROOT / "js" / "constants.js",
        "find": "        MAX_PROJECTS: 1000,",
        "replace": "        MAX_PROJECTS: 100000,",
        "test": "Import truncates projects to MAX_PROJECTS (bloat/DoS ingestion guard)",
    },
    {
        "name": "behavior: Markdown ノートの XSS 境界が innerHTML へ退行する — ノート本文はユーザーが自由に書ける唯一の長文入力で、innerHTML で描くと <script>/onerror が実行される。C1 の『ライブラリを入れない』制約を feature 化した innerHTML-free レンダラの中核契約であり、壊れても視覚的にはむしろ『markdown が効いた』ように見えるため気付けない",
        "file": ROOT / "js" / "apps.js",
        "find": "            else { flushList(); out.push(h('p', { class: 'text-prewrap' }, ..._renderMarkdownInline(line))); }",
        "replace": "            else { flushList(); const _p = h('p', { class: 'text-prewrap' }); _p.innerHTML = line; out.push(_p); }",
        "test": "Markdown notes renders HTML/script as literal text (innerHTML-free XSS boundary)",
    },
    {
        "name": "behavior: cross-tab の storage リスナーが発火しなくなる — 複数タブで開いた時に片方の変更がもう片方へ伝わらず、後から保存したタブが相手の変更を上書きする (last-writer-wins が壊れ、利用者からは『さっき足したタスクが消えた』に見える)",
        "file": ROOT / "js" / "state.js",
        "find": "        if (e.key === CONSTANTS.STORAGE_KEY && e.newValue) {",
        "replace": "        if (false && e.key === CONSTANTS.STORAGE_KEY && e.newValue) {",
        "test": "Cross-tab sync: a task added in one tab appears in another tab",
    },
    {
        "name": "behavior: localStorage への保存が no-op になる — reload で全データが消える最大級のデータ喪失。NOTE: 保存経路は debounce (scheduleSave) と visibilitychange (saveNow) の **二重**で、reload は後者も通るため **scheduleSave 側だけを潰しても RED にならない**。意味のある mutation は唯一の choke point である Storage.set の書き込みそのもの",
        "file": ROOT / "js" / "storage.js",
        "find": "            localStorage.setItem(key, value);",
        "replace": "            void key; void value;",
        "test": "Task app adds a task and persists it across reload",
    },
    {
        "name": "behavior: Speakable の cssSelector がルート追従しなくなる — 全ルートで既定セレクタを返すと、AI 音声アシスタントは role-split の表 (#role-split-table) や ai-knowhow の要約ブロックを読み上げ対象として認識できない。視覚に一切出ない AIO 面ゆえ screenshot も behavior の描画検査も素通りする",
        "file": ROOT / "js" / "meta-management.js",
        "find": "        const cssSel = SPEAKABLE_SELECTORS[routeName] || ['h1', '[data-speakable]', '.sr-only'];",
        "replace": "        const cssSel = ['h1', '[data-speakable]', '.sr-only'];",
        "test": "Speakable JSON-LD updates cssSelector per route (AIO voice)",
    },
    {
        "name": "behavior: silent な URL 更新で data-ai-state の route が汚れる — 絞り込みの query が route 名に混ざると、agentic surface を読むエージェントが 'projects?q=...' を route 名だと解釈する (#765 の drift class)。NOTE: main.js 側も data-ai-state を書くため、**通常のルート遷移を見るテストではこの mutation は隠れる**。router 経路だけを通る silent-filter のテストと対にすること",
        "file": ROOT / "js" / "router.js",
        "find": "                route: _r.name || 'home',",
        "replace": "                route: 'projects?q=zzz',",
        "test": "Body data-ai-state keeps a clean route name after a silent projects filter",
    },
    {
        "name": "behavior: theme-init.js の theme 復元が効かなくなる — pre-paint に data-theme/.dark を付けられず、dark 利用者に **一瞬 light が見えてから切り替わる FOUC** が出る。main.js が後から適用するので最終状態は正しく、screenshot は ADVISORY ゆえ **この e2e 以外に捕捉層が無い**",
        "file": ROOT / "theme-init.js",
        "find": "                const rawState = localStorage.getItem('portfolio_enhanced_v45');",
        "replace": "                const rawState = null;",
        "test": "theme-init.js applies stored dark theme on initial load (FOUC prevention)",
    },
    {
        "name": "behavior: theme-init.js の brand 復元が効かなくなる — pre-paint に data-brand を付けられず、既定ブランド色が一瞬見えてから切り替わる FOUC が出る (theme 側と同 class)",
        "file": ROOT / "theme-init.js",
        "find": "                const rawBrand = localStorage.getItem('portfolio_brand_v45');",
        "replace": "                const rawBrand = null;",
        "test": "theme-init.js applies stored brand on initial load (brand FOUC prevention)",
    },
    {
        "name": "behavior: slug 衝突の一意化が効かなくなる (#154 の回帰) — 同名プロジェクトを追加/取り込みすると slug が重複し、**片方の詳細ページへ到達できなくなる** (ルーターは先勝ちで解決するため後の 1 件が事実上消える)。一覧には両方出るので画面上は正常に見える",
        "file": ROOT / "js" / "store.js",
        "find": "            if (_seenSlugs.has(s)) {",
        "replace": "            if (false && _seenSlugs.has(s)) {",
        "test": "Importing projects with colliding slugs yields unique slugs (detail reachability)",
    },
    {
        "name": "behavior: テーマ切替の巡回順が壊れる (#262 の症状面) — 1 クリックで 2 段進む / 逆順になる等。#262 は data-action の delegation と直接リスナーの二重発火が原因だったが、症状は『押した段数と表示が一致しない』で同じ。巡回順そのものを入れ替えて、段数を数える assertion が実際に効くことを実証する",
        "file": ROOT / "js" / "theme.js",
        "find": "        const next = current === 'system' ? 'dark' : current === 'dark' ? 'light' : 'system';",
        "replace": "        const next = current === 'system' ? 'light' : current === 'dark' ? 'system' : 'dark';",
        "test": "Topbar theme button advances exactly one step per click (double-fire regression)",
    },
    {
        "name": "behavior: FatalPage の『ホームへ』が __fatalError を解除しなくなる (#298 の回帰面) — フラグが立ったままだと 2 秒毎に走る Shadow DOM 安全網が **復旧できた正常なページを覆い直す**。利用者は一度は復旧できたのに再びエラー画面へ戻され、脱出手段が無くなる",
        "file": ROOT / "js" / "components.js",
        "find": "                    window.__fatalError = null;",
        "replace": "",
        "test": "FatalPage ホームへ recovers from a non-home route too",
    },
    {
        "name": "behavior: drawer が背景 (#app) を inert にしなくなる (#947 の対) — 開いている drawer の裏のリンクやボタンがキーボード/支援技術から操作でき、aria-modal の主張と実態が食い違う。視覚的には drawer が被さって見えるので目視では気付けない",
        "file": ROOT / "js" / "mobile-drawer.js",
        "find": "        __setAppInert(true);",
        "replace": "",
        "test": "Mobile drawer opens with ARIA, isolates background, and closes on Escape",
    },
]
