#!/usr/bin/env python3
"""mutation_samples.py — Curated mutation DATA for mutation_probe.py (runner is separate).

mutation_probe.py (runner / completeness-critic) から**データのみ**を分離した葉モジュール。
肥大化解消 (自走効率 + 保守性): runner ロジックと curated mutation データを分ける。さらに
データ自体も log-rotation 方式で分割した (1000 行しきい値対応):

- MUTATIONS_ARCHIVE  : mutation_samples_archive.py (最古 / rotated part 1)。
- MUTATIONS_ARCHIVE2 : mutation_samples_archive2.py (次に古い / rotated part 2, 2026-07-28 新設)。
- 本ファイル tail    : 新しい側の entries (新規追記は常に本ファイルの MUTATIONS 末尾へ)。
- MUTATIONS          : ARCHIVE + ARCHIVE2 + tail の連結 (mutation_probe が import する公開 API・不変)。
- E2E_MUTATIONS      : behavior e2e 安全網用 (--e2e モード)。

【追記規約 (生じないように / 恒久)】新規 mutation は本ファイルの MUTATIONS 末尾 (tail) に追記する。
本ファイルが ~900 行を超えたら、最古の tail entries を最新の archive part へ移して rotate する。
part 1/2 が Check 365 の 1,000 cap に近接したら part をさらに増やす (mutation_samples_archive3.py 等)。

各 mutation の意味・非 vacuous 保証・実行機構は mutation_probe.py の docstring を参照。
本ファイルはデータ (dict の list) のみで、副作用も実行ロジックも持たない。
"""
from __future__ import annotations

import sys

if sys.version_info < (3, 10):
    print("ERROR: mutation_samples.py requires Python 3.10+ (got %d.%d)" % sys.version_info[:2])
    sys.exit(1)

from mutation_samples_common import ROOT, CHECK  # noqa: F401 (entry 内で参照)
from mutation_samples_archive import MUTATIONS_ARCHIVE
from mutation_samples_archive2 import MUTATIONS_ARCHIVE2

# 新しい側の curated mutation (新規追記は本リスト末尾へ / 上記「追記規約」参照)。
_MUTATIONS_TAIL = [
    # 注: Check 362 (mutation anchor resolution) の curated meta-mutation は敢えて置かない。
    # anchor を orphan 化する mutation は mutation_samples.py 自身の `"find":` 行を quote する
    # 自己参照になり、mutation_probe の replace(find, replace, 1) が先頭 (= その mutation 自身の
    # find 値) に当たって挙動が不安定になるため。Check 362 の非 vacuous 性は手動で実証済
    # (mutation の file を誤り先へ変えると Check 362 が RED・restore で緑)。
    {
        "name": "Check 400 (monolith module-level parse fail-soft): check_repository_consistency.py の module 直下へ try/except 非保護の `json.loads(read(...))` を注入 → 対象 file が壊れた瞬間に traceback で suite 全体が停止し、その破損を検出するはずの Check 自身を含む全 Check が未実行のまま skip される latent-crash class が再混入する (実測で Check 343 が一度も走らなかった gap)。Check 400 の非 vacuity 検証 (checks_maintainability.py は mutation_samples.py と別 file ゆえ self-reference trap 無し)",
        "file": ROOT / ".github" / "scripts" / "check_repository_consistency.py",
        "find": "# ── ctx enrichment for split modules",
        "replace": "_unguarded400 = json.loads(read(\".well-known/index.json\"))\n# ── ctx enrichment for split modules",
    },
    {
        "name": "Check 408 (e2e spec 予算登録): file-size-budget.md の BUDGET-DATA から e2e/quiz.spec.js の登録行を除去 → 当該 spec は Check 52 の advisory 対象外になり、Check 365 の 1,000 行 BLOCKING に予告なく当たる状態へ戻る (実測で 2 サイクル連続の BLOCKING を招いた早期警告欠落 class)",
        "file": ROOT / "docs" / "architecture" / "file-size-budget.md",
        "find": "e2e/quiz.spec.js | 900 | advisory\n",
        "replace": "",
    },    {
        "name": "Check 366: ContactPage LinkedIn の rel:'noopener noreferrer' から noreferrer を除去 (source drift 再発・静的 source 軸の防止層の回帰)",
        "file": ROOT / "js" / "components.js",
        "find": "                            h('a', { href: profile.linkedin, target: '_blank', rel: 'noopener noreferrer' }, profile.linkedin)",
        "replace": "                            h('a', { href: profile.linkedin, target: '_blank', rel: 'noopener' }, profile.linkedin)",
    },
    {
        "name": "Check 367: projects-page.js の h('select') に value: cat を再注入 → h('select') attrs に value: キーが禁止であることの BLOCKING 検証",
        "file": ROOT / "js" / "projects-page.js",
        "find": "                    h('select', {\n                        class: 'input',\n                        'aria-label': 'カテゴリフィルター',",
        "replace": "                    h('select', {\n                        class: 'input',\n                        value: cat,\n                        'aria-label': 'カテゴリフィルター',",
    },
    {
        "name": "Check 369: store.js の AI 履歴 slice を CONSTANTS.LIMITS.AI_HISTORY からマジック -80 へ戻す → 履歴上限 drift の BLOCKING 検証",
        "file": ROOT / "js" / "store.js",
        "find": ".slice(-CONSTANTS.LIMITS.AI_HISTORY);",
        "replace": ".slice(-80);",
    },
    {
        "name": "Check 370: store.js の pomodoro 既定 settings を CONSTANTS からマジック {work:25...} へ戻す → 既定状態 drift の BLOCKING 検証",
        "file": ROOT / "js" / "store.js",
        "find": "settings: { ...CONSTANTS.POMODORO_DEFAULT_SETTINGS },",
        "replace": "settings: { work: 25, short: 5, long: 15 },",
    },
    {
        "name": "Check 371: state.js.md に volatile 現在行数引用 (**Check 52**: N 行 ≤ M) を再注入 → mirror-doc line-count drift-magnet の BLOCKING 検証",
        "file": ROOT / "docs" / "files" / "js" / "state.js.md",
        "find": "**Check 52**: 行数予算 ≤ 320 行",
        "replace": "**Check 52**: 219 行 ≤ 320",
    },
    {
        "name": "Check 372: quiz-renderer.js.md の factory signature を stale 形へ戻し quiz data 依存 (awsQuizData 等) を落とす → mirror-doc factory-dep drift の BLOCKING 検証",
        "file": ROOT / "docs" / "files" / "js" / "quiz-renderer.js.md",
        "find": "createQuizRenderer({ h, createIcon, Toast, Router, State, awsQuizData, pmQuizData, qualityQuizData, architectureQuizData })",
        "replace": "createQuizRenderer({ h, createIcon, Store, State, quizData: {} })",
    },
    {
        "name": "Check 364: store.js の Array.isArray ガードを unsafe な `(raw.tech || []).filter` idiom へ戻す → ingestion-crash class 構造防止の BLOCKING 検証",
        "file": ROOT / "js" / "store.js",
        "find": "tech: (Array.isArray(raw.tech) ? raw.tech : []).filter(Boolean).slice(0, 12),",
        "replace": "tech: (raw.tech || []).filter(Boolean).slice(0, 12),",
    },
    {
        "name": "Check 368: store.js の notes 上限を CONSTANTS.LIMITS.NOTES_TEXT からマジック 20000 へ戻す → notes 上限 drift の BLOCKING 検証",
        "file": ROOT / "js" / "store.js",
        "find": "result.notes = data.notes.slice(0, CONSTANTS.LIMITS.NOTES_TEXT);",
        "replace": "result.notes = data.notes.slice(0, 20000);",
    },
    {
        "name": "Check 370 (settings fallback magic): store.js の pomodoro settings normalize clamp fallback を CONSTANTS 参照からマジック || 25 へ戻す → runtime remainingSec は定数参照するのに settings fallback だけ magic だった非対称 gap の再発を拡張 Check 370 が捕捉。checks_shipped_hygiene.py は mutation_samples.py と別 file ゆえ self-reference trap 無し",
        "file": ROOT / "js" / "store.js",
        "find": "Number(data.pomodoro.settings.work) || CONSTANTS.POMODORO_DEFAULT_SETTINGS.work",
        "replace": "Number(data.pomodoro.settings.work) || 25",
    },
    {
        "name": "Check 395 (データ駆動 path 記法): hiring-risk の CTA データ配列で nav 先を typo させる (path: 'settings' → 'setting') → router は未知の第1 segment を home として parse するため、ボタンは throw も console error も出さずユーザーを silent にホームへ送る。literal だけを見る旧実装ではこの典型記法が素通りしていた (別記法見逃し class の navigate 面)",
        "file": ROOT / "js" / "hiring-risk-page.js",
        "find": "path: 'settings',",
        "replace": "path: 'setting',",
    },
    {
        "name": "Check 411 (WebMCP セレクタ解決): main.js の WebMCP ツールが走査するセレクタを実在しない属性へ変える → ツールは説明文で「現在の DOM 状態から抽出」と宣言しながら常に静的フォールバックを返す状態に戻る。視覚に出ないため screenshot も behavior e2e も捕捉できない機械可読面の silent drift の回帰防止",
        "file": ROOT / "main.js",
        "find": "document.querySelectorAll('[data-ai-role]');",
        "replace": "document.querySelectorAll('[data-agent-role]');",
    },
    {
        "name": "Check 412 (JSON-LD @id 解決): main.js の動的 JSON-LD が参照する entity ノードを typo させる (#person → #persona) → AI クローラは about の辺を辿れず宙に浮いた参照を得る。視覚に出ないため screenshot も behavior e2e も捕捉しない、機械可読な権威付けの silent な破壊の回帰防止",
        "file": ROOT / "main.js",
        "find": "'about': { '@id': SITE_BASE + '#person' },",
        "replace": "'about': { '@id': SITE_BASE + '#persona' },",
    },
]

# 公開 API: archive(古) + archive2 + tail(新) の連結。mutation_probe.py が import する (順序 = 時系列)。
MUTATIONS = MUTATIONS_ARCHIVE + MUTATIONS_ARCHIVE2 + _MUTATIONS_TAIL

E2E_MUTATIONS = [
    {
        "name": "behavior: nav-lab collapse 状態の reload 復元喪失 — components.js isLabOpen() の localStorage 読み戻し `=== 'true'` を常時 false 化 → reload 後に Lab 展開状態が失われ collapsed へ戻る (#826 で追加した field-persist reload round-trip の非 vacuity 検証。read-back 喪失で展開→reload→展開維持が RED)",
        "file": ROOT / "js" / "components.js",
        "find": "return localStorage.getItem(labKey) === 'true';",
        "replace": "return false;",
        "test": "Lab nav-group collapse state restores from localStorage across reload",
    },
    {
        "name": "behavior: home 統計カウンタが実データを反映しなくなる — js/home-page.js の TODO カウンタを state.appsData.todos.length から固定値へ置換 → 追加/削除しても数字が動かない silent な描画退行 (Stats は 3 カウンタとも state 由来のデータ駆動面だが e2e 未被覆で、値が固定化しても route 訪問テストは通る)",
        "file": ROOT / "js" / "home-page.js",
        "find": "h('div', { class: 'h2 color-warning' }, String(state.appsData.todos.length)),",
        "replace": "h('div', { class: 'h2 color-warning' }, '1'),",
        "test": "Home stat counters reflect real data",
    },
    {
        "name": "behavior: ResumePage の profile.title 描画喪失 — js/components.js の ResumePage の lead 見出しを State 由来から固定文字列へ置換 → import/設定した title が Resume に反映されなくなる。#/resume は内容レベルの e2e が皆無で route 訪問テストは「fatal なし・content 非空」で通るため、この描画退行は従来どの gate も捕捉できなかった (profile.title は sidebar と Resume の 2 箇所で描画されるデータ駆動値)",
        "file": ROOT / "js" / "components.js",
        "find": "h('h2', { class: 'h3 mb-4', 'data-ai-content': 'lead' }, State.get().profile.title),",
        "replace": "h('h2', { class: 'h3 mb-4', 'data-ai-content': 'lead' }, 'Resume'),",
        "test": "Imported profile.title renders on both the sidebar and the Resume page",
    },
    {
        "name": "a11y: task/todo フィルタ変更の SR 通知喪失 — js/apps.js の todo フィルタ onchange から announceFilter 呼び出しを除去 → フィルタで一覧が変わっても SR には完全に無音 (通知領域には直前のアクション文言が残ったまま・#content 内 live region は 0 個) という実測 gap へ退行する (WCAG 4.1.3 Status Messages)",
        "file": ROOT / "js" / "apps.js",
        "find": "                                announceFilter('TODO', e.target.selectedOptions[0]?.text, getFilteredTodos().length);",
        "replace": "",
        "test": "Task and Todo filter changes are announced",
    },
    {
        "name": "a11y: quiz 検索のヒット件数アナウンス喪失 — quiz-renderer.js の resultStatus からヒット時の件数文言を空文字へ戻す → 0 件時だけ喋りヒット時は無言という旧非対称に退行し、SR 利用者は絞り込みが効いたのか結果が何件なのか分からない (WCAG 4.1.3 Status Messages・ProjectsPage は件数を通知しているのに quiz だけ無言だった実 gap の回帰防止)",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": "                    : '「' + query + '」に一致する問題 ' + matchCount + ' 件')",
        "replace": "                    : '')",
        "test": "Quiz search announces the match count",
    },
    {
        "name": "a11y: BGM ボタンの状態同期喪失 — js/ui-components.js の _syncAll から `btn.setAttribute('aria-pressed', String(_on))` を除去 → 再生中でも SR には常に「押されていない」と報告される (aria-pressed が false 固定)。BGM は behavior e2e 完全未カバーで Check 376 も action の解決しか見ないため、この退行はどの gate も通り抜けていた。新設 BGM a11y test の非 vacuity 検証",
        "file": ROOT / "js" / "ui-components.js",
        "find": "            btn.setAttribute('aria-pressed', String(_on));",
        "replace": "",
        "test": "BGM toggle syncs aria-pressed and aria-label",
    },
    {
        "name": "a11y: Toast の二重アナウンス再混入 — js/ui-components.js の toast コンテナへ aria-live を再付与 → 専用 sr-only 領域 #action-announcement (assertive) と視覚コンテナ (polite) の両方が同じ message を読み上げ、SR 利用者に同一通知が 2 回 (かつコンテナ側は内包する閉じるボタンの語まで含めて) 届く WCAG 4.1.3 の退行。単一通知チャネル化の回帰防止",
        "file": ROOT / "js" / "ui-components.js",
        "find": "            container.id = 'toast-container';",
        "replace": "            container.id = 'toast-container';\n            container.setAttribute('aria-live', 'polite');",
        "test": "Toast is announced through exactly one live region",
    },
    {
        "name": "behavior: cross-tab が別 schema/欠損 store を raw 採用して crash (#93 class)",
        "file": ROOT / "js" / "state.js",
        "find": "                    if (incoming.schemaVersion !== CONSTANTS.SCHEMA_VERSION) {return;}\n                    data = Store.validateAndNormalize(incoming);",
        "replace": "                    data = incoming;",
        "test": "Cross-tab sync ignores a foreign-schema",
    },
    {
        "name": "behavior: quiz 検索が section 見出しを対象外 (#285 class)",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": "                    if (sectionMatch) {return true;}\n",
        "replace": "",
        "test": "section-header",
    },
    {
        "name": "behavior: drawer 再 open の scroll-clobber (#262 class)",
        "file": ROOT / "js" / "mobile-drawer.js",
        "find": "        if (drawer.getAttribute('aria-hidden') === 'false') {return;}\n\n",
        "replace": "",
        "test": "scroll-clobber regression",
    },
    {
        "name": "behavior: 安全網が正常な FatalPage を覆う (silent-failure 限定の喪失)",
        "file": ROOT / "js" / "fatal-overlay.js",
        "find": "\n                    && !document.getElementById('fallback-details')",
        "replace": "",
        "test": "safety net does not cover",
    },
    {
        "name": "behavior: 外部リンク noopener 強制 (tabnabbing 防御) の喪失",
        "file": ROOT / "js" / "mobile-drawer.js",
        "find": "                if (!rel.includes('noopener')) {rel.push('noopener');}\n",
        "replace": "",
        "test": "External target=_blank links are hardened",
    },
    {
        "name": "behavior: AIO/SEO の route 毎 document.title 注入の喪失 (リポジトリ中核 bet)",
        "file": ROOT / "js" / "meta-management.js",
        "find": "        document.title = fullTitle;\n",
        "replace": "",
        "test": "Each route updates document.title",
    },
    {
        "name": "behavior: resilience — corrupt localStorage 耐性 (storage.parse の JSON 例外ガード) の喪失",
        "file": ROOT / "js" / "storage.js",
        "find": "        try {\n            return JSON.parse(data);\n        } catch {\n            return null;\n        }",
        "replace": "        return JSON.parse(data);",
        "test": "App recovers gracefully from corrupt localStorage",
    },
    {
        "name": "behavior: resilience — schema 不一致時の旧データ退避+default リセットの喪失",
        "file": ROOT / "js" / "store.js",
        "find": "if (data.schemaVersion !== CONSTANTS.SCHEMA_VERSION) {",
        "replace": "if (data.schemaVersion === CONSTANTS.SCHEMA_VERSION) {",
        "test": "Store migrates safely on schema version mismatch",
    },
    {
        "name": "behavior: IME composition guard の喪失 (日本語変換確定 Enter の誤 submit・主対象言語)",
        "file": ROOT / "js" / "apps.js",
        "find": "if (e.key === 'Enter' && !e.isComposing) {\n                                addTask(e.target.value);",
        "replace": "if (e.key === 'Enter') {\n                                addTask(e.target.value);",
        "test": "Task input ignores Enter during IME composition",
    },
    {
        "name": "behavior: live-input focus-loss guard の喪失 (oninput が全再描画で focus を破棄)",
        "file": ROOT / "js" / "apps.js",
        "find": "State.updateSilently(s => { s.appsData.notes = val.slice(0, CONSTANTS.LIMITS.NOTES_TEXT); });",
        "replace": "State.update(s => { s.appsData.notes = val.slice(0, CONSTANTS.LIMITS.NOTES_TEXT); });",
        "test": "Notes textarea retains focus while typing",
    },
    {
        "name": "behavior: a11y route-focus (WCAG 2.4.3) の喪失 (route 遷移で新ページ h1 へ focus 移らず)",
        "file": ROOT / "main.js",
        "find": "if (isRouteChange && content && _focusWasLost) {",
        "replace": "if (!isRouteChange && content && _focusWasLost) {",
        "test": "Route change moves focus to the new page heading",
    },
    {
        "name": "behavior: resilience — localStorage quota 超過の握り潰し (storage.set try/catch) の喪失",
        "file": ROOT / "js" / "storage.js",
        "find": "        try {\n            // codeql[js/clear-text-storage-of-sensitive-data] - False positive:\n            // Stores portfolio UI state (task list, theme, pomodoro history).\n            // No credentials, tokens, or PII are stored in localStorage.\n            localStorage.setItem(key, value);\n            return true;\n        } catch {\n            return false;\n        }",
        "replace": "        localStorage.setItem(key, value);\n        return true;",
        "test": "Task app degrades gracefully when localStorage write quota",
    },
    {
        "name": "behavior: a11y — mobile drawer focus-trap (WCAG modal) の喪失 (Tab が背景へ漏れる)",
        "file": ROOT / "js" / "mobile-drawer.js",
        "find": "if (e.key !== 'Tab') {return;}",
        "replace": "if (e.key !== 'Tab-DISABLED') {return;}",
        "test": "Mobile drawer traps focus within the dialog",
    },
    {
        "name": "behavior: a11y — command palette focus-trap の喪失 (Tab が背景へ漏れる)",
        "file": ROOT / "js" / "command-palette.js",
        "find": "else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); }",
        "replace": "else if (!e.shiftKey && document.activeElement === last) { /* trap disabled */ }",
        "test": "Command palette traps Tab focus inside the modal",
    },
    {
        "name": "behavior: pomodoro complete (#121) — getRemaining の stale-closure 化で timer が永遠に未完了",
        # 2026-07-04 bloat-reduction: PomodoroPage は js/apps.js → js/pomodoro-page.js へ分離した
        # (#558)。find-anchor もそこへ移動したため file を追従させる (抽出で anchor が orphan 化した
        # 実例・mutation-probe --e2e が検出)。
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "            const rt = State.get().appsData.pomodoro.runtime;\n            if (rt.isActive && rt.endAtMs) {",
        "replace": "            const rt = pomo.runtime;\n            if (rt.isActive && rt.endAtMs) {",
        "test": "Pomodoro completes at zero",
    },
    {
        "name": "behavior: snapshot 復元が正規化を通さず生採用して schema 不一致/欠損で crash (#93/#295 class)",
        # 2026-07-05: SettingsPage を js/apps.js → js/settings-page.js へ分離したため anchor file を追従 (#558 class)
        "file": ROOT / "js" / "settings-page.js",
        "find": "            State.set(Store.validateAndNormalize(snap.data));",
        "replace": "            State.set(snap.data);",
        "test": "Snapshot restore normalizes",
    },
    {
        "name": "behavior: TodoPage が ErrorBoundary a11y 属性を leak (role=alert / dangling aria-errormessage)",
        "file": ROOT / "js" / "apps.js",
        "find": "        return h('div', { class: 'flex flex-col gap-4 max-w-2xl' },\n            h('header', { class: 'flex items-center gap-3' },\n                createIcon('list', 28),",
        "replace": "        return h('div', { class: 'flex flex-col gap-4 max-w-2xl error-boundary-fallback', role: 'alert', 'aria-errormessage': 'fallback-details' },\n            h('header', { class: 'flex items-center gap-3' },\n                createIcon('list', 28),",
        "test": "carries no leaked ErrorBoundary",
    },
    {
        "name": "behavior: normalizeAppsData の ai.history Array.isArray ガード喪失 (非配列 .filter で TypeError → 全 ingestion 経路 crash・#93/#295/#561 class)",
        "file": ROOT / "js" / "store.js",
        "find": "        if (Array.isArray(data.ai?.history)) {",
        "replace": "        if (data.ai?.history) {",
        "test": "normalizeAppsData tolerates a non-array",
    },
    {
        "name": "behavior: normalizeProject の tech Array.isArray ガード喪失 (非配列 project field .filter で TypeError → import/ingestion crash・#93/#295/#561/#568 class)",
        "file": ROOT / "js" / "store.js",
        "find": "            tech: (Array.isArray(raw.tech) ? raw.tech : []).filter(Boolean).slice(0, 12),",
        "replace": "            tech: (raw.tech || []).filter(Boolean).slice(0, 12),",
        "test": "normalizeProject tolerates a non-array",
    },
    {
        "name": "behavior: normalizeAppsData の task.tags Array.isArray ガード喪失 (非配列 tags .filter で TypeError → import/ingestion crash・#93/#295/#561/#568/#572 class)",
        "file": ROOT / "js" / "store.js",
        "find": "                    tags: (Array.isArray(t.tags) ? t.tags : []).filter(Boolean).slice(0, 10),",
        "replace": "                    tags: (t.tags || []).filter(Boolean).slice(0, 10),",
        "test": "normalizeAppsData tolerates a non-array",
    },
    {
        "name": "behavior: ProjectDetailPage の !project null-guard 喪失 (非存在 slug で guard が発火せず undefined への property access で crash → 「プロジェクトが見つかりません」未描画)",
        "file": ROOT / "js" / "project-detail-page.js",
        "find": "        if (!project) {",
        "replace": "        if (false) {",
        "test": "ProjectDetailPage shows not-found message and returns to list for nonexistent slug",
    },
    {
        "name": "behavior: ProjectsPage URL deep-link ?q= 復元の喪失 (route.query.q を無視して常に空文字を初期 q にする → 直接到達時に検索状態が復元されず input が空)",
        "file": ROOT / "js" / "projects-page.js",
        "find": "        let q = route.query.q || '';",
        "replace": "        let q = '';",
        "test": "Projects page restores search query from URL deep-link (?q=)",
    },
    {
        "name": "behavior: ProjectsPage URL deep-link ?cat= 復元の喪失 (route.query.cat を無視して常に 'All' を初期 cat にする → 直接到達時にカテゴリフィルタが復元されず select が 'All')",
        "file": ROOT / "js" / "projects-page.js",
        "find": "        let cat = route.query.cat || 'All';",
        "replace": "        let cat = 'All';",
        "test": "Projects page restores category filter from URL deep-link (?cat=)",
    },
    {
        "name": "fix regression: h() textarea value — el.value 設定を el.setAttribute に戻す → reload 後に notes textarea が空 (el.value は IDL property、content attribute 経由では設定不能)",
        "file": ROOT / "js" / "ui-components.js",
        "find": "        } else if (key === 'value' && tag === 'textarea') {",
        "replace": "        } else if (key === 'value' && tag === 'NEVER_MATCH_INTENTIONAL_BREAK') {",
        "test": "Markdown notes app live-previews (innerHTML-free) and persists",
    },
    {
        "name": "fix regression: settings import mode select visual selection — selected 条件を除去すると再描画後に 'append' に戻る (#7cbc4d9 class)",
        "file": ROOT / "js" / "settings-page.js",
        "find": "                                        h('option', { value: 'upsert', selected: settingsImportMode === 'upsert' ? true : undefined }, 'upsert（更新+追加）'),",
        "replace": "                                        h('option', { value: 'upsert' }, 'upsert（更新+追加）'),",
        "test": "Settings import mode select retains visual selection after re-render",
    },
    {
        "name": "fix regression: task priority filter select visual selection — selected 条件を除去すると再描画後に 'all' に戻る (#7cbc4d9 class)",
        "file": ROOT / "js" / "apps.js",
        "find": "                        h('option', { value: 'high', text: 'High', selected: taskFilter.priority === 'high' ? true : undefined }),",
        "replace": "                        h('option', { value: 'high', text: 'High' }),",
        "test": "Task priority filter select retains visual selection after re-render",
    },
    {
        "name": "fix regression: task per-card priority select visual selection — selected 条件を除去すると再描画後に 'high' に戻る (#7cbc4d9 class)",
        "file": ROOT / "js" / "apps.js",
        "find": "                                            h('option', { value: 'low', text: 'Low', selected: task.priority === 'low' ? true : undefined })",
        "replace": "                                            h('option', { value: 'low', text: 'Low' })",
        "test": "Task per-card priority select retains visual selection after re-render",
    },
    {
        "name": "fix regression: todo filter select visual selection — selected 条件を除去すると再描画後に 'all' に戻る (#7cbc4d9 class)",
        "file": ROOT / "js" / "apps.js",
        "find": "                            h('option', { value: 'active', text: '未完了', selected: todoFilter === 'active' ? true : undefined }),",
        "replace": "                            h('option', { value: 'active', text: '未完了' }),",
        "test": "Todo filter select retains visual selection after re-render",
    },
    {
        "name": "behavior: quiz 検索語の reload 跨ぎ復元の喪失 (normalizeAppsData が quizSearch を preserve せず reload で空になる producer/consumer drift・#294/#568 class)",
        "file": ROOT / "js" / "store.js",
        "find": "        if (typeof data.quizSearch === 'string') {\n            result.quizSearch = data.quizSearch.slice(0, CONSTANTS.LIMITS.QUIZ_SEARCH);\n        }",
        "replace": "        // quizSearch preserve removed (mutation)",
        "test": "Quiz search term persists across reload",
    },
    {
        "name": "behavior: pomodoro 休憩時間 live-update の喪失 (short 設定 onchange の remainingSec 即更新を除去 → 休憩モード idle で設定変更しても表示が古いまま・work との非対称)",
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "                                        if (!s.appsData.pomodoro.runtime.isActive && s.appsData.pomodoro.runtime.mode === 'short-break') {\n                                            s.appsData.pomodoro.runtime.remainingSec = s.appsData.pomodoro.settings.short * 60;\n                                        }\n",
        "replace": "",
        "test": "Pomodoro break-duration change updates the idle timer display",
    },
    {
        "name": "behavior: AI keyword routing の breakdown 分岐喪失 (analyzeInput から breakdown keyword を除去 → 「分解して」が general に倒れ専用応答が出ない・#718 で追加した routing の非 vacuity 検証)",
        "file": ROOT / "js" / "ai-page.js",
        "find": "            if (p.includes('分解') || p.includes('タスク') || p.includes('手順') || p.includes('ステップ') || p.includes('段取り')) {return 'breakdown';}",
        "replace": "",
        "test": "AI assist routes prompts to troubleshoot/design/breakdown/writing/general",
    },
    {
        "name": "a11y: contact form の autocomplete=name 喪失 (nameInput から autocomplete 除去 → WCAG 1.3.5 の Identify Input Purpose 退行・#722 で追加した属性の非 vacuity 検証)",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": 'placeholder: "お名前", autocomplete: "name",',
        "replace": 'placeholder: "お名前",',
        "test": "Quiz contact form shows validation error on empty submit",
    },
    {
        "name": "a11y: route アナウンスの over-announce gate 喪失 (isRouteChange ガードを外し無条件 announce に戻す → 同一ページ State.update 再描画で route 名を繰り返しアナウンス・WCAG 4.1.3 退行・#727 で追加した gate の非 vacuity 検証)",
        "file": ROOT / "js" / "meta-management.js",
        "find": "        if (isRouteChange) { announceRouteForAccessibility(title); }",
        "replace": "        announceRouteForAccessibility(title);",
        "test": "Same-page State.update does not re-announce the route",
    },
    {
        "name": "a11y: settings 手動追加フォーム 名前入力の label 関連付け喪失 (input の id を除去 → visible <label for> と結び付かず getByLabel が解決不能・WCAG 3.3.2/4.1.2 退行・#728 で追加した関連付けの非 vacuity 検証)",
        "file": ROOT / "js" / "settings-page.js",
        "find": "h('input', { id: 'settingsNewName', class: 'input'",
        "replace": "h('input', { class: 'input'",
        "test": "accessible names via associated labels",
    },
    {
        "name": "a11y: project-detail 先頭セクション見出しの h2 喪失 (先頭 <h2 課題> を <h3> に戻す → h1(project.name)→h3 の見出しレベルスキップ・WCAG 1.3.1 / axe heading-order 退行・#731 で是正した見出しの非 vacuity 検証。first-only replace は先頭 = 課題 見出しに当たる)",
        "file": ROOT / "js" / "project-detail-page.js",
        "find": "h('h2', { class: 'h3 mb-3' }, h('div', { class: 'flex items-center gap-2' },",
        "replace": "h('h3', { class: 'h3 mb-3' }, h('div', { class: 'flex items-center gap-2' },",
        "test": "project detail (#/projects/:slug)",
    },
    {
        "name": "behavior: pomodoro 稼働中モード切替が停止しない (switchMode の isActive=false→true) → 切替後もタイマー稼働表示のまま countdown が続く running-timer-with-wrong-mode 退行 (#747 の非 vacuity 検証。mode=mode 行を含む find で switchMode 限定)",
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "                s.appsData.pomodoro.runtime.mode = mode;\n                s.appsData.pomodoro.runtime.isActive = false;",
        "replace": "                s.appsData.pomodoro.runtime.mode = mode;\n                s.appsData.pomodoro.runtime.isActive = true;",
        "test": "switching mode while running",
    },
    {
        "name": "behavior: notes Markdown ## → h4 の 2 段 demote 喪失 (## を h2 要素へ戻す) → preview 内に note 由来 h2 が現れ heading-order/WCAG 1.3.1 崩れ (#748 の 3 レベル demote 非 vacuity 検証)",
        "file": ROOT / "js" / "apps.js",
        "find": "else if (h2) { flushList(); out.push(h('h4', { class: 'h2' }, ..._renderMarkdownInline(h2[1]))); }",
        "replace": "else if (h2) { flushList(); out.push(h('h2', { class: 'h2' }, ..._renderMarkdownInline(h2[1]))); }",
        "test": "demotes all three heading",
    },
    {
        "name": "behavior: brand sanitize の ALLOWED ガード喪失 (return ALLOWED.has(v)?v:DEFAULT を return v へ) → 不正 brand 値 'garbage-not-json' が data-brand にそのまま残り DEFAULT へ fallback しない (#754 の非 vacuity 検証)",
        "file": ROOT / "js" / "brand.js",
        "find": "        return ALLOWED.has(v) ? v : DEFAULT;",
        "replace": "        return v;",
        "test": "recovers gracefully from corrupt",
    },
    {
        "name": "behavior: theme cycle 三項遷移順の破壊 (system?dark:dark?light:system を system?light:... へ) → cycle が system→dark→light→system の順に一周しない (#755 の完全 cycle 順 非 vacuity 検証)",
        "file": ROOT / "js" / "theme.js",
        "find": "const next = current === 'system' ? 'dark' : current === 'dark' ? 'light' : 'system';",
        "replace": "const next = current === 'system' ? 'light' : current === 'dark' ? 'system' : 'dark';",
        "test": "3-state cycle order",
    },
    {
        "name": "behavior: settings upsert import が更新も新規追加も反映しない data-loss (upsert 分岐の Array.from(map.values()) を base.projects.slice() へ) → import した既存更新 + 新規 project が両方消える (#192 data-loss 実バグ regression の非 vacuity 検証)",
        "file": ROOT / "js" / "settings-page.js",
        "find": "                            merged.projects = Array.from(map.values());",
        "replace": "                            merged.projects = base.projects.slice();",
        "test": "upsert import updates existing",
    },
    {
        "name": "behavior: FatalPage『ホームへ』復旧の window.render() 明示呼び喪失 (home-route の同一 hash では Router.navigate('') が hashchange 不発火のため再描画されず FatalPage から復旧不能に戻る) → home で fatal 発生時『ホームへ』を押しても FatalPage が残る (#269 実バグ regression の非 vacuity 検証)",
        "file": ROOT / "js" / "components.js",
        "find": "if (typeof window.render === 'function') { window.render(); }",
        "replace": "if (typeof window.render === 'function') { /* #269 mutation: render 抑止 */ }",
        "test": "recovers (home-route)",
    },
    {
        "name": "behavior: pomodoro remainingSec=0 の ingestion round-trip fidelity — store.js normalize の 0 保持を `Number(x) || DEFAULT` footgun へ戻す → valid な remainingSec=0 (pause-at-zero / export・snapshot・cross-tab 由来) が DEFAULT(1500=25:00) に化け、リロード後に 00:00 が 25:00 へ silent に破壊される (0 は falsy ゆえ `||` が正当値を捨てる data-fidelity 実バグ regression の非 vacuity 検証)",
        "file": ROOT / "js" / "store.js",
        "find": "remainingSec: clamp(Number.isFinite(rt.remainingSec) ? rt.remainingSec : CONSTANTS.POMODORO_DEFAULT_REMAINING_SEC, 0, 86400),",
        "replace": "remainingSec: clamp(Number(rt.remainingSec) || CONSTANTS.POMODORO_DEFAULT_REMAINING_SEC, 0, 86400),",
        "test": "restores a persisted remainingSec of 0",
    },
    {
        "name": "behavior: task priority の normalize round-trip — store.js normalizeAppsData の priority 保持を `priority: 'med'` ハードコードへ戻す → 非デフォルト priority (high/low) が reload 後に silent に med へ default される (#294/#568/#684 = normalize が reload で field を drop/default する同 class。add-persist は既定 med・visual retention は同一セッションゆえ素通りする穴の非 vacuity 検証)",
        "file": ROOT / "js" / "store.js",
        "find": "priority: ['low', 'med', 'high'].includes(t.priority) ? t.priority : 'med',",
        "replace": "priority: 'med',",
        "test": "priority change persists across reload",
    },
    {
        "name": "behavior: todo completed の normalize round-trip — store.js normalizeAppsData の `completed: Boolean(t.completed)` を `completed: false` へ戻す → 完了 todo が reload 後に全て active へ silent に戻る (#294/#568/#684/#796 = normalize が reload で field を drop/default する同 class。add-persist/filter/disabled/clear は完了状態を reload 跨ぎで検証しないゆえ素通りする穴の非 vacuity 検証)",
        "file": ROOT / "js" / "store.js",
        "find": "completed: Boolean(t.completed),",
        "replace": "completed: false,",
        "test": "completed state persists across reload",
    },
    {
        "name": "behavior: ai.history の normalize round-trip — store.js normalizeAppsData の ai.history 読み戻し guard を skip させる (`if (Array.isArray(data.ai?.history))` を false && で無効化) → 会話履歴が reload 後に silent 消失する (#294/#568/#684/#796/#797 = normalize が reload で field を drop する同 class。生成テストは同一セッション描画のみゆえ素通りする穴の非 vacuity 検証)",
        "file": ROOT / "js" / "store.js",
        "find": "if (Array.isArray(data.ai?.history)) {",
        "replace": "if (false && Array.isArray(data.ai?.history)) {",
        "test": "conversation history persists across reload",
    },
    {
        "name": "behavior: pomodoro settings.work の normalize round-trip — store.js の `work: clamp(Number(...) || DEFAULT.work, 1, 180)` を `work: DEFAULT.work` ハードコードへ戻す → ユーザ設定の非デフォルト集中時間が reload 後に既定 25 へ silent に戻る (#294/#568/#684/#796/#797/#798 = normalize が reload で field を drop/default する同 class。mode/countdown/reset/interval-resume は非デフォルト settings 値の reload を検証しないゆえ素通りする穴の非 vacuity 検証)",
        "file": ROOT / "js" / "store.js",
        "find": "work: clamp(Number(data.pomodoro.settings.work) || CONSTANTS.POMODORO_DEFAULT_SETTINGS.work, 1, 180),",
        "replace": "work: CONSTANTS.POMODORO_DEFAULT_SETTINGS.work,",
        "test": "non-default settings persist across reload",
    },
    {
        "name": "behavior: h() boolean 子 skip の喪失 — ui-components.js の h() children ループから `typeof child === 'boolean'` skip を除去 → `cond && h(...)` が false のとき createTextNode('false') でリテラル 'false' が描画される実バグ (TodoPage の `filtered.length === 0 && h('p',…)` が todo 存在時に false → リスト末尾に可視 'false'。screenshot は advisory ゆえ素通りしていた) の非 vacuity 検証",
        "file": ROOT / "js" / "ui-components.js",
        "find": "if (child === undefined || child === null || typeof child === 'boolean') {return;}",
        "replace": "if (child === undefined || child === null) {return;}",
        "test": "does not render a literal",
    },
    {
        "name": "behavior: MAX_TASKS 件数上限切り詰めの喪失 — store.js normalizeAppsData の tasks `.slice(0, CONSTANTS.LIMITS.MAX_TASKS)` を除去 → import/cross-tab/snapshot 経由の巨大タスク配列が上限 500 で切り詰められず localStorage を bloat させ描画を重くする DoS ガードの喪失。文字列長 bound(#230) は test 済だが件数上限(MAX_TASKS/MAX_TODOS/MAX_PROJECTS)は未被覆だった穴の非 vacuity 検証",
        "file": ROOT / "js" / "store.js",
        "find": "                .slice(0, CONSTANTS.LIMITS.MAX_TASKS);",
        "replace": "                ;",
        "test": "truncates tasks to MAX_TASKS",
    },
    {
        "name": "behavior: MAX_TODOS 件数上限切り詰めの喪失 — store.js normalizeAppsData の todos `.slice(0, CONSTANTS.LIMITS.MAX_TODOS)` を除去 → 巨大 todo 配列が上限 1000 で切り詰められず bloat/描画劣化 DoS を招く。tasks(#801) と別の distinct slice 行ゆえ独立に regress しうる穴の非 vacuity 検証",
        "file": ROOT / "js" / "store.js",
        "find": "                .slice(0, CONSTANTS.LIMITS.MAX_TODOS);",
        "replace": "                ;",
        "test": "truncates todos to MAX_TODOS",
    },
    {
        "name": "behavior: settings import の対象 checkbox 選択的 gate の喪失 — settings-page.js の import が `settingsIncludeProjects && Array.isArray(parsed.projects)` から checkbox ガードを外し常時取り込みへ → Projects を OFF にしても import されユーザが意図的に除外したデータを上書きする (#825 で追加した選択的 gate の非 vacuity 検証。gate 除去で skippedProj が公開一覧に出現し count 0 が RED。テストは keptProject visible を先に待ち grid 描画を確定してから absence 検査する非 vacuous 順序)",
        "file": ROOT / "js" / "settings-page.js",
        "find": "if (settingsIncludeProjects && Array.isArray(parsed.projects)) {",
        "replace": "if (Array.isArray(parsed.projects)) {",
        "test": "selective gate",
    },
    {
        "name": "behavior: brand セレクタ UI の localStorage 書き込み喪失 — settings-page.js brand <select> の onchange から Brand.set を除去し window.render() のみへ → UI で選んだ brand が localStorage に書かれず reload 後に復元されない (#828 で追加した producer 側 round-trip の非 vacuity 検証。write 喪失で classic 選択→reload→data-brand 復元が RED)",
        "file": ROOT / "js" / "settings-page.js",
        "find": "onchange: (e) => { Brand.set(e.target.value); window.render(); }",
        "replace": "onchange: (e) => { window.render(); }",
        "test": "UI write round-trip",
    },
    {
        "name": "behavior: notes Markdown inline renderer の複数マーカー逐次処理の喪失 — apps.js _renderMarkdownInline の while ループを if 化し 1 個目のマーカーのみ処理 → 同一行の 2 個目以降の **bold**/`code` とマーカー間/末尾の平文が preview から欠落する (#832 後継の markdown edge coverage。既存テストは 1 bold + 1 code のみで複数マーカー行を未検証だった穴の非 vacuity 検証)",
        "file": ROOT / "js" / "apps.js",
        "find": "while ((m = token.exec(rest)) !== null) {",
        "replace": "if ((m = token.exec(rest)) !== null) {",
        "test": "multiple bold/code markers with interleaved text",
    },
    {
        "name": "behavior: AI analyzeInput の troubleshoot 優先分岐の喪失 — ai-page.js の troubleshoot チェック行を除去 → 「エラー」+「設計」を含む入力が design へ倒れ first-match 優先順位 (troubleshoot>design) が壊れる (複数キーワード一致時の優先順位を pin するテストの非 vacuity 検証。単独キーワードテストは順序入替を素通しする穴を埋める)",
        "file": ROOT / "js" / "ai-page.js",
        "find": "            if (p.includes('エラー') || p.includes('バグ') || p.includes('失敗')) {return 'troubleshoot';}\n",
        "replace": "",
        "test": "first-match priority order",
    },
    {
        "name": "behavior: task move の done 境界 disabled affordance の喪失 — apps.js の「次のステータスへ進める」ボタン `disabled: task.status === 'done'` を false へ → done 列でも next が有効に見え「これ以上進めない」UX affordance が壊れる (moveStatus の clamp はデータを守るが disabled 属性は別レイヤーの affordance。backlog 境界と対称の done 境界被覆の非 vacuity 検証)",
        "file": ROOT / "js" / "apps.js",
        "find": "disabled: task.status === 'done',",
        "replace": "disabled: false,",
        "test": "disabled at the done boundary",
    },
    {
        "name": "behavior: pomodoro 集中時間 input の範囲外 clamp の喪失 — pomodoro-page.js work onchange の clamp(...,1,180) を外し生 parseInt へ → 999 分等の範囲外値がそのまま settings.work に入り不正 duration の timer になる (number input max=180 は programmatic/paste を防がず JS clamp が実防御。上限/下限境界の非 vacuity 検証)",
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "s.appsData.pomodoro.settings.work = clamp(parseInt(e.target.value, 10) || 25, 1, 180);",
        "replace": "s.appsData.pomodoro.settings.work = parseInt(e.target.value, 10) || 25;",
        "test": "clamps out-of-range values",
    },
    {
        "name": "behavior: pomodoro 短休憩 input の範囲外 clamp[1,60] の喪失 — pomodoro-page.js short onchange の clamp(...,1,60) を外し生 parseInt へ → 999 分等が settings.short に入り work とは別 range の境界が壊れる (#838 work とは独立の range・独立 regress の非 vacuity 検証)",
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "s.appsData.pomodoro.settings.short = clamp(parseInt(e.target.value, 10) || 5, 1, 60);",
        "replace": "s.appsData.pomodoro.settings.short = parseInt(e.target.value, 10) || 5;",
        "test": "short/long break inputs clamp",
    },
    {
        "name": "behavior: pomodoro 長休憩 input の範囲外 clamp[1,120] の喪失 — pomodoro-page.js long onchange の clamp(...,1,120) を外し生 parseInt へ → 999 分等が settings.long に入り short(60) とも別 range の上限 120 境界が壊れる (独立 regress の非 vacuity 検証)",
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "s.appsData.pomodoro.settings.long = clamp(parseInt(e.target.value, 10) || 15, 1, 120);",
        "replace": "s.appsData.pomodoro.settings.long = parseInt(e.target.value, 10) || 15;",
        "test": "short/long break inputs clamp",
    },
    {
        "name": "behavior: AI submit の空/空白プロンプトガードの喪失 — ai-page.js submit の `!input.trim() ||` を外し aiLoading のみ残す → 空文字/空白のみの送信が握り潰されず空の会話を ai.history に積み UI/localStorage を汚す (settings の空入力バリデーションは test 済だが AI 空プロンプトガードは未被覆だった穴の非 vacuity 検証)",
        "file": ROOT / "js" / "ai-page.js",
        "find": "if (!input.trim() || aiLoading) {return;}",
        "replace": "if (aiLoading) {return;}",
        "test": "ignores empty and whitespace",
    },
    {
        "name": "behavior: task addTask の空/空白タイトルガードの喪失 — apps.js addTask の `if (!title.trim())` を常時 false 化 → 空文字/空白のみの Enter が空タイトル task を backlog に積む (AI #841 と同 class の入力バリデーションガード・task 面の非 vacuity 検証)",
        "file": ROOT / "js" / "apps.js",
        "find": "if (!title.trim()) {return;}",
        "replace": "if (false) {return;}",
        "test": "ignore empty/whitespace-only input",
    },
    {
        "name": "behavior: todo addTodo の空/空白テキストガードの喪失 — apps.js addTodo の `if (!text.trim())` を常時 false 化 → 空文字/空白のみの Enter が空テキスト todo を積む (task addTask とは別 function・独立 regress の非 vacuity 検証)",
        "file": ROOT / "js" / "apps.js",
        "find": "if (!text.trim()) {return;}",
        "replace": "if (false) {return;}",
        "test": "ignore empty/whitespace-only input",
    },
    {
        "name": "behavior: snapshot 復元ボタンの未保存時 disabled affordance の喪失 — settings-page.js の 復元ボタン `disabled: !snap` を除去 → snapshot 未保存でも復元ボタンが有効に見え「復元するものが無い」affordance が壊れる (restoreSnapshot は no-op guard 済だが disabled 属性は別レイヤーの UX affordance。#836 task done 境界と同 class・snapshot 面の非 vacuity 検証)",
        "file": ROOT / "js" / "settings-page.js",
        "find": "onclick: restoreSnapshot, disabled: !snap",
        "replace": "onclick: restoreSnapshot",
        "test": "disabled until a snapshot exists",
    },
    {
        "name": "behavior: router の unknown-app whitelist else 分岐の喪失 — router.js の `apps/<app>` で whitelist 外を 'not-found' にする else を 'app-task' へ → 存在しない app サブルート (apps/nonexistent) が task ページを描画し NotFound に落ちない (top-level unknown route とは別 code path の非 vacuity 検証)",
        "file": ROOT / "js" / "router.js",
        "find": ": 'not-found';",
        "replace": ": 'app-task';",
        "test": "Unknown app subroute",
    },
    {
        "name": "behavior: profile email の ingestion 文字列長 bound の喪失 — store.js normalize の email `.slice(0, 254)` を除去 → 巨大 email が truncate されず href/表示に載り localStorage/DOM を bloat させる (AI history 文字列 bound #230 / MAX_TASKS 件数 bound #801 と同じ ingestion bloat-guard class・profile email 面の非 vacuity 検証)",
        "file": ROOT / "js" / "store.js",
        "find": "email: String(data.profile.email || store.profile.email).slice(0, 254)",
        "replace": "email: String(data.profile.email || store.profile.email)",
        "test": "email is length-bounded",
    },
    {
        "name": "behavior: 同名プロジェクト追加時の slug 一意化 (#154) の喪失 — settings-page.js addProjectManual の `while (existing.has(slug))` を while(false) へ → 同名 2 件が同一 slug になり ProjectDetailPage の find(p.slug===slug) が先頭のみ返して片方の詳細が到達不能になる実バグ regression (既存の unique-slugs test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証)",
        "file": ROOT / "js" / "settings-page.js",
        "find": "while (existing.has(slug)) {",
        "replace": "while (false) {",
        "test": "same name yields unique slugs",
    },
    {
        "name": "behavior: profile github/linkedin の URL スキームサニタイズ (#139 XSS) の喪失 — store.js safeUrl の http(s) スキームチェックを外し raw 値をそのまま返す → import した javascript:/data: 等の危険スキーム URL が ContactPage の href に載り XSS ベクタになる (既存 URL-sanitized test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証)",
        "file": ROOT / "js" / "store.js",
        "find": "return /^https?:\\/\\//i.test(s) ? s.slice(0, 500) : String(fallback || '');",
        "replace": "return s;",
        "test": "URL-sanitized",
    },
    {
        "name": "behavior: pomodoro getDuration の live-state 参照 (#134) の喪失 — pomodoro-page.js getDuration の `State.get()...settings` を render 毎キャプチャの stale closure `pomo.settings` へ戻す → 稼働中に集中時間を変えても complete() の remainingSec リセットが旧設定値を使う (getRemaining #121 と同根の stale-closure バグ。既存 mid-run test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証)",
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "const settings = State.get().appsData.pomodoro.settings;",
        "replace": "const settings = pomo.settings;",
        "test": "completion uses the latest focus-duration",
    },
    {
        "name": "behavior: AI 入力の IME composition ガード (#152) の喪失 — ai-page.js の Enter ハンドラから `&& !e.isComposing` を外す → 日本語入力で IME 変換確定の Enter が未確定テキストを誤 submit する (task IME #299 とは別 function・ai-input 独立の実バグ。日本語が主対象の本サイトで既存 test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証)",
        "file": ROOT / "js" / "ai-page.js",
        "find": "if (e.key === 'Enter' && !e.isComposing) {",
        "replace": "if (e.key === 'Enter') {",
        "test": "AI input ignores Enter during IME composition",
    },
    {
        "name": "behavior: TODO 入力の IME composition ガード (todoComposing flag) の喪失 — apps.js todo の Enter ハンドラから `&& !todoComposing` を外す → 日本語 IME 変換確定 Enter が未確定テキストを誤 submit する。task(e.isComposing)/ai(e.isComposing) とは異なり todo は手動 compositionstart/end フラグ機構ゆえ独立 regress しうる。既存 test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "apps.js",
        "find": "if (e.key === 'Enter' && !todoComposing) {",
        "replace": "if (e.key === 'Enter') {",
        "test": "Todo input ignores Enter during IME composition",
    },
    {
        "name": "behavior: quiz 検索 live-input の focus-loss guard (#258) の喪失 — quiz-renderer.js の oninput を updateSilently から State.update へ戻す → 全再描画で input が破棄され 1 文字ごとに focus を失い検索が使えなくなる実バグ。既存 focus-regression test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証 (Check 130 の静的封じと behavior 面の二層)",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": "State.updateSilently(s => { s.appsData.quizSearch = val; s.appsData.quizSearchType = quizType; });",
        "replace": "State.update(s => { s.appsData.quizSearch = val; s.appsData.quizSearchType = quizType; });",
        "test": "Quiz search input retains focus",
    },
    {
        "name": "behavior: projects 検索 live-input の focus-loss guard (#258) の喪失 — projects-page.js の oninput を部分更新 renderGrid() から全再描画 window.render() へ戻す → #content が作り直され検索 input が破棄されて 1 文字ごとに focus を失い検索使用不能になる実バグ。既存 focus-regression test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証 (quiz #258 と同 class・別 surface)",
        "file": ROOT / "js" / "projects-page.js",
        "find": "renderGrid(); // 部分更新でフォーカスを死守",
        "replace": "window.render();",
        "test": "retains focus during filtering",
    },
    {
        "name": "behavior: command-palette close 時の opener への focus 復元 (#700 WCAG 2.4.3) の喪失 — command-palette.js close() の lastFocused.focus() を除去 → palette を閉じても起動元へ focus が戻らず SR/キーボード利用者が文脈を失う a11y 退行。既存 focus-restore test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "command-palette.js",
        "find": "if (lastFocused && lastFocused.focus) { try { lastFocused.focus(); } catch (e) { /* noop */ } }",
        "replace": "if (lastFocused && lastFocused.focus) { try { /* focus removed */ } catch (e) { /* noop */ } }",
        "test": "restores focus to the opener on close",
    },
    {
        "name": "behavior: ProjectsPage の無効 ?cat= 正規化 (control↔filter desync guard) の喪失 — projects-page.js の `cat = 'All'` 再代入を除去 → 無効 URL query cat が正規化されず、<select> は option 不在で 'All' 表示なのに filter は無効値で 0 件 = 「All なのに空」desync が復活 (#93/#295 と同族の外部入力 validate discipline)。既存 desync-guard test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "projects-page.js",
        "find": "if (cat !== 'All' && !categories.includes(cat)) { cat = 'All'; }",
        "replace": "if (cat !== 'All' && !categories.includes(cat)) { /* normalize removed */ }",
        "test": "normalizes an invalid ?cat= to All",
    },
    {
        "name": "behavior: skip-link の native-nav 抑止 (#779 WCAG 2.4.1) の喪失 — main.js skip-link click ハンドラの e.preventDefault() を除去 → native fragment 挙動で location.hash が '#main-content' に変わり router が非-'#/' hash を home 扱いで再描画 → 非 home ページ(#/projects)で「本文へスキップ」がユーザーを home へ誤遷移させる実バグ復活。main.js に preventDefault は 1 個(skip-link 専用)。既存 skip-link test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "main.js",
        "find": "e.preventDefault();",
        "replace": "/* preventDefault removed (#779 skip-link native-nav regression) */",
        "test": "Skip link moves focus to #main-content",
    },
    {
        "name": "behavior: quiz architecture 検索の stakeholder 被覆 (#285 visible-but-unsearchable) の喪失 — quiz-renderer.js _filterBy の return から `|| stakeholderMatch` を除去 → 画面に描画される stakeholder の name/quote (例 CTO の GAFA 発言) が検索対象外に戻り「見えるのに 0 件」drift が復活。既存 stakeholder-search test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": "return titleMatch || idMatch || contentMatch || situationMatch || questionMatch || stakeholderMatch;",
        "replace": "return titleMatch || idMatch || contentMatch || situationMatch || questionMatch;",
        "test": "matches stakeholder quote text",
    },
    {
        "name": "behavior: cross-tab storage 取り込みの schema guard (#295/#93) の喪失 — state.js storage リスナーの `if (incoming.schemaVersion !== SCHEMA_VERSION) return` を除去 → デプロイ跨ぎ (別バージョン) の異 schema / 欠損 store が別タブから来ると採用見送りされず validateAndNormalize を通って現タブの正常 state を上書き → own task 消失 (欠損時は FatalPage crash もありうる #93 class)。既存 foreign-schema-ignore test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "state.js",
        "find": "if (incoming.schemaVersion !== CONSTANTS.SCHEMA_VERSION) {return;}",
        "replace": "/* cross-tab schema guard removed (#295) */",
        "test": "foreign-schema/malformed store",
    },
    {
        "name": "behavior: quiz 検索の section 章タイトル被覆 (#296 visible-but-unsearchable) の喪失 — quiz-renderer.js _filterBy の `sectionMatch = !query || section.includes(query)` から section 一致項を除去 → 画面描画される section 章タイトル (例「第4章：可用性とFinOps…」) が検索対象外に戻り、タイトルにのみ含まれる語 (FinOps) で「見えるのに 0 件」drift が復活。既存 section-header-search test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": "const sectionMatch = !query || section.toLowerCase().includes(query);",
        "replace": "const sectionMatch = !query;",
        "test": "section-header (chapter title)",
    },
    {
        "name": "behavior: drawer の desktop リサイズ stuck-state guard の喪失 — mobile-drawer.js syncMobileDrawer の !isMobile 分岐で開放中 drawer を閉じる条件を無効化 → drawer 開放中に mobile→desktop へリサイズすると inline display:block が media query に勝って drawer/overlay が残り、__setAppInert(true)+__lockBodyScroll(true) のまま app が inert・scroll lock された stuck 状態 (topbar=display:none で menuBtn も隠れ overlay/Escape でしか脱出不能な broken UX) が復活。既存 stuck-state-guard test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "mobile-drawer.js",
        "find": "if (drawer && drawer.getAttribute('aria-hidden') === 'false') {",
        "replace": "if (false && drawer && drawer.getAttribute('aria-hidden') === 'false') {",
        "test": "resize to desktop",
    },
    {
        "name": "behavior: snapshot restore の正規化 (#561/#93/#295) の喪失 — settings-page.js restoreSnapshot の `State.set(Store.validateAndNormalize(snap.data))` を生 `State.set(snap.data)` に戻す → 旧版が保存した schema 不一致/projects・appsData 欠落 snapshot を復元すると renderer が state.projects.map 等で未定義参照し FatalPage crash (外部入力 ingestion は全て正規化を通せ class・importJSON は通すのに restore だけ生採用していた未被覆経路)。既存 snapshot-restore-normalize test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "settings-page.js",
        "find": "State.set(Store.validateAndNormalize(snap.data));",
        "replace": "State.set(snap.data);",
        "test": "Snapshot restore normalizes a foreign-schema/partial snapshot",
    },
    {
        "name": "behavior: store.js の非配列 ai.history ingestion guard (#568/#93) の喪失 — normalizeAppsData の `if (Array.isArray(data.ai?.history))` を旧 truthy 判定 `if (data.ai?.history)` に戻す → 別 schema/破損 store が ai.history を非配列 (文字列等) で持つと `.filter` が TypeError → validateAndNormalize 例外 → load()/cross-tab/import/snapshot-restore の全 ingestion 経路が FatalPage crash (normalizeAppsData の総関数契約違反)。既存 non-array-history-tolerance test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "store.js",
        "find": "if (Array.isArray(data.ai?.history)) {",
        "replace": "if (data.ai?.history) {",
        "test": "tolerates a non-array ai/pomodoro history",
    },
    {
        "name": "behavior: pomodoro 短休憩 onchange の idle 表示即更新 (#692 work との対称性) の喪失 — pomodoro-page.js short-break onchange の `remainingSec = settings.short * 60` を除去 → 短休憩モードで idle 中に短休憩時間を変えても表示中の remainingSec が古い duration のまま (start すると旧設定長で始まる)。従来 work だけこの即更新があり short/long は欠落していた asymmetry 実バグ。既存 break-symmetry test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "s.appsData.pomodoro.runtime.remainingSec = s.appsData.pomodoro.settings.short * 60;",
        "replace": "/* #692 short-break symmetry update removed */",
        "test": "break-duration change updates the idle timer",
    },
    {
        "name": "behavior: store.js の ingestion 側 ai.history prompt 文字列 bound (#230 class) の喪失 — normalizeAppsData の `prompt: String(h.prompt).slice(0, CONSTANTS.LIMITS.AI_MESSAGE)` から `.slice(0, AI_MESSAGE)` を外し生 `String(h.prompt)` に戻す → 巨大 prompt (20000 字) を含む store を load/import/cross-tab で取り込むと prompt が切り詰められず localStorage を bloat させる (write 側 apps.js は AI_MESSAGE で bound 済だが ingestion 側正規化が個々文字列長を bound しない未閉じ枝)。既存 length-bounded-on-normalize test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "store.js",
        "find": "prompt: String(h.prompt).slice(0, CONSTANTS.LIMITS.AI_MESSAGE),",
        "replace": "prompt: String(h.prompt),",
        "test": "AI history strings are length-bounded on normalize ingestion",
    },
    {
        "name": "behavior: drawer overlay(背景)クリック close の喪失 — main.js init の `#overlay` click→closeDrawer 直接リスナー配線を no-op function に差し替え → モバイルドロワーを開いたまま背景 overlay をクリックしても閉じない (モーダル標準の backdrop dismiss が壊れる)。Escape/nav-link close は別経路ゆえ独立に regress しうる。既存 overlay-backdrop-click test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "main.js",
        "find": "document.getElementById('overlay')?.addEventListener('click', closeDrawer);",
        "replace": "document.getElementById('overlay')?.addEventListener('click', function () {});",
        "test": "Mobile drawer closes on overlay (backdrop) click",
    },
    {
        "name": "behavior: relatedProjectIds 要素の String 正規化 (#782 id-coercion) の喪失 — store.js normalizeProject の `relatedProjectIds: (...).filter(Boolean).map(String).slice(0, 20)` から `.map(String)` を外す → import データが数値 id の relatedProjectIds を持つと、normalizeProject が id 自体は `String(raw.id)` で文字列化する一方 relatedProjectIds 要素は数値のまま残り、ProjectDetailPage の `relatedProjectIds.includes(p.id)` (p.id=文字列) と strict 不一致 → 関連プロジェクトリンクが silent に消える (#93/#295 の外部 ingestion 全経路正規化 class の relatedProjectIds 版)。既存 numeric-relatedProjectIds test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "store.js",
        "find": "relatedProjectIds: (Array.isArray(raw.relatedProjectIds) ? raw.relatedProjectIds : []).filter(Boolean).map(String).slice(0, 20),",
        "replace": "relatedProjectIds: (Array.isArray(raw.relatedProjectIds) ? raw.relatedProjectIds : []).filter(Boolean).slice(0, 20),",
        "test": "Imported numeric relatedProjectIds resolve to string ids",
    },
    {
        "name": "behavior: pomodoro reload auto-resume (#121 frozen-timer guard) の喪失 — pomodoro-page.js の `if (isActive && !pomodoroTimer) { startTimer(); }` 条件を `false && ...` で無効化 → reload 後に isActive=true (endAtMs>now を normalize が保持) でも interval が再起動されず、「一時停止ボタン表示だが countdown が frozen で complete() が永遠に発火しない」stuck 状態が復活 (pomodoroTimer は factory 変数ゆえ reload で null に戻り start() ボタン経由でしか起動されなかった元バグ)。既存 frozen-timer-guard test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "if (isActive && !pomodoroTimer) {",
        "replace": "if (false && isActive && !pomodoroTimer) {",
        "test": "resumes ticking after a reload mid-run",
    },
    {
        "name": "behavior: settings のプロジェクト並べ替え (moveProject up/down) の喪失 — settings-page.js moveProject の境界ガード `if (idx + dir < 0 || idx + dir >= s.projects.length) {return;}` を `if (true || ...)` で常に return させ swap を無効化 → ↑↓ ボタンを押しても順序が変わらず、並べ替えが localStorage に反映されない (State.update の swap が dead になる)。既存 reorder test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "settings-page.js",
        "find": "if (idx + dir < 0 || idx + dir >= s.projects.length) {return;}",
        "replace": "if (true || idx + dir < 0 || idx + dir >= s.projects.length) {return;}",
        "test": "Projects can be reordered with the up/down controls",
    },
    {
        "name": "behavior: default プロジェクト並べ替えの reload 永続 (mergeProjectsWithDefaults 順序保持) の喪失 — store.js の incoming 順優先 merge を default 定義順優先へ戻す (`for (const p of normalizedIncoming)` ループを `for (const d of normalizedDefaults)` へ) → settings ↑↓ で default project 同士を並べ替えても reload の normalize round-trip で元の定義順へ silent に戻る data-fidelity バグが復活 (user 追加 project は incoming 順 append で保持されるため default だけが失われる)。回帰 e2e に対応する mutation で safety-net を institutionalize する非 vacuity 検証",
        "file": ROOT / "js" / "store.js",
        "find": "        // 1. incoming(保存済み)順を保持 — default field は id で backfill し incoming の値を優先。\n        for (const p of normalizedIncoming) {\n            const d = defaultsById.get(p.id);\n            merged.push(d ? ({ ...d, ...p, id: d.id }) : p);\n            mergedIds.add(p.id);\n        }",
        "replace": "        // MUTATION: revert to default-definition order (drops reorder persistence).\n        for (const d of normalizedDefaults) {\n            const p = normalizedIncoming.find(x => x.id === d.id);\n            merged.push(p ? ({ ...d, ...p, id: d.id }) : d);\n            mergedIds.add(d.id);\n        }",
        "test": "Default project reorder persists across reload",
    },
    {
        "name": "behavior: TODO の「完了をクリア」ボタンの affordance ガード (disabled until a todo is completed) の喪失 — apps.js TodoPage の `disabled: !todos.some(t => t.completed)` を `disabled: false` にし常時活性化 → 完了 todo が 1 件も無い状態でもボタンが押せてしまい、空 filter 操作 (実質 no-op だが誤操作導線) を許す affordance 契約の喪失。既存 clear-completed-disabled test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "apps.js",
        "find": "disabled: !todos.some(t => t.completed),",
        "replace": "disabled: false,",
        "test": "Todo clear-completed button is disabled until a todo is completed",
    },
    {
        "name": "behavior: task カンバンの status 遷移 (moveStatus) の喪失 — apps.js moveStatus の `updateTask(task.id, { status: statuses[newIdx] })` を `statuses[idx]` に変え遷移先を現在 status に固定 → ←/→ ボタンを押してもカードが列を移動せず status が変わらない (backlog→in-progress→done の遷移が dead)。既存 kanban-move-persist test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "apps.js",
        "find": "updateTask(task.id, { status: statuses[newIdx] });",
        "replace": "updateTask(task.id, { status: statuses[idx] });",
        "test": "moves across kanban columns and persists the status",
    },
    {
        "name": "behavior: task の優先度フィルタ (getFilteredTasks) の喪失 — apps.js の `taskFilter.priority === 'all' || t.priority === taskFilter.priority` を `true` に変え全タスクを常に通す → 優先度フィルタを high/low に絞ってもボードが絞り込まれず全件表示のまま (フィルタが no-op 化)。既存 priority-filter-narrows test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "apps.js",
        "find": "taskFilter.priority === 'all' || t.priority === taskFilter.priority",
        "replace": "true",
        "test": "priority filter narrows the board by priority",
    },
    {
        "name": "behavior: pomodoro 完了時の history エントリの session type 記録の喪失 — pomodoro-page.js complete() の history push で `type: s.appsData.pomodoro.runtime.mode` を固定リテラル `type: 'break'` に変え、記録される session type が実 mode を反映しなくなる → 完了した work セッションが 'break' として履歴に残り、集計/表示が誤る。新設 completion-history-record test に対応する mutation で safety-net を institutionalize する非 vacuity 検証",
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "type: s.appsData.pomodoro.runtime.mode,",
        "replace": "type: 'break',",
        "test": "records a history entry with the session type and duration",
    },
    {
        "name": "behavior: projectPrefs.hiddenIds の normalize round-trip 保持の喪失 — store.js validateAndNormalize の projectPrefs 読み戻しガード `if (data.projectPrefs && ... Array.isArray(data.projectPrefs.hiddenIds))` を `if (false && ...)` で無効化 → reload の normalize で hiddenIds が drop され、非表示にしたプロジェクトが公開一覧へ silent に復活する (#294/#568/#684/#871 の persist-drift class の projectPrefs 版)。新設 hidden-persist test に対応する mutation で safety-net を institutionalize する非 vacuity 検証",
        "file": ROOT / "js" / "store.js",
        "find": "if (data.projectPrefs && typeof data.projectPrefs === 'object' && Array.isArray(data.projectPrefs.hiddenIds)) {",
        "replace": "if (false && data.projectPrefs && typeof data.projectPrefs === 'object' && Array.isArray(data.projectPrefs.hiddenIds)) {",
        "test": "Hidden project stays hidden on the public list across reload",
    },
    {
        "name": "a11y: ProjectsPage の検索 landmark (role='search') の喪失 — projects-page.js の検索 wrapper から `role: 'search'` を外す → 検索入力が ARIA search landmark でなくなり、SR ユーザーが landmark ナビゲーションで検索領域へジャンプできなくなる (WCAG 1.3.1・ARIA APG search landmark の退行)。新設 search-landmark test に対応する mutation で safety-net を institutionalize する非 vacuity 検証",
        "file": ROOT / "js" / "projects-page.js",
        "find": "h('div', { class: 'relative', role: 'search' },",
        "replace": "h('div', { class: 'relative' },",
        "test": "Projects search is exposed as an ARIA search landmark",
    },
    {
        "name": "a11y: QuizPage の検索 landmark (role='search') の喪失 — quiz-renderer.js の検索 wrapper から `role: \"search\"` を外す → 検索入力が ARIA search landmark でなくなり SR ユーザーが landmark ナビで検索領域へジャンプできなくなる (WCAG 1.3.1・ARIA APG・ProjectsPage #879 と同型)。新設 quiz-search-landmark test に対応する mutation で safety-net を institutionalize する非 vacuity 検証",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": "h(\"div\", { class: \"relative\", role: \"search\" },",
        "replace": "h(\"div\", { class: \"relative\" },",
        "test": "Quiz search is exposed as an ARIA search landmark",
    },
    {
        "name": "a11y: ProjectsPage 件数表示の live region (WCAG 4.1.3) の喪失 — projects-page.js の countDisplay から `role: 'status', 'aria-live': 'polite'` を外す → 検索/カテゴリ絞り込みで `合計 N 件` が変わっても SR ユーザーへ通知されなくなる (非 0 件の件数変化が silent に戻る Status Messages 退行)。新設 count-live-region test に対応する mutation で safety-net を institutionalize する非 vacuity 検証",
        "file": ROOT / "js" / "projects-page.js",
        "find": "countDisplay = h('p', { class: 'text-muted', role: 'status', 'aria-live': 'polite' }, '')",
        "replace": "countDisplay = h('p', { class: 'text-muted' }, '')",
        "test": "Projects result count is an aria-live status region",
    },
    {
        "name": "a11y: quiz 模範解答フォームの email 必須マーク (WCAG 3.3.2) の喪失 — quiz-renderer.js emailInput の `'aria-required': 'true'` を外す → submit の JS バリデーションで必須の メールアドレスが SR ユーザーに必須と露出されず、送信してエラー Toast が出るまで必須と分からない (Labels or Instructions の退行)。新設 form-required test に対応する mutation で safety-net を institutionalize する非 vacuity 検証",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": "'aria-label': 'メールアドレス', 'aria-required': 'true' }",
        "replace": "'aria-label': 'メールアドレス' }",
        "test": "Quiz contact form marks name and email as aria-required",
    },
    {
        "name": "behavior: 自動推薦の明示-related 除外の喪失 — store.js autoRelatedCandidates の候補 filter から `&& !fixed.has(p.id)` を外す → target.relatedProjectIds に既にある明示 related が推薦候補へ戻り、プロジェクト詳細の「関連プロジェクト」節と「おすすめ（自動）」節に同じプロジェクトが二重表示される (推薦枠 8 件が既知の関連で埋まり新規発見価値が失われる)。新設 auto-recommendation exclusion test に対応する mutation で safety-net を institutionalize する非 vacuity 検証",
        "file": ROOT / "js" / "store.js",
        "find": ".filter(p => p && p.id && p.id !== target.id && !fixed.has(p.id))",
        "replace": ".filter(p => p && p.id && p.id !== target.id)",
        "test": "Auto-recommendations exclude self and explicitly-related projects",
    },
    {
        "name": "behavior: hidden project が home の注目枠へ漏れる — home-page.js の featured 選定を visibleProjects から素の state.projects へ戻す → 非表示にした default project (削除不可＝非表示が唯一の非公開手段) がトップページ最上位の注目枠に出続け、詳細/デモ導線も残る (公開一覧からは消えているため owner は気づけない listing 面 mesh の漏れ)",
        "file": ROOT / "js" / "home-page.js",
        "find": "const featured = visibleProjects.find(p => p.demoRoute === 'task') || visibleProjects[0] || null;",
        "replace": "const featured = state.projects.find(p => p.demoRoute === 'task') || state.projects[0] || null;",
        "test": "Hidden project disappears from home featured",
    },
    {
        "name": "behavior: hidden project が詳細ページの推薦へ漏れる — project-detail-page.js の related 算出を listable(非表示除外済) から素の state.projects へ戻す → 非表示にしたプロジェクトが「関連プロジェクト」カードとして出続け、そこから詳細ページへ到達できる (listing 面 mesh の漏れ)",
        "file": ROOT / "js" / "project-detail-page.js",
        "find": "const related = listable.filter(p =>",
        "replace": "const related = state.projects.filter(p =>",
        "test": "Hidden project disappears from home featured",
    },
    {
        "name": "behavior: hidden project が Cmd+K 候補へ漏れる — command-palette.js の候補 filter から `&& !_hidden.has(String(p.id))` を落とす → 公開一覧から消したプロジェクトが palette で検索・到達でき、非表示が「一覧だけの部分的な隠蔽」に退行する (listing 面 mesh の漏れ)",
        "file": ROOT / "js" / "command-palette.js",
        "find": " && !_hidden.has(String(p.id))",
        "replace": "",
        "test": "Hidden project disappears from home featured",
    },
    {
        "name": "behavior: hiring-risk CTA が AWS フォールバックへ着地 — quiz-renderer.js の QUIZ_DATA_MAP から 'pm' キーを rename → URL は #/quiz?type=pm のままなのに `|| QUIZ_DATA_MAP.aws` が効き、「PM問題集を見る」ボタンから AWS 問題集が黙って描画される silent wrong-content (throw も console error も無く、直接 URL で開く既存 quiz e2e も CTA 経路を通らないため素通りする)。Check 401a が静的に守る面の behavioral 対",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": "            pm: { title: 'PM問題集', data: pmQuizData },",
        "replace": "            pmX: { title: 'PM問題集', data: pmQuizData },",
        "test": "Hiring-risk CTAs land on the quiz named on the button",
    },
    {
        "name": "behavior: sr-only AIO entity anchor の silent removal — index.html の <div class=\"sr-only\" id=\"aio-footer-entity\"> の id を rename → 著作権/entity/canonical ブロックが DOM から消える。旧テストは `if (await entity.count())` の skip-on-missing で黙って PASS する vacuous gate だった (実測で確認し presence 必須へ是正)。是正版が実際に RED になることの検証",
        "file": ROOT / "index.html",
        "find": '<div class="sr-only" id="aio-footer-entity" aria-hidden="true">',
        "replace": '<div class="sr-only" id="aio-footer-entity-renamed" aria-hidden="true">',
        "test": "sr-only content (route announcer + AIO entity anchor) stays visually hidden",
    },
    {
        "name": "behavior: quiz 検索語の種別スコープ喪失 — quiz-renderer.js の initialSearch を quizSearchType 一致条件から素の quizSearch へ戻す → ある種別で検索したまま別種別へ切り替えると語が持ち越され、切替先が「一致する問題は見つかりませんでした」の空ページになる (sidebar の種別リンク / hiring-risk の CTA はどちらも主要導線)。実測で architecture の 'CAP' が PM へ持ち越され PM が 0 件表示になっていた実バグの回帰防止",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": "        const initialSearch = (state.appsData.quizSearchType === quizType)\n            ? (state.appsData.quizSearch || \"\")\n            : \"\";",
        "replace": "        const initialSearch = state.appsData.quizSearch || \"\";",
        "test": "Quiz search term does not leak across quiz types",
    },
    {
        "name": "behavior: プロジェクト詳細のデモ起動導線が壊れる — project-detail-page.js の「アプリを起動」を apps/<demoRoute> から誤 route (projects) へ差し替え → 閲覧者が作品を触るまでの主要ジャーニーが切れる。Check 136 は demoRoute 値が router whitelist にあることしか見ず、ボタンが実際に遷移してアプリが描画されるかは未被覆だった",
        "file": ROOT / "js" / "project-detail-page.js",
        "find": "onclick: () => Router.navigate(`apps/${project.demoRoute}`)",
        "replace": "onclick: () => Router.navigate(`projects`)",
        "test": "Project demo launch buttons open the embedded app",
    },
    {
        "name": "resilience: crypto.randomUUID 不在環境で項目追加が壊れる — js/pure-utils.js の generateId のフォールバック本体 (Math.random ベースの RFC 4122 テンプレート) を潰す → randomUUID はセキュアコンテキスト限定 API ゆえ http:// の LAN プレビュー (PC の http-server をスマホから開く等) で undefined になり、その閲覧経路でだけ項目追加が例外になる。なお feature-detection (typeof crypto...) を外すだけでは外側の try/catch が TypeError を吸収してフォールバックが働くため mutation として no-op = vacuous になる (実測済)。フォールバック本体を潰す形が正しい非 vacuity 検証",
        "file": ROOT / "js" / "pure-utils.js",
        "find": "    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {",
        "replace": "    return crypto.randomUUID();\n    // eslint-disable-next-line no-unreachable\n    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {",
        "test": "Item creation still works when crypto.randomUUID is unavailable",
    },
    {
        "name": "resilience: localStorage 不在環境での白画面化 — js/storage.js の get() から try/catch を外し素の localStorage アクセスへ → プライベートブラウジング等で localStorage アクセス自体が SecurityError を投げる環境の全ユーザーがコンテンツ非描画 (白画面) になる。quota 超過 (書き込み失敗) とは別クラスの堅牢性の回帰防止",
        "file": ROOT / "js" / "storage.js",
        "find": "        try {\n            return localStorage.getItem(key);",
        "replace": "        {\n            return localStorage.getItem(key);",
        "test": "SPA still renders when localStorage access itself throws",
    },
    {
        "name": "a11y: settings 追加フォームの検証フィールド特定喪失 — settings-page.js の addProjectManual から aria-invalid の付与と focus 移動を除去 → SR 利用者は Toast のエラーだけ聞かされ「どの入力が不正か」を判別できない (WCAG 3.3.1 / 2.4.3・quiz フォーム #913 と同 class の残り 1 面)",
        "file": ROOT / "js" / "settings-page.js",
        "find": "                if (nameEl) { nameEl.setAttribute('aria-invalid', 'true'); nameEl.focus(); }",
        "replace": "",
        "test": "Settings add-project form marks the empty name aria-invalid",
    },
    {
        "name": "a11y: quiz フォーム検証のフィールド特定喪失 — quiz-renderer.js の送信ハンドラから最初の不正フィールドへの focus 移動を除去 → SR 利用者は Toast のエラーだけ聞かされ「どのフィールドが不正か」を自力で探す羽目になる (WCAG 3.3.1 Error Identification / 2.4.3)。aria-invalid + focus 移動による識別の回帰防止",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": "                    (!name ? nameInput : emailInput).focus();",
        "replace": "",
        "test": "Quiz contact form marks the offending field aria-invalid",
    },
    {
        "name": "a11y: 分担表の ARIA table 構造の喪失 — pages.js splitRow のカテゴリセルから `role: 'rowheader'` を外す → 行見出しが失われ、SR はセル読み上げ時にどのカテゴリ行かの文脈を得られなくなる (分担表は div グリッドで table 要素を持たないため ARIA role が唯一の構造露出手段・WCAG 1.3.1)。axe は role の妥当性しか見ず role 除去は違反にならないため behavior e2e が唯一の gate。新設 table-semantics test の非 vacuity 検証",
        "file": ROOT / "js" / "pages.js",
        "find": "class: 'cell-category', role: 'rowheader'",
        "replace": "class: 'cell-category'",
        "test": "Role-split division table exposes ARIA table semantics",
    },
    {
        "name": "behavior: 検索×カテゴリの AND 合成の喪失 — projects-page.js の getFilteredProjects で category 絞り込みを「検索語が無いときだけ」に狭める → カテゴリ選択中に検索するとカテゴリが無視され、選択中の <select> 表示と実際の結果が desync する (control↔filter desync・#350 と同族)。cat 単独 / q 単独の既存テストは通り続けるため、併用を検証する新テストだけが捕捉できる",
        "file": ROOT / "js" / "projects-page.js",
        "find": "            if (cat !== 'All') {\n                list = list.filter(p => p.category === cat);",
        "replace": "            if (cat !== 'All' && !q) {\n                list = list.filter(p => p.category === cat);",
        "test": "Search and category filters compose",
    },
    {
        "name": "behavior: notes editor の silent data-loss 再混入 — apps.js の textarea から maxlength を外す → 保存側は LIMITS.NOTES_TEXT で slice するのに UI は無制限に受け付け、超過分は textarea にもライブプレビューにも表示され続けたまま保存されない (リロードして初めて消失が判明する silent data-loss)。UI 上限と永続化上限の一致 (Check 410 の behavioral 面) の回帰防止",
        "file": ROOT / "js" / "apps.js",
        "find": "            maxlength: CONSTANTS.LIMITS.NOTES_TEXT,",
        "replace": "",
        "test": "Notes editor cannot hold more text than it persists",
    },
    {
        "name": "behavior: quiz の外部入力 ?type= がプロトタイプ継承キーで crash する回帰 — quiz-renderer.js の hasOwnProperty ガードを素の `MAP[type] || fallback` へ戻す → 'constructor' 等は truthy な非 config 値 (Object コンストラクタ) を返して fallback を素通りし、sourceData が undefined のまま Object.keys(undefined) が throw → FatalPage でページ全体が表示不能になる (実測)。外部入力を object 添字に使う際の own-key 検証の回帰防止",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": "        const quizConfig = Object.prototype.hasOwnProperty.call(QUIZ_DATA_MAP, quizType)\n            ? QUIZ_DATA_MAP[quizType]\n            : QUIZ_DATA_MAP.aws;",
        "replace": "        const quizConfig = QUIZ_DATA_MAP[quizType] || QUIZ_DATA_MAP.aws;",
        "test": "prototype-inherited",
    },
    {
        "name": "behavior: route-render gate 自体の非 vacuity — main.js render の case 'role-split' から page = RoleSplitPage() の代入を落とす (葉抽出で配線を落とす回帰 class) → page が undefined のまま appendChild され TypeError で #content 空 + pageerror。全ルートの描画健全性を守る中核 gate (security-proxy の ALL_ROUTES loop) が実際に RED になることの検証。この loop は題名が backtick テンプレートで、Check 379/397 が引用符リテラルしか parse しなかった間は mutation を登録できなかった",
        "file": ROOT / "main.js",
        "find": "                        case 'role-split':\n                            page = RoleSplitPage();\n",
        "replace": "                        case 'role-split':\n",
        "test": "renders without runtime errors",
    },
    {
        "name": "a11y: quiz 章アイコンの装飾絵文字が SR に読み上げられる回帰 — quiz-renderer.js の quiz-section-icon から aria-hidden を外す → アクセシビリティツリーに 🏛️ 等が露出し、SR は全章で章題の前に「classical building」等の無意味な語を読む (WCAG 1.1.1・axe は装飾テキスト露出をルール化しないため behavior e2e が唯一の gate)",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": "{ class: \"quiz-section-icon\", 'aria-hidden': 'true' }, icons[sIdx]",
        "replace": "{ class: \"quiz-section-icon\" }, icons[sIdx]",
        "test": "decorative emoji are hidden from the accessibility tree",
    },
    {
        "name": "behavior: WebMCP の DOM 抽出契約の喪失 — js/pages.js splitRow の human 列から機械向けフック data-ai-role を外す → WebMCP ツールが役割分担表の human/ai を区別して抽出できなくなる (agentic 面の contract 破壊)",
        "file": ROOT / "js" / "pages.js",
        "find": "class: 'cell-human', role: 'cell', 'data-ai-role': 'human'",
        "replace": "class: 'cell-human', role: 'cell'",
        "test": "WebMCP role-split extraction selector resolves",
    },
    {
        "name": "behavior: ルート追従 JSON-LD の silent 喪失 — main.js の _installSemanticDriftGuard から MutationObserver の observe 配線を落とす → script[data-ld='dynamic-route'] がルート遷移で更新されなくなり、AI クローラは初期状態の structured data しか見なくなる。視覚に一切出ないため screenshot も他の e2e も consistency も捕捉できなかった silent-critical な AIO 配線 (#133/#134/#135 と同 class) の回帰防止",
        "file": ROOT / "main.js",
        "find": "                    _observer.observe(contentEl, { childList: true, subtree: false });",
        "replace": "                    void _observer;",
        "test": "dynamic JSON-LD is injected and tracks the current route",
    },
    {
        "name": "behavior: aio-guard の自己修復が働かなくなる回帰 — aio-guard.js の MutationObserver 監視対象を document.body から document.head へ変える → hidden な AIO アンカーが削除されても復元されない。script 配線は残るため Check 133 は緑のまま (= 「配線はあるが機能しない」class・#929 WebMCP と同じレンズ)。視覚に出ない要素ゆえ screenshot も他の e2e も気付けない",
        "file": ROOT / "aio-guard.js",
        "find": "        _observer.observe(document.body, { childList: true, subtree: true });\n    }\n\n    // Attach to DOMContentLoaded",
        "replace": "        _observer.observe(document.head, { childList: true, subtree: true });\n    }\n\n    // Attach to DOMContentLoaded",
        "test": "aio-guard restores the hidden AIO anchor after it is removed",
    },
]
