#!/usr/bin/env python3
"""mutation_samples_e2e_archive.py — 旧 (rotated) behavior mutation データ (e2e 版 log-rotation part 1).

consistency 側 (mutation_samples_archive*.py) と同じ理由・同じ方式の e2e 版。curated mutation は
増分ごとに時系列で追記され無限に成長するため、hot log (mutation_samples.py) が Check 365 の
1,000 行 cap に近づいたら最古の連続ブロックを本 archive へ移す。

**なぜ e2e 版が後から必要になったか**: consistency 側にだけ rotation 機構があり、
E2E_MUTATIONS は単一リテラルのまま増え続けていた。実際 2026-08-10 に hot log が 996 行 (advisory
budget 975 超過・BLOCKING の 1,000 まで残り 4 行) に達し、**当たる前に**先回りで機構を用意した。

- 公開: E2E_MUTATIONS_ARCHIVE (dict の list)。mutation_samples.py が tail と連結して
  公開 API E2E_MUTATIONS を構成する (順序 = 時系列: ARCHIVE(古) + tail(新))。
- 各 entry の意味・非 vacuous 保証・実行機構は mutation_probe.py の docstring を参照。
"""
from __future__ import annotations

from mutation_samples_common import ROOT, CHECK  # noqa: F401 (entry 内で参照)

E2E_MUTATIONS_ARCHIVE = [
    {
        "name": "behavior: AI analyzeInput の troubleshoot 優先分岐の喪失 — ai-page.js の troubleshoot チェック行を除去 → 「エラー」+「設計」を含む入力が design へ倒れ first-match 優先順位 (troubleshoot>design) が壊れる (複数キーワード一致時の優先順位を pin するテストの非 vacuity 検証。単独キーワードテストは順序入替を素通しする穴を埋める)",
        "file": ROOT / "js" / "ai-page.js",
        "find": "            if (p.includes('エラー') || p.includes('バグ') || p.includes('失敗')) {return 'troubleshoot';}\n",
        "replace": "",
        "test": "first-match priority order",
    },
    {
        "name": "behavior: TODO 入力の IME composition ガード (todoComposing flag) の喪失 — apps.js todo の Enter ハンドラから `&& !todoComposing` を外す → 日本語 IME 変換確定 Enter が未確定テキストを誤 submit する。task(e.isComposing)/ai(e.isComposing) とは異なり todo は手動 compositionstart/end フラグ機構ゆえ独立 regress しうる。既存 test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "apps.js",
        "find": "if (e.key === 'Enter' && !todoComposing) {",
        "replace": "if (e.key === 'Enter') {",
        "test": "Todo input ignores Enter during IME composition",
    },
    {
        "name": "behavior: quiz 検索 live-input の focus-loss guard (#258) の喪失 — quiz-renderer.js の oninput を updateSilently から State.update へ戻す → 全再描画で input が破棄され 1 文字ごとに focus を失い検索が使えなくなる実バグ。既存 focus-regression test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証 (Check 130 の静的封じと behavior 面の二層)",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": "State.updateSilently(s => { s.appsData.quizSearch = val; s.appsData.quizSearchType = quizType; });",
        "replace": "State.update(s => { s.appsData.quizSearch = val; s.appsData.quizSearchType = quizType; });",
        "test": "Quiz search input retains focus",
    },
    {
        "name": "behavior: projects 検索 live-input の focus-loss guard (#258) の喪失 — projects-page.js の oninput を部分更新 renderGrid() から全再描画 window.render() へ戻す → #content が作り直され検索 input が破棄されて 1 文字ごとに focus を失い検索使用不能になる実バグ。既存 focus-regression test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証 (quiz #258 と同 class・別 surface)",
        "file": ROOT / "js" / "projects-page.js",
        "find": "renderGrid(); // 部分更新でフォーカスを死守",
        "replace": "window.render();",
        "test": "retains focus during filtering",
    },
    {
        "name": "behavior: command-palette close 時の opener への focus 復元 (#700 WCAG 2.4.3) の喪失 — command-palette.js close() の lastFocused.focus() を除去 → palette を閉じても起動元へ focus が戻らず SR/キーボード利用者が文脈を失う a11y 退行。既存 focus-restore test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "command-palette.js",
        "find": "            try { lastFocused.focus({ preventScroll: true }); } catch (e) { /* noop */ }",
        "replace": "            try { /* focus removed */ } catch (e) { /* noop */ }",
        "test": "restores focus to the opener on close",
    },
    {
        "name": "behavior: ProjectsPage の無効 ?cat= 正規化 (control↔filter desync guard) の喪失 — projects-page.js の `cat = 'All'` 再代入を除去 → 無効 URL query cat が正規化されず、<select> は option 不在で 'All' 表示なのに filter は無効値で 0 件 = 「All なのに空」desync が復活 (#93/#295 と同族の外部入力 validate discipline)。既存 desync-guard test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "projects-page.js",
        "find": "if (cat !== 'All' && !categories.includes(cat)) { cat = 'All'; }",
        "replace": "if (cat !== 'All' && !categories.includes(cat)) { /* normalize removed */ }",
        "test": "normalizes an invalid ?cat= to All",
    },
    {
        "name": "behavior: skip-link の native-nav 抑止 (#779 WCAG 2.4.1) の喪失 — main.js skip-link click ハンドラの e.preventDefault() を除去 → native fragment 挙動で location.hash が '#main-content' に変わり router が非-'#/' hash を home 扱いで再描画 → 非 home ページ(#/projects)で「本文へスキップ」がユーザーを home へ誤遷移させる実バグ復活。main.js に preventDefault は 1 個(skip-link 専用)。既存 skip-link test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "main.js",
        "find": "e.preventDefault();",
        "replace": "/* preventDefault removed (#779 skip-link native-nav regression) */",
        "test": "Skip link moves focus to #main-content",
    },
    {
        "name": "behavior: quiz architecture 検索の stakeholder 被覆 (#285 visible-but-unsearchable) の喪失 — quiz-renderer.js _filterBy の return から `|| stakeholderMatch` を除去 → 画面に描画される stakeholder の name/quote (例 CTO の GAFA 発言) が検索対象外に戻り「見えるのに 0 件」drift が復活。既存 stakeholder-search test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": "return titleMatch || idMatch || contentMatch || situationMatch || questionMatch || stakeholderMatch;",
        "replace": "return titleMatch || idMatch || contentMatch || situationMatch || questionMatch;",
        "test": "matches stakeholder quote text",
    },
    {
        "name": "behavior: cross-tab storage 取り込みの schema guard (#295/#93) の喪失 — state.js storage リスナーの `if (incoming.schemaVersion !== SCHEMA_VERSION) return` を除去 → デプロイ跨ぎ (別バージョン) の異 schema / 欠損 store が別タブから来ると採用見送りされず validateAndNormalize を通って現タブの正常 state を上書き → own task 消失 (欠損時は FatalPage crash もありうる #93 class)。既存 foreign-schema-ignore test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "state.js",
        "find": "if (incoming.schemaVersion !== CONSTANTS.SCHEMA_VERSION) {return;}",
        "replace": "/* cross-tab schema guard removed (#295) */",
        "test": "foreign-schema/malformed store",
    },
    {
        "name": "behavior: quiz 検索の section 章タイトル被覆 (#296 visible-but-unsearchable) の喪失 — quiz-renderer.js _filterBy の `sectionMatch = !query || section.includes(query)` から section 一致項を除去 → 画面描画される section 章タイトル (例「第4章：可用性とFinOps…」) が検索対象外に戻り、タイトルにのみ含まれる語 (FinOps) で「見えるのに 0 件」drift が復活。既存 section-header-search test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": "const sectionMatch = !query || section.toLowerCase().includes(query);",
        "replace": "const sectionMatch = !query;",
        "test": "section-header (chapter title)",
    },
    {
        "name": "behavior: drawer の desktop リサイズ stuck-state guard の喪失 — mobile-drawer.js syncMobileDrawer の !isMobile 分岐で開放中 drawer を閉じる条件を無効化 → drawer 開放中に mobile→desktop へリサイズすると inline display:block が media query に勝って drawer/overlay が残り、__setAppInert(true)+__lockBodyScroll(true) のまま app が inert・scroll lock された stuck 状態 (topbar=display:none で menuBtn も隠れ overlay/Escape でしか脱出不能な broken UX) が復活。既存 stuck-state-guard test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "mobile-drawer.js",
        "find": "if (drawer && drawer.getAttribute('aria-hidden') === 'false') {",
        "replace": "if (false && drawer && drawer.getAttribute('aria-hidden') === 'false') {",
        "test": "resize to desktop",
    },
    {
        "name": "behavior: snapshot restore の正規化 (#561/#93/#295) の喪失 — settings-page.js restoreSnapshot の `State.set(Store.validateAndNormalize(snap.data))` を生 `State.set(snap.data)` に戻す → 旧版が保存した schema 不一致/projects・appsData 欠落 snapshot を復元すると renderer が state.projects.map 等で未定義参照し FatalPage crash (外部入力 ingestion は全て正規化を通せ class・importJSON は通すのに restore だけ生採用していた未被覆経路)。既存 snapshot-restore-normalize test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "settings-page.js",
        "find": "const _norm = Store.validateAndNormalize(snap.data);",
        "replace": "const _norm = snap.data;",
        "test": "Snapshot restore normalizes a foreign-schema/partial snapshot",
    },
    {
        "name": "behavior: store.js の非配列 ai.history ingestion guard (#568/#93) の喪失 — normalizeAppsData の `if (Array.isArray(data.ai?.history))` を旧 truthy 判定 `if (data.ai?.history)` に戻す → 別 schema/破損 store が ai.history を非配列 (文字列等) で持つと `.filter` が TypeError → validateAndNormalize 例外 → load()/cross-tab/import/snapshot-restore の全 ingestion 経路が FatalPage crash (normalizeAppsData の総関数契約違反)。既存 non-array-history-tolerance test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "store.js",
        "find": "if (Array.isArray(data.ai?.history)) {",
        "replace": "if (data.ai?.history) {",
        "test": "tolerates a non-array ai/pomodoro history",
    },
    {
        "name": "behavior: pomodoro 短休憩 onchange の idle 表示即更新 (#692 work との対称性) の喪失 — pomodoro-page.js short-break onchange の `remainingSec = settings.short * 60` を除去 → 短休憩モードで idle 中に短休憩時間を変えても表示中の remainingSec が古い duration のまま (start すると旧設定長で始まる)。従来 work だけこの即更新があり short/long は欠落していた asymmetry 実バグ。既存 break-symmetry test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "s.appsData.pomodoro.runtime.remainingSec = s.appsData.pomodoro.settings.short * 60;",
        "replace": "/* #692 short-break symmetry update removed */",
        "test": "break-duration change updates the idle timer",
    },
    {
        "name": "behavior: store.js の ingestion 側 ai.history prompt 文字列 bound (#230 class) の喪失 — normalizeAppsData の `prompt: String(h.prompt).slice(0, CONSTANTS.LIMITS.AI_MESSAGE)` から `.slice(0, AI_MESSAGE)` を外し生 `String(h.prompt)` に戻す → 巨大 prompt (20000 字) を含む store を load/import/cross-tab で取り込むと prompt が切り詰められず localStorage を bloat させる (write 側 apps.js は AI_MESSAGE で bound 済だが ingestion 側正規化が個々文字列長を bound しない未閉じ枝)。既存 length-bounded-on-normalize test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "store.js",
        "find": "prompt: String(h.prompt).slice(0, CONSTANTS.LIMITS.AI_MESSAGE),",
        "replace": "prompt: String(h.prompt),",
        "test": "AI history strings are length-bounded on normalize ingestion",
    },
    {
        "name": "behavior: drawer overlay(背景)クリック close の喪失 — main.js init の `#overlay` click→closeDrawer 直接リスナー配線を no-op function に差し替え → モバイルドロワーを開いたまま背景 overlay をクリックしても閉じない (モーダル標準の backdrop dismiss が壊れる)。Escape/nav-link close は別経路ゆえ独立に regress しうる。既存 overlay-backdrop-click test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "main.js",
        "find": "document.getElementById('overlay')?.addEventListener('click', closeDrawer);",
        "replace": "document.getElementById('overlay')?.addEventListener('click', function () {});",
        "test": "Mobile drawer closes on overlay (backdrop) click",
    },
    {
        "name": "behavior: relatedProjectIds 要素の String 正規化 (#782 id-coercion) の喪失 — store.js normalizeProject の `relatedProjectIds: (...).filter(Boolean).map(String).slice(0, 20)` から `.map(String)` を外す → import データが数値 id の relatedProjectIds を持つと、normalizeProject が id 自体は `String(raw.id)` で文字列化する一方 relatedProjectIds 要素は数値のまま残り、ProjectDetailPage の `relatedProjectIds.includes(p.id)` (p.id=文字列) と strict 不一致 → 関連プロジェクトリンクが silent に消える (#93/#295 の外部 ingestion 全経路正規化 class の relatedProjectIds 版)。既存 numeric-relatedProjectIds test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "store.js",
        "find": "relatedProjectIds: (Array.isArray(raw.relatedProjectIds) ? raw.relatedProjectIds : []).filter(Boolean).map(String).slice(0, 20),",
        "replace": "relatedProjectIds: (Array.isArray(raw.relatedProjectIds) ? raw.relatedProjectIds : []).filter(Boolean).slice(0, 20),",
        "test": "Imported numeric relatedProjectIds resolve to string ids",
    },
    {
        "name": "behavior: pomodoro reload auto-resume (#121 frozen-timer guard) の喪失 — pomodoro-page.js の `if (isActive && !pomodoroTimer) { startTimer(); }` 条件を `false && ...` で無効化 → reload 後に isActive=true (endAtMs>now を normalize が保持) でも interval が再起動されず、「一時停止ボタン表示だが countdown が frozen で complete() が永遠に発火しない」stuck 状態が復活 (pomodoroTimer は factory 変数ゆえ reload で null に戻り start() ボタン経由でしか起動されなかった元バグ)。既存 frozen-timer-guard test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "        if (rt.isActive && !pomodoroTimer) { startTimer(); }",
        "replace": "        if (false && rt.isActive && !pomodoroTimer) { startTimer(); }",
        "test": "resumes ticking after a reload mid-run",
    },
    {
        "name": "behavior: settings のプロジェクト並べ替え (moveProject up/down) の喪失 — settings-page.js moveProject の境界ガード `if (idx + dir < 0 || idx + dir >= s.projects.length) {return;}` を `if (true || ...)` で常に return させ swap を無効化 → ↑↓ ボタンを押しても順序が変わらず、並べ替えが localStorage に反映されない (State.update の swap が dead になる)。既存 reorder test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "settings-page.js",
        "find": "if (idx + dir < 0 || idx + dir >= s.projects.length) {return;}",
        "replace": "if (true || idx + dir < 0 || idx + dir >= s.projects.length) {return;}",
        "test": "Projects can be reordered with the up/down controls",
    },
    {
        "name": "behavior: default プロジェクト並べ替えの reload 永続 (mergeProjectsWithDefaults 順序保持) の喪失 — store.js の incoming 順優先 merge を default 定義順優先へ戻す (`for (const p of normalizedIncoming)` ループを `for (const d of normalizedDefaults)` へ) → settings ↑↓ で default project 同士を並べ替えても reload の normalize round-trip で元の定義順へ silent に戻る data-fidelity バグが復活 (user 追加 project は incoming 順 append で保持されるため default だけが失われる)。回帰 e2e に対応する mutation で safety-net を institutionalize する非 vacuity 検証",
        "file": ROOT / "js" / "store.js",
        "find": "        // 1. incoming(保存済み)順を保持 — default field は id で backfill し incoming の値を優先。\n        for (const p of normalizedIncoming) {\n            const d = defaultsById.get(p.id);\n            merged.push(d ? ({ ...d, ...p, id: d.id }) : p);\n            mergedIds.add(p.id);\n        }",
        "replace": "        // MUTATION: revert to default-definition order (drops reorder persistence).\n        for (const d of normalizedDefaults) {\n            const p = normalizedIncoming.find(x => x.id === d.id);\n            merged.push(p ? ({ ...d, ...p, id: d.id }) : d);\n            mergedIds.add(d.id);\n        }",
        "test": "Default project reorder persists across reload",
    },
    {
        "name": "behavior: TODO の「完了をクリア」ボタンの affordance ガード (disabled until a todo is completed) の喪失 — apps.js TodoPage の `disabled: !todos.some(t => t.completed)` を `disabled: false` にし常時活性化 → 完了 todo が 1 件も無い状態でもボタンが押せてしまい、空 filter 操作 (実質 no-op だが誤操作導線) を許す affordance 契約の喪失。既存 clear-completed-disabled test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "apps.js",
        "find": "disabled: !todos.some(t => t.completed),",
        "replace": "disabled: false,",
        "test": "Todo clear-completed button is disabled until a todo is completed",
    },
    {
        "name": "behavior: task カンバンの status 遷移 (moveStatus) の喪失 — apps.js moveStatus の `updateTask(task.id, { status: statuses[newIdx] })` を `statuses[idx]` に変え遷移先を現在 status に固定 → ←/→ ボタンを押してもカードが列を移動せず status が変わらない (backlog→in-progress→done の遷移が dead)。既存 kanban-move-persist test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "apps.js",
        "find": "                updateTask(task.id, { status: next });",
        "replace": "                updateTask(task.id, { status: statuses[idx] });",
        "test": "moves across kanban columns and persists the status",
    },
    {
        "name": "behavior: task の優先度フィルタ (getFilteredTasks) の喪失 — apps.js の `taskFilter.priority === 'all' || t.priority === taskFilter.priority` を `true` に変え全タスクを常に通す → 優先度フィルタを high/low に絞ってもボードが絞り込まれず全件表示のまま (フィルタが no-op 化)。既存 priority-filter-narrows test に対応する mutation が未登録だった safety-net 補強の非 vacuity 検証",
        "file": ROOT / "js" / "apps.js",
        "find": "taskFilter.priority === 'all' || t.priority === taskFilter.priority",
        "replace": "true",
        "test": "priority filter narrows the board by priority",
    },
    {
        "name": "behavior: pomodoro 完了時の history エントリの session type 記録の喪失 — pomodoro-page.js complete() の history push で `type: s.appsData.pomodoro.runtime.mode` を固定リテラル `type: 'break'` に変え、記録される session type が実 mode を反映しなくなる → 完了した work セッションが 'break' として履歴に残り、集計/表示が誤る。新設 completion-history-record test に対応する mutation で safety-net を institutionalize する非 vacuity 検証",
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "type: s.appsData.pomodoro.runtime.mode,",
        "replace": "type: 'break',",
        "test": "records a history entry with the session type and duration",
    },
    {
        "name": "behavior: projectPrefs.hiddenIds の normalize round-trip 保持の喪失 — store.js validateAndNormalize の projectPrefs 読み戻しガード `if (data.projectPrefs && ... Array.isArray(data.projectPrefs.hiddenIds))` を `if (false && ...)` で無効化 → reload の normalize で hiddenIds が drop され、非表示にしたプロジェクトが公開一覧へ silent に復活する (#294/#568/#684/#871 の persist-drift class の projectPrefs 版)。新設 hidden-persist test に対応する mutation で safety-net を institutionalize する非 vacuity 検証",
        "file": ROOT / "js" / "store.js",
        "find": "if (data.projectPrefs && typeof data.projectPrefs === 'object' && Array.isArray(data.projectPrefs.hiddenIds)) {",
        "replace": "if (false && data.projectPrefs && typeof data.projectPrefs === 'object' && Array.isArray(data.projectPrefs.hiddenIds)) {",
        "test": "Hidden project stays hidden on the public list across reload",
    },
    {
        "name": "a11y: ProjectsPage の検索 landmark (role='search') の喪失 — projects-page.js の検索 wrapper から `role: 'search'` を外す → 検索入力が ARIA search landmark でなくなり、SR ユーザーが landmark ナビゲーションで検索領域へジャンプできなくなる (WCAG 1.3.1・ARIA APG search landmark の退行)。新設 search-landmark test に対応する mutation で safety-net を institutionalize する非 vacuity 検証",
        "file": ROOT / "js" / "projects-page.js",
        "find": "h('div', { class: 'relative', role: 'search' },",
        "replace": "h('div', { class: 'relative' },",
        "test": "Projects search is exposed as an ARIA search landmark",
    },
    {
        "name": "a11y: QuizPage の検索 landmark (role='search') の喪失 — quiz-renderer.js の検索 wrapper から `role: \"search\"` を外す → 検索入力が ARIA search landmark でなくなり SR ユーザーが landmark ナビで検索領域へジャンプできなくなる (WCAG 1.3.1・ARIA APG・ProjectsPage #879 と同型)。新設 quiz-search-landmark test に対応する mutation で safety-net を institutionalize する非 vacuity 検証",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": "h(\"div\", { class: \"relative\", role: \"search\" },",
        "replace": "h(\"div\", { class: \"relative\" },",
        "test": "Quiz search is exposed as an ARIA search landmark",
    },
    {
        "name": "a11y: ProjectsPage 件数表示の live region (WCAG 4.1.3) の喪失 — projects-page.js の countDisplay から `role: 'status', 'aria-live': 'polite'` を外す → 検索/カテゴリ絞り込みで `合計 N 件` が変わっても SR ユーザーへ通知されなくなる (非 0 件の件数変化が silent に戻る Status Messages 退行)。新設 count-live-region test に対応する mutation で safety-net を institutionalize する非 vacuity 検証",
        "file": ROOT / "js" / "projects-page.js",
        "find": "countDisplay = h('p', { class: 'text-muted', role: 'status', 'aria-live': 'polite' }, '')",
        "replace": "countDisplay = h('p', { class: 'text-muted' }, '')",
        "test": "Projects result count is an aria-live status region",
    },
    {
        "name": "a11y: quiz 模範解答フォームの email 必須マーク (WCAG 3.3.2) の喪失 — quiz-renderer.js emailInput の `'aria-required': 'true'` を外す → submit の JS バリデーションで必須の メールアドレスが SR ユーザーに必須と露出されず、送信してエラー Toast が出るまで必須と分からない (Labels or Instructions の退行)。新設 form-required test に対応する mutation で safety-net を institutionalize する非 vacuity 検証",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": "'aria-label': 'メールアドレス', 'aria-required': 'true' }",
        "replace": "'aria-label': 'メールアドレス' }",
        "test": "Quiz contact form marks name and email as aria-required",
    },
    {
        "name": "behavior: 自動推薦の明示-related 除外の喪失 — store.js autoRelatedCandidates の候補 filter から `&& !fixed.has(p.id)` を外す → target.relatedProjectIds に既にある明示 related が推薦候補へ戻り、プロジェクト詳細の「関連プロジェクト」節と「おすすめ（自動）」節に同じプロジェクトが二重表示される (推薦枠 8 件が既知の関連で埋まり新規発見価値が失われる)。新設 auto-recommendation exclusion test に対応する mutation で safety-net を institutionalize する非 vacuity 検証",
        "file": ROOT / "js" / "store.js",
        "find": ".filter(p => p && p.id && p.id !== target.id && !fixed.has(p.id))",
        "replace": ".filter(p => p && p.id && p.id !== target.id)",
        "test": "Auto-recommendations exclude self and explicitly-related projects",
    },
    {
        "name": "behavior: hidden project が home の注目枠へ漏れる — home-page.js の featured 選定を visibleProjects から素の state.projects へ戻す → 非表示にした default project (削除不可＝非表示が唯一の非公開手段) がトップページ最上位の注目枠に出続け、詳細/デモ導線も残る (公開一覧からは消えているため owner は気づけない listing 面 mesh の漏れ)",
        "file": ROOT / "js" / "home-page.js",
        "find": "const featured = visibleProjects.find(p => p.demoRoute === 'task') || visibleProjects[0] || null;",
        "replace": "const featured = state.projects.find(p => p.demoRoute === 'task') || state.projects[0] || null;",
        "test": "Hidden project disappears from home featured",
    },
    {
        "name": "behavior: hidden project が詳細ページの推薦へ漏れる — project-detail-page.js の related 算出を listable(非表示除外済) から素の state.projects へ戻す → 非表示にしたプロジェクトが「関連プロジェクト」カードとして出続け、そこから詳細ページへ到達できる (listing 面 mesh の漏れ)",
        "file": ROOT / "js" / "project-detail-page.js",
        "find": "const related = listable.filter(p =>",
        "replace": "const related = state.projects.filter(p =>",
        "test": "Hidden project disappears from home featured",
    },
    {
        "name": "behavior: hidden project が Cmd+K 候補へ漏れる — command-palette.js の候補 filter から `&& !_hidden.has(String(p.id))` を落とす → 公開一覧から消したプロジェクトが palette で検索・到達でき、非表示が「一覧だけの部分的な隠蔽」に退行する (listing 面 mesh の漏れ)",
        "file": ROOT / "js" / "command-palette.js",
        "find": " && !_hidden.has(String(p.id))",
        "replace": "",
        "test": "Hidden project disappears from home featured",
    },
    {
        "name": "behavior: hiring-risk CTA が AWS フォールバックへ着地 — quiz-renderer.js の QUIZ_TITLES から 'pm' キーを rename → URL は #/quiz?type=pm のままなのに `|| QUIZ_DATA_MAP.aws` が効き、「PM問題集を見る」ボタンから AWS 問題集が黙って描画される silent wrong-content (throw も console error も無く、直接 URL で開く既存 quiz e2e も CTA 経路を通らないため素通りする)。Check 401a が静的に守る面の behavioral 対",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": "            pm: 'PM問題集',",
        "replace": "            pmX: 'PM問題集',",
        "test": "Hiring-risk CTAs land on the quiz named on the button",
    },
    {
        "name": "behavior: sr-only AIO entity anchor の silent removal — index.html の <div class=\"sr-only\" id=\"aio-footer-entity\"> の id を rename → 著作権/entity/canonical ブロックが DOM から消える。旧テストは `if (await entity.count())` の skip-on-missing で黙って PASS する vacuous gate だった (実測で確認し presence 必須へ是正)。是正版が実際に RED になることの検証",
        "file": ROOT / "index.html",
        "find": '<div class="sr-only" id="aio-footer-entity" aria-hidden="true">',
        "replace": '<div class="sr-only" id="aio-footer-entity-renamed" aria-hidden="true">',
        "test": "sr-only content (route announcer + AIO entity anchor) stays visually hidden",
    },
    {
        "name": "behavior: quiz 検索語の種別スコープ喪失 — quiz-renderer.js の initialSearch を quizSearchType 一致条件から素の quizSearch へ戻す → ある種別で検索したまま別種別へ切り替えると語が持ち越され、切替先が「一致する問題は見つかりませんでした」の空ページになる (sidebar の種別リンク / hiring-risk の CTA はどちらも主要導線)。実測で architecture の 'CAP' が PM へ持ち越され PM が 0 件表示になっていた実バグの回帰防止",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": "        const initialSearch = (state.appsData.quizSearchType === quizType)\n            ? (state.appsData.quizSearch || \"\")\n            : \"\";",
        "replace": "        const initialSearch = state.appsData.quizSearch || \"\";",
        "test": "Quiz search term does not leak across quiz types",
    },
    {
        "name": "behavior: プロジェクト詳細のデモ起動導線が壊れる — project-detail-page.js の「アプリを起動」を apps/<demoRoute> から誤 route (projects) へ差し替え → 閲覧者が作品を触るまでの主要ジャーニーが切れる。Check 136 は demoRoute 値が router whitelist にあることしか見ず、ボタンが実際に遷移してアプリが描画されるかは未被覆だった",
        "file": ROOT / "js" / "project-detail-page.js",
        "find": "onclick: () => Router.navigate(`apps/${project.demoRoute}`)",
        "replace": "onclick: () => Router.navigate(`projects`)",
        "test": "Project demo launch buttons open the embedded app",
    },
    {
        "name": "resilience: crypto.randomUUID 不在環境で項目追加が壊れる — js/pure-utils.js の generateId のフォールバック本体 (Math.random ベースの RFC 4122 テンプレート) を潰す → randomUUID はセキュアコンテキスト限定 API ゆえ http:// の LAN プレビュー (PC の http-server をスマホから開く等) で undefined になり、その閲覧経路でだけ項目追加が例外になる。なお feature-detection (typeof crypto...) を外すだけでは外側の try/catch が TypeError を吸収してフォールバックが働くため mutation として no-op = vacuous になる (実測済)。フォールバック本体を潰す形が正しい非 vacuity 検証",
        "file": ROOT / "js" / "pure-utils.js",
        "find": "    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {",
        "replace": "    return crypto.randomUUID();\n    // eslint-disable-next-line no-unreachable\n    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {",
        "test": "Item creation still works when crypto.randomUUID is unavailable",
    },
    {
        "name": "resilience: localStorage 不在環境での白画面化 — js/storage.js の get() から try/catch を外し素の localStorage アクセスへ → プライベートブラウジング等で localStorage アクセス自体が SecurityError を投げる環境の全ユーザーがコンテンツ非描画 (白画面) になる。quota 超過 (書き込み失敗) とは別クラスの堅牢性の回帰防止",
        "file": ROOT / "js" / "storage.js",
        "find": "        try {\n            return localStorage.getItem(key);",
        "replace": "        {\n            return localStorage.getItem(key);",
        "test": "SPA still renders when localStorage access itself throws",
    },
    {
        "name": "a11y: settings 追加フォームの検証フィールド特定喪失 — settings-page.js の addProjectManual から aria-invalid の付与と focus 移動を除去 → SR 利用者は Toast のエラーだけ聞かされ「どの入力が不正か」を判別できない (WCAG 3.3.1 / 2.4.3・quiz フォーム #913 と同 class の残り 1 面)",
        "file": ROOT / "js" / "settings-page.js",
        "find": "                if (nameEl) { nameEl.setAttribute('aria-invalid', 'true'); nameEl.focus(); }",
        "replace": "",
        "test": "Settings add-project form marks the empty name aria-invalid",
    },
    {
        "name": "a11y: quiz フォーム検証のフィールド特定喪失 — quiz-renderer.js の送信ハンドラから最初の不正フィールドへの focus 移動を除去 → SR 利用者は Toast のエラーだけ聞かされ「どのフィールドが不正か」を自力で探す羽目になる (WCAG 3.3.1 Error Identification / 2.4.3)。aria-invalid + focus 移動による識別の回帰防止",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": "                    (!name ? nameInput : emailInput).focus();",
        "replace": "",
        "test": "Quiz contact form marks the offending field aria-invalid",
    },
    {
        "name": "a11y: 分担表の ARIA table 構造の喪失 — pages.js splitRow のカテゴリセルから `role: 'rowheader'` を外す → 行見出しが失われ、SR はセル読み上げ時にどのカテゴリ行かの文脈を得られなくなる (分担表は div グリッドで table 要素を持たないため ARIA role が唯一の構造露出手段・WCAG 1.3.1)。axe は role の妥当性しか見ず role 除去は違反にならないため behavior e2e が唯一の gate。新設 table-semantics test の非 vacuity 検証",
        "file": ROOT / "js" / "pages.js",
        "find": "class: 'cell-category', role: 'rowheader'",
        "replace": "class: 'cell-category'",
        "test": "Role-split division table exposes ARIA table semantics",
    },
    {
        "name": "behavior: 検索×カテゴリの AND 合成の喪失 — projects-page.js の getFilteredProjects で category 絞り込みを「検索語が無いときだけ」に狭める → カテゴリ選択中に検索するとカテゴリが無視され、選択中の <select> 表示と実際の結果が desync する (control↔filter desync・#350 と同族)。cat 単独 / q 単独の既存テストは通り続けるため、併用を検証する新テストだけが捕捉できる",
        "file": ROOT / "js" / "projects-page.js",
        "find": "            if (cat !== 'All') {\n                list = list.filter(p => p.category === cat);",
        "replace": "            if (cat !== 'All' && !q) {\n                list = list.filter(p => p.category === cat);",
        "test": "Search and category filters compose",
    },
    {
        "name": "behavior: notes editor の silent data-loss 再混入 — apps.js の textarea から maxlength を外す → 保存側は LIMITS.NOTES_TEXT で slice するのに UI は無制限に受け付け、超過分は textarea にもライブプレビューにも表示され続けたまま保存されない (リロードして初めて消失が判明する silent data-loss)。UI 上限と永続化上限の一致 (Check 410 の behavioral 面) の回帰防止",
        "file": ROOT / "js" / "apps.js",
        "find": "            maxlength: CONSTANTS.LIMITS.NOTES_TEXT,",
        "replace": "",
        "test": "Notes editor cannot hold more text than it persists",
    },
    {
        "name": "behavior: quiz の外部入力 ?type= がプロトタイプ継承キーで crash する回帰 — quiz-renderer.js の hasOwnProperty ガードを素の `MAP[type] || fallback` へ戻す → 'constructor' 等は truthy な非 config 値 (Object コンストラクタ) を返して fallback を素通りし、sourceData が undefined のまま Object.keys(undefined) が throw → FatalPage でページ全体が表示不能になる (実測)。外部入力を object 添字に使う際の own-key 検証の回帰防止",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": "        const resolvedType = Object.prototype.hasOwnProperty.call(QUIZ_TITLES, quizType)\n            ? quizType\n            : 'aws';",
        "replace": "        const resolvedType = QUIZ_TITLES[quizType] ? quizType : 'aws';",
        "test": "prototype-inherited",
    },
    {
        "name": "behavior: route-render gate 自体の非 vacuity — main.js render の case 'role-split' から page = RoleSplitPage() の代入を落とす (葉抽出で配線を落とす回帰 class) → page が undefined のまま appendChild され TypeError で #content 空 + pageerror。全ルートの描画健全性を守る中核 gate (security-proxy の ALL_ROUTES loop) が実際に RED になることの検証。この loop は題名が backtick テンプレートで、Check 379/397 が引用符リテラルしか parse しなかった間は mutation を登録できなかった",
        "file": ROOT / "main.js",
        "find": "                        case 'role-split':\n                            page = RoleSplitPage();\n",
        "replace": "                        case 'role-split':\n",
        "test": "renders without runtime errors",
    },
    {
        "name": "a11y: quiz 章アイコンの装飾絵文字が SR に読み上げられる回帰 — quiz-renderer.js の quiz-section-icon から aria-hidden を外す → アクセシビリティツリーに 🏛️ 等が露出し、SR は全章で章題の前に「classical building」等の無意味な語を読む (WCAG 1.1.1・axe は装飾テキスト露出をルール化しないため behavior e2e が唯一の gate)",
        "file": ROOT / "js" / "quiz-renderer.js",
        "find": "{ class: \"quiz-section-icon\", 'aria-hidden': 'true' }, icons[sIdx]",
        "replace": "{ class: \"quiz-section-icon\" }, icons[sIdx]",
        "test": "decorative emoji are hidden from the accessibility tree",
    },
    {
        "name": "behavior: WebMCP の DOM 抽出契約の喪失 — js/pages.js splitRow の human 列から機械向けフック data-ai-role を外す → WebMCP ツールが役割分担表の human/ai を区別して抽出できなくなる (agentic 面の contract 破壊)",
        "file": ROOT / "js" / "pages.js",
        "find": "class: 'cell-human', role: 'cell', 'data-ai-role': 'human'",
        "replace": "class: 'cell-human', role: 'cell'",
        "test": "WebMCP role-split extraction selector resolves",
    },
    {
        "name": "behavior: ルート追従 JSON-LD の silent 喪失 — main.js の _installSemanticDriftGuard から MutationObserver の observe 配線を落とす → script[data-ld='dynamic-route'] がルート遷移で更新されなくなり、AI クローラは初期状態の structured data しか見なくなる。視覚に一切出ないため screenshot も他の e2e も consistency も捕捉できなかった silent-critical な AIO 配線 (#133/#134/#135 と同 class) の回帰防止",
        "file": ROOT / "main.js",
        "find": "                    _observer.observe(contentEl, { childList: true, subtree: false });",
        "replace": "                    void _observer;",
        "test": "dynamic JSON-LD is injected and tracks the current route",
    },
    {
        "name": "behavior: aio-guard の自己修復が働かなくなる回帰 — aio-guard.js の MutationObserver 監視対象を document.body から document.head へ変える → hidden な AIO アンカーが削除されても復元されない。script 配線は残るため Check 133 は緑のまま (= 「配線はあるが機能しない」class・#929 WebMCP と同じレンズ)。視覚に出ない要素ゆえ screenshot も他の e2e も気付けない",
        "file": ROOT / "aio-guard.js",
        "find": "        _observer.observe(document.body, { childList: true, subtree: true });\n    }\n\n    // Attach to DOMContentLoaded",
        "replace": "        _observer.observe(document.head, { childList: true, subtree: true });\n    }\n\n    // Attach to DOMContentLoaded",
        "test": "aio-guard restores the hidden AIO anchor after it is removed",
    },
    {
        "name": "behavior: cross-app 状態の clobber — store.js normalizeAppsData の notes 読み戻しを落とす → task/todo は残るのに notes だけリロードで消える。単体テストは各アプリを独立に見るため、4 アプリを 1 セッションで触ってから 1 回リロードする統合 e2e だけがこの「片方の経路だけ巻き戻る」class を捕捉する (静的面は Check 373)",
        "file": ROOT / "js" / "store.js",
        "find": "            result.notes = data.notes.slice(0, CONSTANTS.LIMITS.NOTES_TEXT);",
        "replace": "            result.notes = '';",
        "test": "four apps in one session all survives a single reload",
    },
    {
        "name": "behavior: cross-tab 更新が編集中の入力を破壊する回帰 — state.js の storage リスナーから編集中の採用延期ガードを外す → 別タブがタスクを 1 件追加しただけで、こちらのタブで書きかけの notes が巻き戻り focus が body へ落ちる (#258 の『再描画が focused input を破棄する』class の外部イベント起点版・実測済)",
        "file": ROOT / "js" / "state.js",
        "find": "                    if (_deferIfEditing(incoming)) {return;}",
        "replace": "                    if (false) {return;}",
        "test": "Cross-tab update does not destroy an in-progress edit",
    },
    {
        "name": "behavior: 二重モーダル (drawer + command palette) の再発 — command-palette.js の open() から closeDrawer() 呼び出しを除去 → mobile drawer が開いたまま Cmd/Ctrl+K を押すと aria-modal='true' の領域が 2 つ同時に有効になり、SR にはどちらが現在のモーダルか判別できない。さらに両者の Escape ハンドラが同じ document keydown で走るため Escape 1 回で両方閉じる (#262 の二重発火と同族・実測済)",
        "file": ROOT / "js" / "command-palette.js",
        "find": "        if (typeof closeDrawer === 'function') { closeDrawer(); }\n",
        "replace": "",
        "test": "Opening the command palette closes the mobile drawer",
    },
    {
        "name": "behavior: 二重モーダルの逆方向 — mobile-drawer.js の openDrawer() から closePalette() 呼び出しを除去 → command palette 表示中に menuBtn (topbar は #app の inert 対象外ゆえクリック可能) を押すと drawer が重なって開き aria-modal='true' が 2 つ同時に有効になる。片方向だけ塞ぐと『1 ケースだけ処理して他を忘れる』非対称バグとして残る class の回帰防止",
        "file": ROOT / "js" / "mobile-drawer.js",
        "find": "        if (typeof closePalette === 'function') { closePalette(); }\n",
        "replace": "",
        "test": "Opening the drawer closes the command palette",
    },
    {
        "name": "a11y: palette 表示中の背景 inert の喪失 — command-palette.js の open() から setAppInert(true) を除去 → 背景 (#app) が AT からもポインタからも生きたままになり、aria-modal='true' の解釈が揺れる AT では背景コンテンツを読み進められる。drawer は同じ状況で inert 化しており、**同じモーダルなのに背景の扱いが非対称**だった class の回帰防止",
        "file": ROOT / "js" / "command-palette.js",
        "find": "        if (typeof setAppInert === 'function') { setAppInert(true); }\n",
        "replace": "",
        "test": "Command palette makes the background inert while open",
    },
    {
        "name": "behavior: closeDrawer の idempotency ガード喪失による scroll-clobber — mobile-drawer.js の closeDrawer から『閉じているなら早期 return』を外す → 末尾の __lockBodyScroll(false) が window.scrollTo(0, __drawerScrollY=0) を実行し、**閉じている drawer を閉じるだけでページ先頭へ飛ぶ**。二重モーダル防止で palette が open 時に無条件 closeDrawer() を呼ぶため、スクロール中に Cmd/Ctrl+K を押すと先頭ジャンプになる (#297 の openDrawer 側ガードの対・実測済)",
        "file": ROOT / "js" / "mobile-drawer.js",
        "find": "        if (drawer.getAttribute('aria-hidden') !== 'false') { return; }\n",
        "replace": "",
        "test": "Opening and closing the command palette preserves the scroll position",
    },
    {
        "name": "behavior: フィルタ操作が履歴を汚す回帰 — projects-page.js の syncURL を Router.replaceSilently から Router.navigate へ変える → 検索語 1 文字ごとに history entry が積まれ、3 文字打つと『戻る』を 3 回押さないとページを離れられない典型的な SPA 退行になる (replaceSilently は history.replaceState でこれを防いでいる)",
        "file": ROOT / "js" / "projects-page.js",
        "find": "Router.replaceSilently('projects' + ",
        "replace": "Router.navigate('projects' + ",
        "test": "Browser back/forward moves between routes and filtering does not pollute history",
    },
    {
        "name": "behavior: 詳細ページの『一覧に戻る』が絞り込みを捨てる回帰 — project-detail-page.js の戻り先を Router.getLastListPath() から 'projects' ハードコードへ戻す → ?q= / ?cat= を落として全件表示へ戻る。ブラウザの Back は履歴の query 付き URL へ復帰するため『同じ意味の操作なのに結果が違う』不整合になる (実測: 1 件に絞って詳細を開き in-page back → 18 件)",
        "file": ROOT / "js" / "project-detail-page.js",
        # NOTE: `getLastListPath` は **2 箇所** にある (not-found 分岐の「一覧へ戻る」と、
        #   詳細ページ本体の「← 一覧に戻る」)。mutation_probe は replace(find, replace, 1) ＝
        #   **先頭 1 件しか置換しない**ため、素の式を find にすると not-found 分岐だけが壊れ、
        #   テストが通る経路には当たらず **silent SURVIVED** になる (週次 probe が検出)。
        #   実ボタン側だけに一意に当たるよう、直前の class 属性まで含めて anchor する。
        "find": "                    class: 'btn btn-ghost btn-sm mb-4',\n                    onclick: () => Router.navigate(Router.getLastListPath ? Router.getLastListPath() : 'projects')",
        "replace": "                    class: 'btn btn-ghost btn-sm mb-4',\n                    onclick: () => Router.navigate('projects')",
        "test": "In-page \"back to list\" preserves the active filter",
    },
    {
        "name": "a11y: topbar テーマボタンのラベル同期の喪失 — theme.js apply() から #themeBtnTop の aria-label 更新を除去 → mobile 利用者には『テーマを切り替える（現在: …）』が初期値のまま固定され、現在テーマが SR に露出しなくなる (WCAG 4.1.2)。sidebar 側は render 毎の再構築という **別機構** で更新されるため、desktop 前提の既存テストでは検出できなかった (実測: 削除しても既存 10 件は全緑) 未被覆面の回帰防止",
        "file": ROOT / "js" / "theme.js",
        "find": "            topBtn.setAttribute('aria-label', themeToggleAriaLabel(theme));",
        "replace": "            void themeToggleAriaLabel;",
        "test": "Topbar theme button exposes the current theme in its label on mobile",
    },
    {
        "name": "behavior: スナップショット削除の確認ガード喪失 — settings-page.js clearSnapshot から confirm を除去 → ユーザー唯一の復元点が無確認で消える。プロジェクト 1 件の削除と全リセットは confirm を通すのに、より影響の大きいスナップショット削除だけ無確認だった非対称 (CLAUDE.md §7 の反復 class) の回帰防止",
        "file": ROOT / "js" / "settings-page.js",
        "find": "            if (!confirm(_at",
        "replace": "            if (false && !confirm(_at",
        "test": "Deleting the snapshot asks for confirmation",
    },
    {
        "name": "behavior: タスク 0 件の説明表示の喪失 — apps.js の空状態ブロックを無効化 → 優先度フィルタで 0 件になっても 3 列に『0』が並ぶだけで、フィルタが隠しているのか本当に空なのか判別できない状態へ戻る (TodoPage は同じ状況でメッセージを出しており task 側だけ欠けていた非対称) の回帰防止",
        "file": ROOT / "js" / "apps.js",
        "find": "            if (allTasks.length === 0) {",
        "replace": "            if (false) {",
        "test": "Task board explains why it is empty",
    },
    {
        "name": "behavior: ポモドーロ当日要約の集計誤り — pomodoro-page.js の当日フィルタ (timestamp >= 当日 0 時) を外す → 昨日以前の完了セッションまで『今日の実績』に数え、利用者が今日の進捗を誤認する。記録しているのに画面に出していなかった history を要約表示した増分の回帰防止",
        "file": ROOT / "js" / "pomodoro-page.js",
        "find": "e.type === 'work' && e.timestamp >= _start).length",
        "replace": "e.type === 'work').length",
        "test": "Pomodoro shows today",
    },
    {
        "name": "behavior: 320px 幅の横あふれ再発 — style.css の mobile media query から `max-width: 100%` を外す → .app が column flex になった際に .main-content の左右 auto margin が cross 軸 auto margin となり stretch が無効化され、fit-content が min-content を下回れず item が viewport より広くなる (WCAG 1.4.10 違反・実測 role-split +51px)。screenshot は 1280x720 clip でこの media query に到達しないため、捕捉できるのは behavior test だけ",
        "file": ROOT / "style.css",
        "find": "は非到達。 */\n                max-width: 100%;",
        "replace": "は非到達。 */",
        "test": "WCAG 1.4.10: 320px 幅でどのルートも横スクロールしない",
    },
    {
        "name": "behavior: profile 正規化の型ガード喪失 — store.js の safeStr を旧実装 `String(v || fallback)` に戻す → `[]` や `{}` のような truthy な非文字列が `||` を素通りし String([]) === '' でフィールドが空になる。email が空になると ContactPage から宛先表示が消え「メールを作成」が宛先の無い mailto: を開く (fatal を出さないので ErrorBoundary にも掛からず、視覚 baseline は ADVISORY ゆえ behavior test 以外に捕捉層が無い)",
        "file": ROOT / "js" / "store.js",
        "find": "        const s = (v && cand.trim() !== '') ? cand : String(fallback || '');",
        "replace": "        const s = String(v || fallback || '');",
        "test": "Hostile profile import: a truthy non-string must not blank a field",
    },
    {
        "name": "behavior: project 正規化の型ガード喪失 — store.js の name を旧実装 `String(raw.name || 'Untitled')` に戻す → `{}` が truthy なので fallback が働かず \"[object Object]\" が一覧カードと詳細ページへそのまま描画される (実測で一覧 3 箇所 / 詳細 4 箇所)。fatal を出さないので ErrorBoundary に掛からず、視覚 baseline は ADVISORY ゆえ behavior test 以外に捕捉層が無い",
        "file": ROOT / "js" / "store.js",
        "find": "            name: safeStr(raw.name, 'Untitled', CONSTANTS.LIMITS.PROJECT_NAME),",
        "replace": "            name: String(raw.name || 'Untitled').slice(0, CONSTANTS.LIMITS.PROJECT_NAME),",
        "test": "Hostile project import: non-string fields must not render as [object Object]",
    },
    {
        "name": "behavior: appsData の必須テキスト型ガード喪失 — normalizeAppsData の task filter を `isText(t.title)` から旧 `t.title` へ戻す → `{}` は truthy なので entry が落ちず、本文の無い空カードとして残る (旧実装ではさらに String(t.title) が \"[object Object]\" を描画していた)。NOTE: 描画側の検査だけでは捕捉できず (safeStr により空文字になるため)、永続化された appsData に壊れた entry が残っていないことの検査が本 mutation を捕捉する",
        "file": ROOT / "js" / "store.js",
        "find": "                .filter(t => t && isText(t.title))",
        "replace": "                .filter(t => t && t.title)",
        "test": "Hostile appsData import: non-string title/text must not render as [object Object]",
    },
    {
        "name": "behavior: router の slug decode ガード喪失 — js/router.js の decodeURIComponent から try/catch を外す → 不正な percent-encoding を含む slug (`#/projects/%E0%A4%A`) で URIError が route 解決中に throw し、graceful な「見つかりません」ではなく ErrorBoundary 送りになる。hash は利用者が直接編集でき古いブックマークからも来る最外周の入力面で、SW の normalizePath (#270) と同じ「全リクエストを触る hot path の decode は try/catch 必須」class のルータ面",
        "file": ROOT / "js" / "router.js",
        "find": "                    try {\n                        route.params.slug = decodeURIComponent(parts[1]);\n                    } catch (_) {\n                        route.params.slug = parts[1];\n                    }",
        "replace": "                    route.params.slug = decodeURIComponent(parts[1]);",
        "test": "Router tolerates a malformed percent-encoded project slug",
    },
    {
        "name": "behavior: ブランド primary の WCAG 1.4.3 (AA) 退行 — style.css の --color-primary-rgb を旧値 rgb(99,102,241) へ戻す → 白背景に対するコントラスト比が 4.467 となり要求 4.5:1 を下回る (1 ルートあたり 15〜59 ノードが axe の color-contrast violation)。axe の color-contrast は serious だが本リポジトリの a11y ゲートは critical 限定のため素通りする = トークン契約の e2e が唯一の捕捉層",
        "file": ROOT / "style.css",
        "find": "            --color-primary-rgb: 98, 101, 240;\n            /* Indigo (値の根拠は :root 側のコメント参照・WCAG 1.4.3 AA) */",
        "replace": "            --color-primary-rgb: 99, 102, 241;\n            /* Indigo (値の根拠は :root 側のコメント参照・WCAG 1.4.3 AA) */",
        "test": "WCAG 1.4.3: 各ブランドの primary は白に対し 4.5:1 以上",
    },
    {
        "name": "behavior: ダークテーマの適用が壊れる — style.css の [data-theme=\"system\"] セレクタを無効化 → OS がダークでもライトのまま描画される。ダーク走査の a11y テストは「実際にダークになっているか」を先に検査するので、壊れると『ダークを検査したつもりでライトを検査していた』vacuous な結果ではなく明示的な RED になる",
        "file": ROOT / "style.css",
        "find": "            [data-theme=\"system\"] {",
        "replace": "            [data-theme=\"system-DISABLED\"] {",
        "test": "a11y axe: ダークテーマの全ルートに render-neutral critical 違反が無い",
    },
    {
        "name": "behavior: 初回ロードの projects 要素フィルタ喪失 — mergeProjectsWithDefaults から `.filter(p => p && typeof p === 'object')` を外す → localStorage に `projects: [null, 0, 'x']` を持つ store (parse でき schemaVersion も一致するので **実際に adopt される**) で normalizeProject が null を dereference し boot が壊れる。import 経路 (#968-#970) とは別の入口 (JSON.parse・schemaVersion gate・boot 時 State.set) を通る面",
        "file": ROOT / "js" / "store.js",
        "find": "        const normalizedIncoming = (Array.isArray(incomingProjects) ? incomingProjects : [])\n            .filter(p => p && typeof p === 'object')",
        "replace": "        const normalizedIncoming = (Array.isArray(incomingProjects) ? incomingProjects : [])",
        "test": "Hostile-but-adoptable localStorage: every field type survives the boot path",
    },
    {
        "name": "behavior: cross-app — 全リセットが稼働中ポモドーロを止めない — settings-page.js の resetData を appsData 温存版へ改変 → 永続化された runtime.isActive が true のまま残り、『動いているのに endAtMs は初期化済み』の矛盾状態になる (走り続けた interval が初期化を上書きしうる)。ポモドーロは他ページに居ても走り続ける唯一の機能で、別アプリからの破壊的操作と交差する面。fatal を出さずに壊れるため behavior test 以外に捕捉層が無い",
        "file": ROOT / "js" / "settings-page.js",
        "find": "            State.set(Store.createDefaultStore());",
        "replace": "            State.set({ ...Store.createDefaultStore(), appsData: State.get().appsData });",
        "test": "Full reset stops a running pomodoro timer (cross-app interaction)",
    },
    {
        "name": "window.addEventListener が直接上書きされる — main.js は listener registry を **prototype/API を書き換えずに**実装している (書き換えると DOM の意味論がサイト内だけ非標準になり、他コードや e2e の診断が壊れる・#963 で perf-guards の style hook を除去したのと同じ理由)。この不変条件はどの静的 Check も見ておらず、この security test だけが捕捉層",
        "file": ROOT / "main.js",
        "find": "        (function _installEventListenerRegistry() {",
        "replace": "        (function _installEventListenerRegistry() {\n            window.addEventListener = window.addEventListener.bind(window);",
        "test": "5-layer proxy: window.addEventListener is not directly overwritten",
    },
    {
        "name": "home の注目枠が非表示を無視して戻る (#886) — 既定プロジェクトは削除できず「非表示」が唯一の非公開手段なので、隠したはずのものがトップの注目枠に出続けるのは **公開/非公開の意思**の喪失。ProjectsPage だけ塞いでも home が漏れる listing mesh の一角",
        "file": ROOT / "js" / "home-page.js",
        "find": "        const visibleProjects = state.projects.filter(p => !hiddenIds.has(String(p.id)));",
        "replace": "        const visibleProjects = state.projects;",
        "test": "非表示は home と Cmd+K にも効き、解除で両方に戻る",
    },
    {
        "name": "Cmd+K 候補が非表示を無視して戻る (#886) — home とは**別 file の別フィルタ**なので独立に腐る。パレットは全ルートから開ける横断導線ゆえ、ここが漏れると非表示にしたプロジェクトへ誰でも到達できてしまう",
        "file": ROOT / "js" / "command-palette.js",
        "find": "            .filter(p => p && p.slug && p.name && !_hidden.has(String(p.id)))",
        "replace": "            .filter(p => p && p.slug && p.name)",
        "test": "非表示は home と Cmd+K にも効き、解除で両方に戻る",
    },
    {
        "name": "role-split Speakable が dead class へ戻る — `#role-split-table` (実在 id) を `.role-split-table` (どこにも無い class) へ戻すと、音声アシスタントに『この表を読め』と指しながら **解決先が存在しない**。#929 で実際に見つかった「機械向け宣言が一度も成功していなかった」class そのもので、視覚にも behavior にも一切出ない",
        "file": ROOT / "js" / "meta-management.js",
        "find": "            'role-split':  ['h1', '#role-split-table', '[data-speakable]', '.sr-only'],",
        "replace": "            'role-split':  ['h1', '.role-split-table', '[data-speakable]', '.sr-only'],",
        "test": "Role-split Speakable references the actual table via #role-split-table (not a dead class)",
    },
    {
        "name": "ai-knowhow の Speakable セレクタが解決しなくなる — home / role-split と**別のルート**の宣言で、独立に腐りうる (ページ側の class 名を変えれば片方だけ dead になる)。AIO 精度は route ごとに独立した契約なので、1 ルート被覆では他が守られない",
        "file": ROOT / "js" / "meta-management.js",
        "find": "            'ai-knowhow':  ['h1', '.ai-summary-block', '[data-speakable]', '.sr-only'],",
        "replace": "            'ai-knowhow':  ['h1', '.ai-summary-block-missing', '[data-speakable]', '.sr-only'],",
        "test": "ai-knowhow/about Speakable cssSelectors (non-baseline) resolve to real elements (AIO accuracy)",
    },
    {
        "name": "絞り込み select の focus 復元用 id が外れる — main.js _renderCore の復元は **id を鍵にする**ので、id を失ったコントロールだけが取り残されて change のたび focus が body へ落ちる。キーボード利用者は絞り込みを 1 段変えるたびに文書先頭へ戻され、**2 回目以降の操作ができない**。Check 422 は静的に id の存在を守るが、こちらは復元が実際に働くことを見る",
        "file": ROOT / "js" / "apps.js",
        "find": "                        id: 'task-filter-priority',\n",
        "replace": "",
        "test": "WCAG 2.1.1: 絞り込み select を変更しても focus が select に残る",
    },
    {
        "name": "AI 送信の連打ガードが外れる — `aiLoading` を条件から落とすと、キーリピートや連打で **描画が追いつく前に次の keydown が届き**、同じ会話が複数回 history に積まれる。1 回の送信が history エントリと 300ms の生成を伴うので、**会話ログが壊れ localStorage も無駄に膨らむ** (#1061 の task/todo Enter 連打と同 class の AI 面)",
        "file": ROOT / "js" / "ai-page.js",
        "find": "            if (!input.trim() || aiLoading) {return;}",
        "replace": "            if (!input.trim()) {return;}",
        "test": "AI 送信の連打で同じ会話が二重に積まれない",
    },
    {
        "name": "import の append 分岐が新規プロジェクトを取り込まなくなる — 既定モードは 'append' で、**バックアップからの復旧はこの経路を通る**。取り込みが no-op になっても「インポートが完了しました」とだけ出るので、利用者は復元できたと信じて元データを捨てうる (#1039/#1040 の silent no-op と同じ形の、既定経路版)",
        "file": ROOT / "js" / "settings-io.js",
        "find": "                        parsed.projects.forEach(p => { if (!existing.has(p.id)) { appended.push(p); } });",
        "replace": "",
        "test": "Settings import (valid JSON) appends projects and persists (data recovery)",
    },
    {
        "name": "詳細ページの推薦が非表示を無視して戻る (#886) — 隠したプロジェクトが「関連」「おすすめ」として他ページから提示され続ける。**推薦は利用者が自分で探していない経路**なので、隠したはずのものが向こうから出てくる形になる",
        "file": ROOT / "js" / "project-detail-page.js",
        "find": "        const listable = state.projects.filter(p => !hiddenIds.has(String(p.id)));",
        "replace": "        const listable = state.projects;",
        "test": "非表示は詳細の推薦とカテゴリ選択肢にも効く",
    },
    {
        "name": "カテゴリ選択肢が非表示を無視して戻る (#886) — そのカテゴリの project を全部隠しても選択肢が残り、**選ぶと 0 件になる死んだ選択肢**が生まれる。1 件だけ隠しても変化しない面なので、カテゴリを空にするまで setup しないと検査できない",
        "file": ROOT / "js" / "projects-page.js",
        "find": "            .filter(p => !_hiddenForCats.has(String(p.id)))\n",
        "replace": "",
        "test": "非表示は詳細の推薦とカテゴリ選択肢にも効く",
    },
    {
        "name": "一覧カードのデモが常に同じアプリへ飛ぶ — `apps/${p.demoRoute}` を固定値へ潰すと、どのカードのデモを押しても同じアプリが開く。**一覧は「作品を触る」までの最短導線**なので、閲覧者が最初に試す経路が死ぬ。Check 136 は demoRoute の値が router whitelist に含まれることを静的に守るが、**ボタンが正しいアプリへ遷移するか**は見ない",
        "file": ROOT / "js" / "projects-page.js",
        "find": "onclick: () => Router.navigate(`apps/${p.demoRoute}`) }, 'デモ')",
        "replace": "onclick: () => Router.navigate('apps/task') }, 'デモ')",
        "test": "一覧カードのデモボタンが対応する内蔵アプリを開く",
    },
    {
        "name": "ブランド選択が保存されなくなる — `set()` から `storage.set` だけ落とすと **適用は効くのにリロードで既定へ戻る**。既存のブランド関連テストは localStorage を直接 seed する pre-paint 検証と `data-brand` を直接書き換えるコントラスト検査だけで、**write 面が未被覆**だったため素通りしていた (#294 の producer/consumer class)。配色の単一ソースなので「設定したのに戻っている」形で出る",
        "file": ROOT / "js" / "brand.js",
        "find": "        const b = apply(brand);\n        storage.set(KEY, b);",
        "replace": "        apply(brand);",
        "test": "Settings のブランド選択がリロードを跨いで保持される",
    },
    {
        "name": "QUIZ_DATA_MAP の data 取り違え — pm の `data:` を別の問題集へ差し替えると、**見出しは QUIZ_DATA_MAP の `title` から出るので「PM問題集」のまま**で、中身だけ別の問題集になる。旧テストは見出しとブロックの存在しか見ておらず **緑のまま通っていた** (実測)。map 内の copy-paste 事故で現実に起こりうる形",
                "file": ROOT / "main.js",
        "find": "type === 'pm' ? import('./js/quiz/pm-quiz-data.js').then(m => m.pmQuizData)",
        "replace": "type === 'pm' ? import('./js/quiz/aws-quiz-data.js').then(m => m.awsQuizData)",
        "test": "Quiz pm and quality types render their data files",
    },
    {
        "name": "Cmd+K からプロジェクトが検索できなくなる — 候補生成でプロジェクトを落とすと、パレットは**全ルートから開ける横断導線**なので「どこからでもプロジェクトへ飛べる」経路が丸ごと死ぬ。ナビ項目は残るので**パレット自体は正常に見える**",
        "file": ROOT / "js" / "command-palette.js",
        "find": "            .filter(p => p && p.slug && p.name && !_hidden.has(String(p.id)))",
        "replace": "            .filter(() => false)",
        "test": "Command palette searches projects and jumps to a project detail",
    },
]
